Problems[12]={
 title:'置换复合：覆盖补集',
 statement:`函数 ${M.inline('f:A\\to A')} 的定义域和值域均为 ${M.inline('A=\\{1,2,3\\}')}，所有这样的函数组成全集 ${M.inline('B')}。非空 ${M.inline('C\\subseteq B')} 满足：补集中的每个函数均能由 ${M.inline('C')} 中两个函数（可相同）复合得到，求 ${M.inline('|C|')} 的最小值。〔原卷第2页〕`,
 mount(host){
  const C=Lab.C,perms=[[1,2,3],[2,1,3],[3,2,1],[1,3,2],[2,3,1],[3,1,2]],names=['e','s_{12}','s_{13}','s_{23}','r','r^2'];let chosen=new Set([1,4]),pair=[1,4],step=null;const show=n=>step===null||step>=n;
  const compose=(f,g)=>perms.findIndex(p=>p.every((v,i)=>v===perms[f][perms[g][i]-1]));
  function model(){const selected=[...chosen].sort(),products=[...new Set(selected.flatMap(f=>selected.map(g=>compose(f,g))))],outside=perms.map((_,i)=>i).filter(i=>!chosen.has(i)),missing=outside.filter(i=>!products.includes(i));return{selected,products,outside,missing,valid:selected.length>0&&missing.length===0};}
  const steps=[
   {title:'把函数变成六个置换',body:`定义域和值域均为三元集合，每个函数必须是双射，故共有 ${M.inline('3!=6')} 个。用 ${M.inline('(f(1),f(2),f(3))')} 表示映射，先列出全集 ${M.inline('B')}。`},
   {title:'选择集合 C，分出需要覆盖的补集',body:`勾选 ${M.inline('C')} 中的函数。未选中的才是必须复合得到的目标；条件不要求 ${M.inline('C')} 自己也被覆盖，且 ${M.inline('C')} 必须非空。`},
   {title:'按先右后左画复合映射',body:`选定 ${M.inline('f,g\\in C')} 后，先走 ${M.inline('g')}，再走 ${M.inline('f')}，得到 ${M.inline('f\\circ g')}。图中三条路都按同一个规则计算；交换次序可能得到不同函数。`},
   {title:'列出所有有序复合并检查漏项',body:`在表格中高亮行、列均来自 ${M.inline('C')} 的格子。它们的结果组成 ${M.inline('C\\circ C')}；红色标出尚未覆盖的补集元素。点高亮格可查看对应复合，不能只检查一个例子。`},
   {title:'用构造和下界确定最小值',body:`取 ${M.inline('C=\\{s_{12},r\\}')} 可覆盖其余四个置换。若 ${M.inline('|C|=1')}，仅能产生一个平方，而补集有五个元素，必不满足。故最小值为 ${M.inline('2')}。图中可加载这个最小构造，再删去一个元素观察漏项。`}
  ];
  host.innerHTML=`<div class="controls"><div id="q12-choices" style="display:flex;flex-wrap:wrap;gap:8px"></div><button id="q12-example">最小构造</button><button id="q12-swap">交换复合次序</button><span id="q12-composition"></span></div><div class="figures"><svg id="q12-map" class="figure" role="img" aria-label="先g后f的三列映射图"></svg><div class="figure" id="q12-table-wrap" style="padding:16px;overflow-x:auto"><div id="q12-table"></div></div></div><div class="readout" id="q12-readout"></div><div class="explain"><section class="proof-step"><h3>为什么只有六个函数</h3><p>三个输入覆盖三个输出，因此每个输出恰有一个原像，函数即三元置换。</p></section><section class="proof-step"><h3>两个函数足够</h3><p>令 ${M.inline('s_{12}=(2,1,3),\\ r=(2,3,1)')}，则</p>${M.block(String.raw`\begin{aligned}s_{12}^2&=e\\r^2&=(3,1,2)\\s_{12}\circ r&=s_{23}\\r\circ s_{12}&=s_{13}\end{aligned}`)}<p>恰好覆盖 ${M.inline('B\\setminus\\{s_{12},r\\}')}。</p></section><section class="proof-step"><h3>一个函数不够</h3><p>若 ${M.inline('C=\\{f\\}')}，所有允许复合只有 ${M.inline('f\\circ f')}，最多覆盖一个函数，不能覆盖补集的五个函数，故最小为 ${M.inline('2')}。</p></section></div>`;
  const choices=host.querySelector('#q12-choices');choices.innerHTML=perms.map((p,i)=>`<label style="border:1px solid var(--line);padding:6px 8px;border-radius:6px"><input type="checkbox" data-q12-perm="${i}">${M.inline(`${names[i]}=(${p.join(',')})`)}</label>`).join('');
  function render(){
   const m=model(),[f,g]=pair,result=compose(f,g);choices.querySelectorAll('input').forEach(el=>el.checked=chosen.has(+el.dataset.q12Perm));host.querySelector('#q12-composition').innerHTML=show(2)&&chosen.size?M.inline(`${names[f]}\\circ ${names[g]}=${names[result]}`):'';
   const p=Lab.plot(host.querySelector('#q12-map'),{xmin:0,xmax:4,ymin:0,ymax:4,equal:false,pad:44});
   if(show(2)&&chosen.size){const columns=[.35,2,3.65],ys=[3,2,1];for(let col=0;col<3;col++)for(let n=1;n<=3;n++){p.dot([columns[col],ys[n-1]],'',col===2?C.target:C.blue);p.math([columns[col],ys[n-1]],String(n),{size:19,dx:col===0?-17:14,dy:-5});}for(let n=1;n<=3;n++){const mid=perms[g][n-1],end=perms[f][mid-1];p.line([columns[0],ys[n-1]],[columns[1],ys[mid-1]],{stroke:C.blue,width:2.2});p.line([columns[1],ys[mid-1]],[columns[2],ys[end-1]],{stroke:C.target,width:2.2});}p.math([1.12,3.7],names[g],{color:C.blue,anchor:'middle',size:22});p.math([2.8,3.7],names[f],{color:C.target,anchor:'middle',size:22});p.screenText(16,p.h-15,'先走蓝线 g，再走红线 f；终点就是复合值。',{size:15});}
   else if(show(2))p.screenText(24,70,'C 不能为空，请先选取函数。',{color:C.target,size:20});
   else {perms.forEach((perm,i)=>{const cols=p.w>480?2:1,x=24+(i%cols)*p.w/cols,y=48+Math.floor(i/cols)*45;if(show(1))p.add(`<rect x="${x-10}" y="${y-23}" width="${Math.min(205,p.w/cols-28)}" height="36" rx="4" fill="${chosen.has(i)?C.blue:C.target}" opacity=".1"/>`);p.screenMath(x,y,`${names[i]}:(${perm.join(',')})`,{size:22,color:show(1)&&!chosen.has(i)?C.target:C.blue});});p.screenText(16,p.h-15,show(1)?'红色函数属于补集，是需要覆盖的目标。':'每个三元组按 f(1), f(2), f(3) 排列。',{size:15});}
   if(show(4))p.screenMath(16,27,String.raw`|C|_{\min}=2`,{color:C.target,size:21});p.finish();
   const table=host.querySelector('#q12-table');if(show(3)){table.innerHTML=`<p id="q12-coverage" style="margin:0 0 5px;color:${m.valid?C.green:C.target}">${m.missing.length?'未覆盖：'+m.missing.map(i=>M.inline(names[i])).join('、'):m.selected.length?'补集全部已覆盖。':'C 不能为空。'}</p><table style="border-collapse:collapse;width:100%;text-align:center;font-size:14px"><caption style="padding-bottom:5px">行是外层函数，列是内层函数</caption><thead><tr><th>${M.inline('\\circ')}</th>${names.map(n=>`<th style="padding:4px">${M.inline(n)}</th>`).join('')}</tr></thead><tbody>${perms.map((_,i)=>`<tr><th>${M.inline(names[i])}</th>${perms.map((_,j)=>{const on=chosen.has(i)&&chosen.has(j),r=compose(i,j);return`<td style="border:1px solid var(--line);padding:2px;${on?'background:color-mix(in srgb,var(--plot-green) 18%,transparent)':''}"><button data-q12-pair="${i},${j}" ${on?'':'disabled'} style="padding:2px;min-width:30px;min-height:24px;font-size:14px;border:0;background:transparent;color:${on?C.target:C.gray}">${M.inline(names[r])}</button></td>`;}).join('')}</tr>`).join('')}</tbody></table>`;table.querySelectorAll('[data-q12-pair]').forEach(b=>b.onclick=()=>{pair=b.dataset.q12Pair.split(',').map(Number);render();});}
   else table.innerHTML=`<p>${show(1)?`当前 ${M.inline('C=\\{'+m.selected.map(i=>names[i]).join(',')+'\\}')}；需要覆盖 ${m.outside.map(i=>M.inline(names[i])).join('、')||'空集'}。`:'先列全集，再选择集合 C。'}</p><p>复合表将在映射规则建立后出现。</p>`;
   host.querySelector('#q12-readout').innerHTML=`${M.inline(`|C|=${m.selected.length}`)}；${m.valid?'补集全部覆盖，满足条件。':m.selected.length?'还缺 '+m.missing.map(i=>M.inline(names[i])).join('、')+'。':'C 不能为空。'}${M.answer('最小值：'+M.inline('2'))}`;
  }
  choices.querySelectorAll('input').forEach(el=>el.onchange=()=>{const i=+el.dataset.q12Perm;if(el.checked)chosen.add(i);else chosen.delete(i);if(chosen.size){const first=[...chosen][0];pair=pair.map(v=>chosen.has(v)?v:first);}render();});host.querySelector('#q12-example').onclick=()=>{chosen=new Set([1,4]);pair=[1,4];render();};host.querySelector('#q12-swap').onclick=()=>{pair.reverse();render();};render();
  return{render,reset(){chosen=new Set([1,4]);pair=[1,4];if(step!==null)step=0;render();host.dispatchEvent(new Event('constructionchange'));},getState(){return{...model(),pair:[...pair],composition:compose(...pair),permutations:perms};},getConstructionSteps(){return steps;},getConstructionStep(){return step;},setConstructionStep(n){step=n===null?null:Math.max(0,Math.min(4,Math.trunc(Number(n)||0)));render();}};
 }
};
