Problems[16]={
 title:'轮换均值：三点为何共线',
 statement:`记 ${M.inline(String.raw`t_n=\frac{S_n}{n}`)}。若存在常数 ${M.inline('c')}，使任意两两不同的正整数 ${M.inline('i,j,k')} 都有 ${M.inline('(i-j)t_k+(j-k)t_i+(k-i)t_j=c')}，称原数列为“轮换均值数列”。判断：①任意等差数列都是；②存在公比不为 ${M.inline('1')} 的等比数列也是。〔原卷第3页〕`,
 mount(host){
  const C=Lab.C;let kind='arithmetic',first=2,d=1,ratio=1.5,indices=[1,2,3],step=null;const show=n=>step===null||step>=n;
  function model(){const terms=Array.from({length:9},(_,i)=>kind==='arithmetic'?first+i*d:first*ratio**i),means=[];let sum=0;terms.forEach((v,i)=>{sum+=v;means.push(sum/(i+1));});const [i,j,k]=indices,F=(i-j)*means[k-1]+(j-k)*means[i-1]+(k-i)*means[j-1];return{terms,means,F,area:Math.abs(F)/2,valid:kind==='arithmetic'||ratio===1};}
  const steps=[
   {title:'从前 n 项和得到平均值点',body:`由 ${M.inline(String.raw`t_n=\frac{S_n}{n}`)}，把前若干个均值画成 ${M.inline('(n,t_n)')}。切换等差、等比或改变参数后，所有均值均由当前原数列重新计算。`},
   {title:'选择三个不同指标并连成三角形',body:`选 ${M.inline('i,j,k')} 两两不同，连接 ${M.inline('(i,t_i),(j,t_j),(k,t_k)')}。原轮换式记为 ${M.inline('F(i,j,k)')}，其绝对值等于这个三角形面积的两倍。`},
   {title:'交换两个指标，观察有向量变号',body:`交换 ${M.inline('i,j')} 不改变三个点和普通面积，却使 ${M.inline('F(j,i,k)=-F(i,j,k)')}。题设要求每个有序三元组都等于同一常数，因此 ${M.inline('c=-c')}，即 ${M.inline('c=0')}。`},
   {title:'从全称条件推出全部均值点共线',body:`固定 ${M.inline('i=1,j=2')}，任取 ${M.inline('k=n')}，可得 ${M.inline('t_n=(2-n)t_1+(n-1)t_2')}。画出前两点确定的直线；所有正整数指标都必须在这条线上，有限点的观察不能代替这个推导。`},
   {title:'回到原数列，核对两个命题',body:`设 ${M.inline('t_n=\\alpha n+\\beta')}，则 ${M.inline('S_n=\\alpha n^2+\\beta n')}，从而 ${M.inline('a_n=\\alpha(2n-1)+\\beta')} 是等差数列。若又是等比，非零首项给出 ${M.inline('a_1(q-1)^2=0')}，只能 ${M.inline('q=1')}。因此①真②假，选 ${M.inline('A')}。`}
  ];
  host.innerHTML=`<div class="controls"><label>原数列 <select id="q16-kind"><option value="arithmetic">等差数列</option><option value="geometric">等比数列</option></select></label><label>首项 <input title="等比数列首项不能为零" id="q16-first" type="number" min="-5" max="5" step=".5" value="2"></label><label id="q16-d-control">公差 <input id="q16-d" type="range" min="-2" max="2" step=".1" value="1"></label><label id="q16-r-control" hidden>公比 <select id="q16-r"><option value="-1">−1</option><option value="0.5">1/2</option><option value="1">1</option><option value="1.5" selected>3/2</option><option value="2">2</option></select></label><label>指标组 <select id="q16-triple"><option value="1,2,3">1,2,3</option><option value="1,3,5">1,3,5</option><option value="2,5,8">2,5,8</option></select></label><button id="q16-swap">交换 i、j</button></div><div class="figures"><svg id="q16-mean" class="figure" role="img" aria-label="均值点与指标三角形"></svg><svg id="q16-terms" class="figure" role="img" aria-label="原数列的项值"></svg></div><div class="readout" id="q16-readout"></div><div class="explain"><section class="proof-step"><h3>交换指标消去常数</h3><p>题设的“任意”包含交换次序后的三元组。因此 ${M.inline('c=F(i,j,k)=-F(j,i,k)=-c')}，得 ${M.inline('c=0')}。</p></section><section class="proof-step"><h3>均值线性等价于原数列等差</h3>${M.block(String.raw`t_n=(2-n)t_1+(n-1)t_2=\alpha n+\beta`)}${M.block(String.raw`S_n=\alpha n^2+\beta n,\quad a_n=\alpha(2n-1)+\beta`)}<p>上式对 ${M.inline('n=1')} 也成立；反过来等差数列的前项均值线性，故①真。</p></section><section class="proof-step"><h3>非零首项排除第二命题</h3><p>若等比数列同时为等差，则</p>${M.block(String.raw`0=a_3-2a_2+a_1=a_1(q-1)^2`)}<p>高中等比数列的各项非零，所以 ${M.inline('a_1\\ne0')}，只能 ${M.inline('q=1')}；零数列不能作为②的例子。因此选A。</p></section></div>`;
  function render(){
   const m=model(),isAP=kind==='arithmetic',visibleN=Math.min(9,Math.max(...indices)+1),visibleMeans=m.means.slice(0,visibleN);host.querySelector('#q16-d-control').hidden=!isAP;host.querySelector('#q16-r-control').hidden=isAP;host.querySelector('#q16-first').value=first;
   const extent=values=>{let lo=Math.min(0,...values),hi=Math.max(0,...values);if(hi-lo<1){lo-=1;hi+=1;}const pad=(hi-lo)*.2;return{ymin:lo-pad,ymax:hi+pad};};
   const p=Lab.plot(host.querySelector('#q16-mean'),{xmin:0,xmax:visibleN+1,...extent(visibleMeans),equal:false,pad:43});p.axes({x:'n',y:''});p.screenMath(16,25,String.raw`t_n=\frac{S_n}{n}`,{size:20});
   const triangle=indices.map(n=>[n,m.means[n-1]]),avoidSegments=show(1)?triangle.map((a,i)=>[a,triangle[(i+1)%3]]):[];if(show(1))p.poly(triangle,{fill:C.target,stroke:C.target,opacity:.16,width:2});
   if(show(3)){const slope=m.means[1]-m.means[0],base=m.means[0]-slope;avoidSegments.push([[1,m.means[0]],[visibleN,slope*visibleN+base]]);p.line([1,m.means[0]],[visibleN,slope*visibleN+base],{stroke:C.green,dash:'6 4',width:2});}
   visibleMeans.forEach((v,i)=>{const chosen=show(1)&&indices.includes(i+1);p.dot([i+1,v],'',chosen?C.target:C.blue);if(chosen)p.math([i+1,v],`(${i+1},t_{${i+1}})`,{color:C.target,size:17,dx:9,dy:-15,avoidSegments});});
   if(show(2))p.screenMath(16,p.h-17,`F(${indices.join(',')})\\approx${M.number(m.F,4)}`,{size:18,color:C.target});p.finish();
   const q=Lab.plot(host.querySelector('#q16-terms'),{xmin:0,xmax:10,...extent(m.terms),equal:false,pad:43});q.axes({x:'n',y:''});q.screenText(16,25,'原数列项值',{size:18});if(show(4))m.terms.forEach((v,i)=>{q.line([i+1,0],[i+1,v],{stroke:C.target,width:1.3,opacity:.4});q.dot([i+1,v],'',C.target);});else q.screenText(16,60,'最后一步：由均值关系回到原数列。',{size:16,color:C.gray});q.finish();
   host.querySelector('#q16-readout').innerHTML=`${M.inline(`F(${indices.join(',')})\\approx${M.number(m.F,4)}`)}；三角形面积 ${M.inline('\\approx'+M.number(m.area,4))}。${m.valid?'当前数列满足全称条件。':'当前不是轮换均值数列；一般性结论见证明。'}${M.answer('A：①真，②假。')}`;
  }
  function modeChanged(){if(step!==null)step=0;render();host.dispatchEvent(new Event('constructionchange'));}
  host.querySelector('#q16-kind').onchange=e=>{kind=e.target.value;if(kind==='geometric'&&first===0)first=2;modeChanged();};host.querySelector('#q16-first').onchange=e=>{const v=+e.target.value;if(Number.isFinite(v)&&v>=-5&&v<=5&&(kind==='arithmetic'||v!==0))first=v;render();};host.querySelector('#q16-d').oninput=e=>{d=+e.target.value;render();};host.querySelector('#q16-r').onchange=e=>{ratio=+e.target.value;render();};host.querySelector('#q16-triple').onchange=e=>{indices=e.target.value.split(',').map(Number);render();};host.querySelector('#q16-swap').onclick=()=>{[indices[0],indices[1]]=[indices[1],indices[0]];render();};render();return{render,reset(){kind='arithmetic';first=2;d=1;ratio=1.5;indices=[1,2,3];host.querySelector('#q16-kind').value=kind;host.querySelector('#q16-d').value=d;host.querySelector('#q16-r').value=ratio;host.querySelector('#q16-triple').value='1,2,3';modeChanged();},getState(){return{kind,first,d,ratio,indices:[...indices],...model()};},getConstructionSteps(){return steps;},getConstructionStep(){return step;},setConstructionStep(n){step=n===null?null:Math.max(0,Math.min(4,Math.trunc(Number(n)||0)));render();}};
 }
};
