Problems[18]={
 title:'四棱锥：线面平行与投影角',
 statement:`四棱锥 ${M.inline('P-ABCD')} 中，${M.inline(String.raw`AD\parallel BC,\ \angle ADC=\angle PAB=90^\circ,\ BC=CD=\frac12AD`)}。${M.inline('E')} 是 ${M.inline('AD')} 中点，${M.inline(String.raw`PA\perp CD`)}。<span class="statement-part">（1）证明 ${M.inline(String.raw`CD\parallel\text{平面}\,PBE`)}。</span><span class="statement-part">（2）另给二面角 ${M.inline(String.raw`P-CD-A=45^\circ`)}，求 ${M.inline('PA')} 与平面 ${M.inline('PCE')} 所成角的正弦值。</span>〔原卷第4页〕`,
 mount(host){
  const C=Lab.C;let part=1,height=1.5,step=null,sceneKey='';const initialView={yaw:-.65,pitch:.44};
  const show=n=>step===null||step>=n,add=(a,b)=>a.map((v,i)=>v+b[i]),sub=(a,b)=>a.map((v,i)=>v-b[i]),scale=(a,s)=>a.map(v=>v*s),mid=(a,b)=>scale(add(a,b),.5);
  function model(){return{A:[2,0,0],B:[1,1,0],C:[0,1,0],D:[0,0,0],E:[1,0,0],P:[2,0,part===1?height:2],H:[14/9,-4/9,2/9],h:part===1?height:2};}
  const steps={1:[
   {title:'按长度比例画直角梯形底面',body:`由 ${M.inline(String.raw`AD\parallel BC,\ CD\perp AD,\ BC=CD=\frac12AD`)}，按比例令 ${M.inline('BC=CD=1,AD=2')}，画底面 ${M.inline('ABCD')}；统一缩放不影响平行和夹角。`},
   {title:'取中点 E，识别底面中的矩形',body:`${M.inline('E')} 是 ${M.inline('AD')} 中点，故 ${M.inline('DE=BC=1')}，且 ${M.inline(String.raw`DE\parallel BC`)}。标出 ${M.inline('E')}，四边形 ${M.inline('EBCD')} 是矩形。`},
   {title:'按垂直条件确定顶点方向',body:`${M.inline('PA')} 同时垂直 ${M.inline('AB')} 和 ${M.inline('CD')} 的方向，故垂直底面。沿 ${M.inline('A')} 的垂线取 ${M.inline('P')}，高度可变；第一问没有 ${M.inline(String.raw`45^\circ`)} 条件。`},
   {title:'在目标平面内寻找平行线',body:`连接 ${M.inline('BE')}。矩形 ${M.inline('EBCD')} 给出 ${M.inline(String.raw`BE\parallel CD`)}，其中 ${M.inline('BE')} 位于平面 ${M.inline('PBE')} 内。`},
   {title:'画目标平面，核对直线在面外',body:`画平面 ${M.inline('PBE')}。它与底面的交线为 ${M.inline('BE')}，而 ${M.inline('CD')} 与 ${M.inline('BE')} 平行且不重合，故 ${M.inline('CD')} 不在该平面内。由线面平行判定得所求结论。`}
  ],2:[
   {title:'先画公共条件确定的底面',body:`仍令 ${M.inline('BC=CD=DE=1,AD=2')}，画底面和中点 ${M.inline('E')}。本问将单独使用新增的二面角条件。`},
   {title:'把 45° 二面角画成截面角',body:`公共条件已给出 ${M.inline(String.raw`PA\perp\text{底面}`)}。${M.inline('DP,DA')} 都垂直棱 ${M.inline('CD')}，所以二面角就是 ${M.inline(String.raw`\angle PDA=45^\circ`)}，由 ${M.inline('AD=2')} 得 ${M.inline('PA=2')}。`},
   {title:'连接 C、E，画所求平面',body:`连接 ${M.inline('PC,PE,CE')}，标出平面 ${M.inline('PCE')}。所求是直线 ${M.inline('PA')} 与这个平面的角，不能用它与底面的直角代替。`},
   {title:'向平面作垂足 H',body:`从 ${M.inline('A')} 向平面 ${M.inline('PCE')} 作垂线，垂足为 ${M.inline('H')}。${M.inline('H')} 在三角形 ${M.inline('PCE')} 外，但仍在其所在平面内；补画必要的平面延伸和直角标记。`},
   {title:'用投影线识别角并求正弦',body:`连接 ${M.inline('PH')}，它是 ${M.inline('PA')} 在平面上的投影，因此所求角是 ${M.inline('\\angle APH')}。法向量可取 ${M.inline('\\boldsymbol n=(2,2,-1)')}，由 ${M.inline(String.raw`\sin\theta=\frac{|(0,0,1)\cdot\boldsymbol n|}{|\boldsymbol n|}=\frac13`)} 得答案；也有 ${M.inline(String.raw`\sin\theta=\frac{AH}{AP}=\frac{\frac23}{2}=\frac13`)}。`}
  ]};
  host.innerHTML=`<div class="controls"><label>小问 <select id="q18-part"><option value="1">（1）线面平行</option><option value="2">（2）线面角</option></select></label><label id="q18-height-label">${M.inline(String.raw`\frac{PA}{BC}`)} <input id="q18-height" type="range" min=".5" max="2.5" step=".02" value="1.5"></label><button id="q18-view">恢复视角</button><span class="hint">拖动旋转 · 滚轮缩放</span></div><div class="figures"><svg id="q18-space" class="main-figure" role="img" aria-label="可旋转的四棱锥及当前小问辅助线"></svg></div><div id="q18-readout" class="readout"></div><div id="q18-explain" class="explain"></div>`;
  const svg=host.querySelector('#q18-space'),view=Space.create(svg,{center:[1,.3,1],span:3.1,view:initialView});
  const restoreView=()=>view.setView({yaw:part===2?.65:-.65,pitch:.44,zoom:1});
  function makeScene(m){const points=[],edges=[],faces=[],annotations=[],one=part===1;
   const point=(name,at,color=C.ink)=>points.push({id:name,at,label:name,color,priority:90});const edge=(id,a,b,color=C.ink,width=2,extra={})=>edges.push({id,a,b,color,width,...extra});
   faces.push({id:'base',vertices:[m.A,m.B,m.C,m.D],color:C.green,opacity:.065});[['A',m.A],['B',m.B],['C',m.C],['D',m.D]].forEach(([n,v])=>point(n,v));[['AB','A','B'],['BC','B','C'],['CD','C','D'],['DA','D','A']].forEach(([id,a,b])=>edge(id,m[a],m[b],id==='CD'&&one&&show(3)?C.target:C.ink,id==='CD'&&one&&show(3)?4:2));
   annotations.push({id:'base-long',at:mid(m.A,m.D),tex:'2',color:C.green,size:18,dy:24},{id:'base-short',at:mid(m.B,m.C),tex:'1',color:C.green,size:18},{id:'base-side',at:mid(m.C,m.D),tex:'1',color:C.green,size:18});
   if(show(one?1:0))point('E',m.E,C.gold);
   if(show(one?2:1)){point('P',m.P);['A','B','C','D'].forEach(n=>edge('P'+n,m.P,m[n],!one&&n==='A'&&show(4)?C.target:C.ink,!one&&n==='A'&&show(4)?4:2));faces.push({id:'sidePAB',vertices:[m.P,m.A,m.B],color:C.ink,opacity:.045},{id:'sidePBC',vertices:[m.P,m.B,m.C],color:C.ink,opacity:.045},{id:'sidePCD',vertices:[m.P,m.C,m.D],color:C.ink,opacity:.045},{id:'sidePDA',vertices:[m.P,m.D,m.A],color:C.ink,opacity:.045});}
   if(one){if(show(3))edge('BE',m.B,m.E,C.green,3.5);if(show(4)){faces.push({id:'targetPlane',vertices:[m.P,m.B,m.E],color:C.blue,opacity:.22});edge('PE',m.P,m.E,C.blue,2.4);annotations.push({id:'parallel-result',at:mid(m.C,m.D),tex:String.raw`CD\parallel\text{平面}\,PBE`,color:C.target,size:21,priority:100,dy:32});}}
   else{
    if(show(1)){edge('DP-angle',m.D,m.P,C.gold,3);annotations.push({id:'height-given',at:mid(m.A,m.P),tex:'2',color:C.gold,size:20});for(let i=1;i<=18;i++){const arc=t=>[.48*Math.cos(t),0,.48*Math.sin(t)];edge('dihedral-'+i,arc(Math.PI/4*(i-1)/18),arc(Math.PI/4*i/18),C.gold,1.8,{occlude:false});}annotations.push({id:'dihedral-label',at:[.7,0,.3],tex:String.raw`45^\circ`,color:C.gold,size:20,priority:95});}
    if(show(2)){faces.push({id:'targetPlane',vertices:[m.P,m.C,m.E],color:C.blue,opacity:.23});edge('CE',m.C,m.E,C.blue,2.6);edge('PE',m.P,m.E,C.blue,2.6);}
    if(show(3)){point('H',m.H,C.gold);faces.push({id:'plane-extension',vertices:[m.P,m.E,m.H],color:C.blue,opacity:.09});edge('AH',m.A,m.H,C.gold,3.2,{occlude:false});edge('EH',m.E,m.H,C.blue,1.6,{dash:'5 5'});const u=scale(sub(m.A,m.H),.18),v=scale(sub(m.P,m.H),.07);edge('right1',add(m.H,u),add(add(m.H,u),v),C.gold,1.6,{occlude:false});edge('right2',add(add(m.H,u),v),add(m.H,v),C.gold,1.6,{occlude:false});}
    if(show(4)){edge('PH',m.P,m.H,C.target,3.5,{occlude:false});faces.push({id:'angleTriangle',vertices:[m.P,m.A,m.H],color:C.target,opacity:.06,occluder:false});annotations.push({id:'target-angle',at:mid(m.P,m.H),tex:String.raw`\sin\angle APH=\frac13`,color:C.target,size:22,priority:110,dx:-25},{id:'distance',at:mid(m.A,m.H),tex:String.raw`\frac23`,color:C.gold,size:18,priority:85});const theta=Math.asin(1/3),arc=t=>add(m.P,[-.5*Math.sin(t)/Math.sqrt(2),-.5*Math.sin(t)/Math.sqrt(2),-.5*Math.cos(t)]);for(let i=1;i<=16;i++)edge('theta-'+i,arc(theta*(i-1)/16),arc(theta*i/16),C.target,2,{occlude:false});}
   }
   return{points,edges,faces,annotations};
  }
  function render(){const m=model();host.querySelector('#q18-part').value=part;host.querySelector('#q18-height-label').hidden=part===2;const key=[part,height,step].join('|');if(key!==sceneKey){sceneKey=key;view.setScene(makeScene(m));}else view.render();
   host.querySelector('#q18-readout').innerHTML=part===1?`${M.inline(String.raw`\frac{PA}{BC}\approx${M.number(height,2)}`)}；第一问高度自由，未使用第二问二面角。${M.answer(M.inline(String.raw`CD\parallel\text{平面}\,PBE`))}`:`二面角 ${M.inline(String.raw`45^\circ`)} 给出 ${M.inline('PA=AD')}；红线 ${M.inline('PH')} 是投影线。${M.answer(M.inline(String.raw`\sin\angle(PA,\text{平面}\,PCE)=\frac13`))}`;
   host.querySelector('#q18-explain').innerHTML=part===1?`<section class="proof-step"><h3>先在底面内找平行线</h3><p>${M.inline('DE=BC')} 且 ${M.inline(String.raw`DE\parallel BC`)}，故 ${M.inline('EBCD')} 是平行四边形，又有直角，所以是矩形。因此 ${M.inline(String.raw`BE\parallel CD`)}。</p></section><section class="proof-step"><h3>核对直线在平面外</h3><p>平面 ${M.inline('PBE')} 与底面的交线为 ${M.inline('BE')}。${M.inline('CD')} 不与 ${M.inline('BE')} 相交，因而不在平面 ${M.inline('PBE')} 内；结合 ${M.inline(String.raw`BE\subset\text{平面}\,PBE`)} 得线面平行。</p></section>`:`<section class="proof-step"><h3>从公共条件得到垂直高</h3><p>过 ${M.inline('A')} 作 ${M.inline('CD')} 的平行线，它与 ${M.inline('AB')} 相交。${M.inline('PA')} 垂直这两条线，故垂直底面。于是 ${M.inline('DP,DA')} 都垂直 ${M.inline('CD')}，二面角等于 ${M.inline('\\angle PDA')}，得 ${M.inline('PA=AD=2')}。</p></section><section class="proof-step"><h3>为目标平面求法向量</h3><p>取 ${M.inline('D=(0,0,0),A=(2,0,0),C=(0,1,0),E=(1,0,0),P=(2,0,2)')}。平面 ${M.inline('PCE')} 方程为 ${M.inline('2x+2y-z-2=0')}，法向量 ${M.inline('\\boldsymbol n=(2,2,-1)')}。</p>${M.block(String.raw`\sin\theta=\frac{|(0,0,1)\cdot(2,2,-1)|}{\sqrt{2^2+2^2+(-1)^2}}=\frac13`)}</section><section class="proof-step"><h3>投影落在三角形外仍合法</h3><p>垂足 ${M.inline(String.raw`H=(\frac{14}9,-\frac49,\frac29)`)} 满足平面方程，且 ${M.inline(String.raw`AH=\frac23`)}、${M.inline('AP=2')}。因此同样有 ${M.inline(String.raw`\sin\angle APH=\frac{AH}{AP}=\frac13`)}。平面无限延伸，不能将三角形的边界误作平面的边界。</p></section>`;
  }
  host.querySelector('#q18-part').onchange=e=>{part=+e.target.value;if(step!==null)step=0;restoreView();render();host.dispatchEvent(new Event('constructionchange'));};host.querySelector('#q18-height').oninput=e=>{height=+e.target.value;render();};host.querySelector('#q18-view').onclick=restoreView;render();return{render,reset(){part=1;height=1.5;if(step!==null)step=0;host.querySelector('#q18-height').value=height;restoreView();render();host.dispatchEvent(new Event('constructionchange'));},getState(){return{part,height,...model(),sine:part===2?1/3:null,space:view.getState()};},getConstructionSteps(){return steps[part];},getConstructionStep(){return step;},setConstructionStep(n){step=n===null?null:Math.max(0,Math.min(4,Math.trunc(Number(n)||0)));render();},destroy(){view.destroy();}};
 }
};
