Problems[12] = {
  title: '绝对值：两段距离的和',
  statement: `已知 ${M.inline('x_1^2+y_1^2=x_2^2+y_2^2=1')}，${M.inline(String.raw`x_1x_2+y_1y_2=\dfrac12`)}。求 <span class="target">${M.inline(String.raw`\dfrac{|x_1+y_1-1|+|x_2+y_2-1|}{\sqrt2}`)} 的最小值</span>。`,
  mount(host) {
    const initial={angle:24,sign:1};let state={...initial},plot,drag=false;
    host.innerHTML=`<div class="controls"><label>${M.inline('P')} 的转角 <input id="q12-angle" type="range" min="0" max="360" step="0.2" value="24"> <output id="q12-angle-value"></output></label><label>${M.inline('Q')} 相对 ${M.inline('P')} <select id="q12-sign"><option value="1">逆时针 60°</option><option value="-1">顺时针 60°</option></select></label><button id="q12-boundary">一个点落在线上</button><span class="hint">拖动圆周改变两点位置</span></div><div class="figures"><svg id="q12-svg" class="main-figure" role="img" aria-label="单位圆上夹角固定的两点及它们到直线的距离"></svg></div><div class="readout" id="q12-readout"></div><div class="explain"><section class="proof-step"><h3>把绝对值读成距离</h3><p>${M.inline('P,Q')} 在单位圆上，${M.inline(String.raw`\overrightarrow{OP}\cdot\overrightarrow{OQ}=\cos\angle POQ=\dfrac12`)}，因此较小夹角为 ${M.inline(String.raw`60^\circ`)}。两项分别是 ${M.inline('P,Q')} 到直线 ${M.inline('x+y=1')} 的距离：</p>${M.block(String.raw`\begin{aligned}d_P&=\dfrac{|x_1+y_1-1|}{\sqrt2},\\d_Q&=\dfrac{|x_2+y_2-1|}{\sqrt2}.\end{aligned}`)}</section><section class="proof-step"><h3>先找临界位置</h3><p>一个点刚好在线上时，一项绝对值变号。点击“一个点落在线上”，可见另一点到直线的距离为 <span class="target">${M.inline(String.raw`\dfrac{\sqrt6-\sqrt2}{4}\approx0.259`)}</span>。仅找到此位置还不够，需要证明没有更小值。</p></section><section class="proof-step"><h3>证明没有更小值</h3><p>以直线法向为基准，设两点的方向角分别为 ${M.inline(String.raw`\gamma-\dfrac\pi6`)}、${M.inline(String.raw`\gamma+\dfrac\pi6`)}。利用</p>${M.block(String.raw`|u+v|+|u-v|=2\max\{|u|,|v|\}`)}<p>可将距离和写成</p><div class="target">${M.block(String.raw`\begin{aligned}F(\gamma)&=d_P+d_Q\\&=\max\bigl\{|\sqrt3\cos\gamma-\sqrt2|,\\&\qquad\qquad |\sin\gamma|\bigr\}.\end{aligned}`)}</div><p>利用对称只需考察 ${M.inline(String.raw`\gamma\in[0,\pi]`)}；${M.inline(String.raw`\gamma\ge\dfrac\pi2`)} 时第一项 ${M.inline(String.raw`\ge\sqrt2`)}。若 ${M.inline(String.raw`0\le\gamma\le\dfrac\pi{12}`)}，则第一项 ${M.inline(String.raw`\ge\sin\dfrac\pi{12}`)}；若 ${M.inline(String.raw`\dfrac\pi{12}\le\gamma\le\dfrac\pi2`)}，则第二项 ${M.inline(String.raw`\ge\sin\dfrac\pi{12}`)}。</p><p>当 ${M.inline(String.raw`\gamma=\dfrac\pi{12}`)} 时两项相等，因此 <span class="target">${M.inline(String.raw`\min F=\sin\dfrac\pi{12}=\dfrac{\sqrt6-\sqrt2}{4}`)}</span>。</p><p>这个证明统一了两点在直线同侧与异侧的分类。</p></section></div>`;
    const svg=host.querySelector('#q12-svg'),angle=host.querySelector('#q12-angle'),sign=host.querySelector('#q12-sign');
    function model(){const a=state.angle*Math.PI/180,b=a+state.sign*Math.PI/3,P=[Math.cos(a),Math.sin(a)],Q=[Math.cos(b),Math.sin(b)];const foot=X=>{const d=(X[0]+X[1]-1)/2;return [X[0]-d,X[1]-d];};const d1=Math.abs(P[0]+P[1]-1)/Math.sqrt(2),d2=Math.abs(Q[0]+Q[1]-1)/Math.sqrt(2);return {a,b,P,Q,H1:foot(P),H2:foot(Q),d1,d2,sum:d1+d2,dot:P[0]*Q[0]+P[1]*Q[1]};}
    function render(){const m=model(),C=Lab.C;angle.value=state.angle;sign.value=state.sign;host.querySelector('#q12-angle-value').textContent=Lab.fmt(state.angle,1)+'°';
      const p=Lab.plot(svg,{xmin:-1.32,xmax:1.65,ymin:-1.25,ymax:1.45,pad:38});plot=p;p.axes();p.circle([0,0],1,{stroke:C.ink,width:2});p.line([-0.6,1.6],[1.6,-0.6],{stroke:C.gray,width:2.5});p.math([1.3,-.3],'x+y=1',{color:C.ink,size:18,dx:8,dy:23});
      p.line([0,0],m.P,{stroke:C.blue,width:1.5,opacity:.6});p.line([0,0],m.Q,{stroke:C.gold,width:1.5,opacity:.6});
      const arc=[];for(let i=0;i<=24;i++){const t=m.a+state.sign*Math.PI/3*i/24;arc.push([.28*Math.cos(t),.28*Math.sin(t)]);}for(let i=1;i<arc.length;i++)p.line(arc[i-1],arc[i],{stroke:C.gray,width:1.5});const mid=(m.a+m.b)/2;p.text([.40*Math.cos(mid),.40*Math.sin(mid)],'60°',{color:C.gray,anchor:'middle',size:17,dy:6});
      [[m.P,m.H1,'H₁'],[m.Q,m.H2,'H₂']].forEach(([X,H,label])=>{const color=C.target;p.line(X,H,{stroke:color,width:4});if(Math.hypot(X[0]-H[0],X[1]-H[1])>.09){p.dot(H,label,color,10,17);const sg=Math.sign(X[0]+X[1]-1),u=[sg/Math.sqrt(2),sg/Math.sqrt(2)],v=[1/Math.sqrt(2),-1/Math.sqrt(2)],r=.055;const corner=[[H[0]+u[0]*r,H[1]+u[1]*r],[H[0]+(u[0]+v[0])*r,H[1]+(u[1]+v[1])*r],[H[0]+v[0]*r,H[1]+v[1]*r]];p.line(corner[0],corner[1],{stroke:color,width:1.1});p.line(corner[1],corner[2],{stroke:color,width:1.1});}});
      p.dot([0,0],'O',C.ink,-21,20);p.dot(m.P,'P',C.blue,m.P[0]<0?-24:11,m.P[1]<0?22:-11);p.dot(m.Q,'Q',C.gold,m.Q[0]<0?-25:11,m.Q[1]<0?22:-11);p.finish();
      const where=X=>Math.abs(X[0]+X[1]-1)<1e-9?'在线上':M.inline(X[0]+X[1]-1>0?'x+y-1>0':'x+y-1<0');
      host.querySelector('#q12-readout').innerHTML=`<span class="target">${M.inline(String.raw`d_P\approx${Lab.fmt(m.d1)}`)}</span><span class="target">${M.inline(String.raw`d_Q\approx${Lab.fmt(m.d2)}`)}</span><strong class="target">距离和 ${M.inline(String.raw`F=d_P+d_Q\approx${Lab.fmt(m.sum)}`)}</strong>${M.answer(M.inline(String.raw`\min F=\dfrac{\sqrt6-\sqrt2}{4}`))}<small>${M.inline('P')}：${where(m.P)}；${M.inline('Q')}：${where(m.Q)}。两点内积始终为 ${M.inline(String.raw`\dfrac12`)}。两段红线表示所求距离。</small>`;
    }
    angle.oninput=()=>{state.angle=+angle.value;render();};sign.onchange=()=>{state.sign=+sign.value;render();};host.querySelector('#q12-boundary').onclick=()=>{state.angle=state.sign===1?0:60;render();};
    function update(e){const [x,y]=plot.fromEvent(e);state.angle=(Math.atan2(y,x)*180/Math.PI+360)%360;render();}
    svg.style.touchAction='none';svg.style.cursor='grab';svg.addEventListener('pointerdown',e=>{drag=true;svg.setPointerCapture(e.pointerId);update(e);});svg.addEventListener('pointermove',e=>{if(drag)update(e);});svg.addEventListener('pointerup',()=>drag=false);svg.addEventListener('pointercancel',()=>drag=false);
    render();return {render,reset(){state={...initial};render();},getState(){return {...state,...model()};},destroy(){drag=false;}};
  }
};
