Problems[17] = {
  title: '斜三棱柱：高与辅助线',
  statement: `三棱柱 ${M.inline('ABC-A_1B_1C_1')} 中，${M.inline('AB=AC')}，侧面 ${M.inline('BB_1C_1C')} 垂直于底面 ${M.inline('ABC')}；${M.inline('E,F')} 分别为 ${M.inline('BC,A_1C_1')} 的中点。<span class="statement-part">（1）底面为边长 ${M.inline('2')} 的正三角形，${M.inline('CC_1=2')}，${M.inline('CC_1')} 与底面所成角为 ${M.inline(String.raw`60^\circ`)}，求 <span class="target">体积 ${M.inline('V')}</span>。</span><span class="statement-part">（2）证明 <span class="target">${M.inline(String.raw`EF\parallel\text{平面}\,AA_1B_1B`)}</span>。</span>`,
  mount(host) {
    const initial={part:1,shift:.7,height:1.45,base:1.4,yaw:.25,pitch:.5};let state={...initial},drag=null;
    host.innerHTML=`<div class="controls"><label>小问 <select id="q17-part"><option value="1">（1）侧棱与高</option><option value="2">（2）寻找平行线</option></select></label><label id="q17-shift-control">上底水平偏移 <input id="q17-shift" type="range" min="-0.8" max="1.4" step="0.02" value="0.7"></label><label id="q17-height-control">高 <input id="q17-height" type="range" min="0.6" max="2.1" step="0.02" value="1.45"></label><button id="q17-view">恢复视角</button><button id="q17-side">侧面正视</button><span class="hint">拖动图形旋转</span></div><div class="figures"><svg class="main-figure" id="q17-svg" role="img" aria-label="可旋转的斜三棱柱，观察垂直高和中点辅助线"></svg></div><div class="readout" id="q17-readout"></div><div class="explain" id="q17-explain"></div>`;
    const svg=host.querySelector('#q17-svg'),part=host.querySelector('#q17-part'),shift=host.querySelector('#q17-shift'),height=host.querySelector('#q17-height');
    const add=(a,b)=>a.map((v,i)=>v+b[i]),sub=(a,b)=>a.map((v,i)=>v-b[i]),mid=(a,b)=>a.map((v,i)=>(v+b[i])/2),norm=a=>Math.hypot(...a);
    function model(){const one=state.part===1,v=one?[1,0,Math.sqrt(3)]:[state.shift,0,state.height],A=[0,one?Math.sqrt(3):state.base,0],B=[-1,0,0],C=[1,0,0],A1=add(A,v),B1=add(B,v),C1=add(C,v),E=mid(B,C),F=mid(A1,C1),D=mid(A,B),H=[C1[0],C1[1],0];return {A,B,C,A1,B1,C1,E,F,D,H,v,height:v[2],baseArea:A[1],volume:A[1]*v[2],side:norm(v),ef:sub(F,E),da1:sub(A1,D)};}
    function render(){const m=model(),one=state.part===1,C=Lab.C;part.value=state.part;shift.value=state.shift;height.value=state.height;host.querySelector('#q17-shift-control').hidden=one;host.querySelector('#q17-height-control').hidden=one;host.querySelector('#q17-side').hidden=!one;
      const p=Lab.plot(svg,{xmin:-2.25,xmax:2.25,ymin:-1.45,ymax:1.7,pad:36});const cy=Math.cos(state.yaw),sy=Math.sin(state.yaw),cp=Math.cos(state.pitch),sp=Math.sin(state.pitch);const center=[.25,.55,.7];const project=q=>{const[x,y,z]=sub(q,center);return [x*cy-y*sy,z*cp-(x*sy+y*cy)*sp];};const line=(a,b,opts)=>p.line(project(a),project(b),opts),poly=(arr,opts)=>p.poly(arr.map(project),opts);
      poly([m.A,m.B,m.C,m.A],{fill:'var(--plot-fill)',stroke:C.gray,width:1,opacity:.4});
      poly([m.B,m.C,m.C1,m.B1,m.B],{fill:'var(--plot-fill)',stroke:C.gray,width:1,opacity:.24});
      if(!one)poly([m.A,m.A1,m.B1,m.B,m.A],{fill:C.blue,stroke:C.blue,width:1,opacity:.14});
      [[m.A,m.B],[m.B,m.C],[m.C,m.A],[m.A1,m.B1],[m.B1,m.C1],[m.C1,m.A1],[m.A,m.A1],[m.B,m.B1],[m.C,m.C1]].forEach(([a,b])=>line(a,b,{stroke:C.ink,width:2}));
      if(one){
        line(m.C,m.H,{stroke:C.gray,width:2,dash:'5 4'});line(m.C,m.C1,{stroke:C.blue,width:3.5});line(m.C1,m.H,{stroke:C.gold,width:3.5});
        const r=.13;line([m.H[0]-r,0,0],[m.H[0]-r,0,r],{stroke:C.gold,width:1.4});line([m.H[0]-r,0,r],[m.H[0],0,r],{stroke:C.gold,width:1.4});
        const arc=[];for(let i=0;i<=18;i++){const a=Math.PI/3*i/18;arc.push([m.C[0]+.39*Math.cos(a),0,.39*Math.sin(a)]);}for(let i=1;i<arc.length;i++)line(arc[i-1],arc[i],{stroke:C.gold,width:1.5});p.text(project([m.C[0]+.54,0,.23]),'60°',{color:C.gold,size:18});
        p.math(project(mid(m.C,m.C1)),'2',{color:C.blue,dx:-18,dy:-2,size:20});p.math(project(mid(m.C1,m.H)),String.raw`h=\sqrt3`,{color:C.gold,dx:12,dy:2});p.math(project(mid(m.C,m.H)),String.raw`\text{投影}\ 1`,{color:C.gray,dx:-24,dy:22,size:16});p.dot(project(m.H),'H',C.gold,9,21);
        p.math(project([0,m.A[1]/3,0]),String.raw`S_{\text{底}}=\sqrt3`,{color:C.green,anchor:'middle',dy:16,size:18});
        p.screenMath(16,p.h-18,String.raw`V=S_{\text{底}}\,h=3`,{color:C.target,size:23});
      } else {
        line(m.E,m.F,{stroke:C.target,width:4});p.dot(project(m.E),'E',C.target,-24,20);p.dot(project(m.F),'F',C.target,10,-12);
        p.add('<g class="aux">');poly([m.E,m.D,m.A1,m.F,m.E],{fill:C.green,stroke:'none',opacity:.28});line(m.D,m.A1,{stroke:C.green,width:3.5});line(m.E,m.D,{stroke:C.gold,width:2.5,dash:'5 4'});line(m.F,m.A1,{stroke:C.gold,width:2.5});p.dot(project(m.D),'D',C.gold,-24,-8);p.add('</g>');
        p.screenText(16,24,'蓝色面：AA₁B₁B　红色线：EF',{color:C.gray,size:16});
        p.add('<g class="aux">');p.math(project(mid(m.D,m.A1)),'DA_1',{color:C.green,dx:-48,dy:0,size:19});p.screenMath(16,p.h-18,String.raw`EF\parallel DA_1\subset\text{平面}\,AA_1B_1B`,{color:C.target,size:22});p.add('</g>');
      }
      [[m.A,'A',C.ink,0,22],[m.B,'B',C.ink,-22,18],[m.C,'C',C.ink,-16,23],[m.A1,'A₁',C.ink,8,-12],[m.B1,'B₁',C.ink,-27,-9],[m.C1,'C₁',one?C.blue:C.ink,9,-12]].forEach(([pt,label,color,dx,dy])=>p.dot(project(pt),label,color,dx,dy));p.finish();
      host.querySelector('#q17-readout').innerHTML=one?`<span style="color:${C.green}">${M.inline(String.raw`S_{\text{底}}=\sqrt3`)}</span><span style="color:${C.blue}">侧棱 ${M.inline('CC_1=2')}</span><span style="color:${C.gold}">高 ${M.inline(String.raw`h=\sqrt3`)}</span>${M.answer('（1）体积 '+M.inline('V=3'))}<small>${M.inline(String.raw`\triangle CC_1H`)} 是线面角所在的直角三角形。旋转视角，侧棱和高的真实长度不会改变。</small>`:`<span>高 ${M.inline(String.raw`h\approx${Lab.fmt(m.height,2)}`)}</span><span>上底水平偏移 ${M.inline(Lab.fmt(state.shift,2))}</span><span class="aux target">${M.inline(String.raw`|EF|\approx${Lab.fmt(norm(m.ef))}`)}</span><span class="aux" style="color:${C.green}">${M.inline(String.raw`|DA_1|\approx${Lab.fmt(norm(m.da1))}`)}</span>${M.answer('（2）'+M.inline(String.raw`EF\parallel\text{平面}\,AA_1B_1B`))}<small>第二问为一般构型，不沿用第一问的边长与 ${M.inline(String.raw`60^\circ`)}。显示关键关系后，观察绿色 ${M.inline('DA_1')} 与红色 ${M.inline('EF')}。</small>`;
      host.querySelector('#q17-explain').innerHTML=one?`<section class="proof-step"><h3>先求垂直高</h3><p>侧面 ${M.inline('BB_1C_1C')} 垂直于底面，所以侧棱在底面内的投影沿 ${M.inline('BC')} 所在直线。</p>${M.block(String.raw`h=CC_1\sin60^\circ=2\cdot\dfrac{\sqrt3}{2}=\sqrt3`)}</section><section class="proof-step"><h3>底面积乘垂直高</h3><div class="target">${M.block(String.raw`V=S_{\text{底}}\,h=\dfrac{\sqrt3}{4}\cdot2^2\cdot\sqrt3=3`)}</div><p>${M.inline('H')} 可以落在底面三角形之外，仍然是 ${M.inline('C_1')} 到底面所在平面的垂足。</p></section>`:`<section class="proof-step"><h3>辅助线为什么选 ${M.inline('DA_1')}</h3><p>取 ${M.inline('AB')} 中点 ${M.inline('D')}。在 ${M.inline(String.raw`\triangle ABC`)} 中，${M.inline(String.raw`ED\parallel CA`)} 且 ${M.inline(String.raw`ED=\dfrac{CA}{2}`)}；又 ${M.inline(String.raw`FA_1\parallel CA`)} 且 ${M.inline(String.raw`FA_1=\dfrac{CA}{2}`)}，所以 ${M.inline('EDA_1F')} 是平行四边形，<span class="target">${M.inline(String.raw`EF\parallel DA_1`)}</span>。</p><p>${M.inline('DA_1')} 在平面 ${M.inline('AA_1B_1B')} 内，${M.inline('E')} 不在该平面内，故 <span class="target">${M.inline(String.raw`EF\parallel\text{平面}\,AA_1B_1B`)}</span>。</p></section><section class="proof-step"><h3>用向量解释同一关系</h3><p>设侧棱向量为 ${M.inline(String.raw`\vec v`)}，则</p>${M.block(String.raw`\overrightarrow{EF}=\vec v+\dfrac12\overrightarrow{BA}=\overrightarrow{DA_1}`)}<p>拖动高和水平投影，这个等式仍然成立；证明只用了中点与棱柱的平移关系。</p></section>`;
    }
    part.onchange=()=>{state.part=+part.value;state.yaw=initial.yaw;state.pitch=initial.pitch;render();};shift.oninput=()=>{state.shift=+shift.value;render();};height.oninput=()=>{state.height=+height.value;render();};host.querySelector('#q17-view').onclick=()=>{state.yaw=initial.yaw;state.pitch=initial.pitch;render();};host.querySelector('#q17-side').onclick=()=>{state.yaw=0;state.pitch=0;render();};
    svg.style.touchAction='none';svg.style.cursor='grab';svg.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,yaw:state.yaw,pitch:state.pitch};svg.setPointerCapture(e.pointerId);});svg.addEventListener('pointermove',e=>{if(!drag)return;state.yaw=drag.yaw+(e.clientX-drag.x)*.008;state.pitch=Math.max(-1.35,Math.min(1.35,drag.pitch+(e.clientY-drag.y)*.008));render();});svg.addEventListener('pointerup',()=>drag=null);svg.addEventListener('pointercancel',()=>drag=null);
    render();return {render,reset(){state={...initial};render();},getState(){return {...state,...model()};},destroy(){drag=null;}};
  }
};
