/* Exact models shared by diagrams, readouts and regression checks. */
(function(root){
 const add=(a,b)=>a.map((v,i)=>v+b[i]),sub=(a,b)=>a.map((v,i)=>v-b[i]),scale=(a,k)=>a.map(v=>v*k),dot=(a,b)=>a.reduce((t,v,i)=>t+v*b[i],0),norm=a=>Math.hypot(...a),mid=(a,b)=>scale(add(a,b),.5);
 function lookout(degrees){const t=degrees*Math.PI/180,O=[0,0],A=[0,100],B=[200*Math.cos(t),200*Math.sin(t)],AB=norm(sub(A,B)),angle=Math.acos(Math.max(-1,Math.min(1,dot(sub(A,B),sub(O,B))/(AB*200))));return{O,A,B,AB,angle,degrees};}
 function vectors(degrees){const t=degrees*Math.PI/180,u=4*Math.cos(t),v=Math.sqrt(11.5)*Math.sin(t),A=[1.5+(u-v)/Math.SQRT2,1.5+(u+v)/Math.SQRT2],C=[-A[1],A[0]],B=[-3-C[0],3-C[1]];return{A,B,C,sum:add(A,B),length:norm(A)+norm(B),value:A[0]+B[0],u,v,degrees};}
 function slice(d){return{d,a:d/2,b:d,cosine:3/5,angle:Math.acos(3/5)};}
 const tetra=[[0,0,0],[1,0,0],[0,1,0],[0,0,1]];
 const solutions=[...[0,1,2].map(i=>[0,0,0].map((_,j)=>i===j?.5:0)),...[0,1,2].map(i=>[.5,.5,.5].map((v,j)=>i===j?0:v)),...[0,1,2].map(i=>[.25,.25,.25].map((v,j)=>i===j?.5:v)),[1/3,1/3,1/3]];
 function distances(P){const squares=tetra.map(v=>dot(sub(P,v),sub(P,v))),groups=[];squares.forEach(v=>{if(!groups.some(w=>Math.abs(v-w)<1e-10))groups.push(v);});return{P,squares,distances:squares.map(Math.sqrt),distinct:groups.length,valid:groups.length===2&&!squares.some(v=>v<1e-20)};}
 function tetraPoint(mode,t,index){return distances(mode==='solutions'?solutions[index]:mode==='leg'?[t,0,0]:[t,(1-t)/2,(1-t)/2]);}
 function pyramid(){return{A:[0,0,0],B:[2,0,0],C:[1,1,0],D:[0,1,0],P:[0,0,1],Q:[1,0,.5],E:[0,0,.5],H:[.5,.5,0],distance:Math.SQRT1_2};}
 function chord(degrees){const theta=degrees*Math.PI/180,u=Math.cos(theta),v=Math.sin(theta),den=4-u*u,F=[1,0],t1=(-3*u+6)/den,t2=(-3*u-6)/den,s1=2/(1+v),s2=-2/(1-v),A=add(F,scale([u,v],t1)),B=add(F,scale([u,v],t2)),C=add(F,scale([-v,u],s1)),D=add(F,scale([-v,u],s2));return{degrees,F,A,B,C,D,M:mid(A,B),AB:12/den,CD:4/(u*u),area:24/(u*u*den)};}
 function tpoints(a){let sines;if(a===0)sines=[0];else{const d=Math.sqrt(1+32*a*a);sines=[4*a/(1+d),-(1+d)/(8*a)];}const xs=[];for(let s of sines){if(Math.abs(s)>1+1e-12)continue;if(Math.abs(Math.abs(s)-1)<1e-12)s=Math.sign(s);if(s===0){xs.push(Math.PI);continue;}const h=Math.asin(s),r=s>0?[h,Math.PI-h]:[Math.PI-h,2*Math.PI+h];for(const x of r)if(!xs.some(y=>Math.abs(y-x)<1e-10))xs.push(x);}return{a,sines,xs:xs.sort((x,y)=>x-y),count:xs.length};}
 function harmony(left,ratio,b){const right=left*ratio,m=(left+right)/2,secant=Math.log(ratio)/(right-left)+b*(left+right),tangent=1/m+2*b*m;return{left,right,m,b,ratio,secant,tangent,gap:secant-tangent};}
 function mount(host,c){const initial={...c.initial};let s={...initial},step=null;const prefix='js25-'+c.id;host.innerHTML=`<div class="controls">${c.controls}</div><div class="figures"><svg id="${prefix}-svg" class="${c.dual?'figure':'main-figure'}" aria-label="${c.title}"></svg>${c.dual?`<svg id="${prefix}-second" class="figure" aria-label="${c.dual}"></svg>`:''}</div><div id="${prefix}-readout" class="readout" aria-live="polite"></div><div id="${prefix}-proof" class="explain"></div>`;const svg=host.querySelector('#'+prefix+'-svg'),second=host.querySelector('#'+prefix+'-second'),read=host.querySelector('#'+prefix+'-readout'),proof=host.querySelector('#'+prefix+'-proof');host.querySelectorAll('[data-k]').forEach(e=>{e.id=prefix+'-'+e.dataset.k;});host.querySelectorAll('[data-action]').forEach(e=>e.id=prefix+'-'+e.dataset.action);const view=c.space?Space.create(svg,c.space):null;
  function render(){host.querySelectorAll('[data-k]').forEach(e=>{if(e.type==='checkbox')e.checked=!!s[e.dataset.k];else e.value=s[e.dataset.k];});c.sync?.(host,s);const show=n=>step===null||step>=n;c.draw(svg,s,show,view,second);read.innerHTML=c.read(s);proof.innerHTML=typeof c.proof==='function'?c.proof(s):c.proof;}
  function restart(){if(step!==null)step=0;host.dispatchEvent(new Event('constructionchange'));}
  host.querySelectorAll('[data-k]').forEach(e=>{e.addEventListener(e.tagName==='SELECT'||e.type==='checkbox'?'change':'input',()=>{const k=e.dataset.k;s[k]=e.type==='checkbox'?e.checked:typeof initial[k]==='number'?+e.value:e.value;c.change?.(s,k);if(e.tagName==='SELECT')restart();render();});});host.querySelectorAll('[data-action]').forEach(e=>e.onclick=()=>{c.action?.(s,e.dataset.action);restart();render();});
  return{render,reset(){s={...initial};view?.resetView();restart();render();},getState:()=>({...s,...c.model?.(s),...(view?{space:view.getState()}:{})}),getConstructionSteps:()=>c.steps,getConstructionStep:()=>step,setConstructionStep(n){step=n===null?null:Math.max(0,Math.min(c.steps.length-1,+n));render();},destroy(){view?.destroy();}};
 }
 const api={add,sub,scale,dot,norm,mid,lookout,vectors,slice,tetra,solutions,distances,tetraPoint,pyramid,chord,tpoints,harmony,mount};root.Jinshan25=api;if(typeof module==='object'&&module.exports)module.exports=api;
})(typeof window==='object'?window:globalThis);
