const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs'),{pathToFileURL}=require('node:url');
const {launchBrowser,reportFailure}=require('./browser-runtime.cjs');
const root=path.resolve(__dirname,'..'),shots=process.env.XH24_SHOTS;
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);
async function main(){const browser=await launchBrowser(),errors=[];try{for(const width of [1280,1920]){const page=await browser.newPage({viewport:{width,height:width===1280?720:1080}});page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.join(root,'papers/xuhui-2024/index.html')).href);await page.waitForFunction(()=>window.Lesson);const select=async id=>{await page.evaluate(id=>Lesson.select(id),id);await page.waitForTimeout(100);},state=()=>page.evaluate(()=>Lesson.getState()),input=async(id,v)=>page.locator(id).evaluate((el,v)=>{el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}));},String(v)),snap=async label=>{if(shots){fs.mkdirSync(shots,{recursive:true});await page.screenshot({path:path.join(shots,`${width}-${label}.png`)});}};
for(const id of [10,12,18,19,21]){await select(id);assert.equal(await page.locator('.katex-error').count(),0,`q${id} TeX`);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);await snap('q'+id);}
await select(10);for(const angle of [10,30,45,60,80]){await input('#xh24-10-angle',angle);const s=await state();assert.ok(s.length>=6*Math.sqrt(2)-2-1e-8);near(Math.hypot(s.E[0]-s.B[0],s.E[1]-s.B[1]),1);}await page.locator('#xh24-10-critical').click();near((await state()).length,6*Math.sqrt(2)-2);
await select(12);for(const [selector,max]of [['#xh24-12-left',8],['#xh24-12-excluded',7],['#xh24-12-right',8]]){await page.locator(selector).click();assert.equal((await state()).maximum,max);}await input('#xh24-12-a',1);assert.equal((await state()).maximum,null);
await select(18);await page.locator('#xh24-18-part').selectOption('2');await page.locator('#keyButton').click();await page.waitForTimeout(120);const d=await state(),sub=(a,b)=>a.map((x,i)=>x-b[i]),dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),v=sub(d.P,d.M),u=sub(d.U,d.M),w=sub(d.V,d.M);near(dot(u,v),0);near(dot(w,v),0);near(Math.sqrt(1-dot(u,w)**2/dot(u,u)/dot(w,w)),Math.sqrt(30)/6);await snap('q18-key');
await select(19);await page.locator('#xh24-19-optimum').click();const optimum=await state();near(optimum.op,250*Math.sqrt(2)*(1-1/Math.sqrt(3)));for(const angle of [45.2,55,75,100,112.3]){await input('#xh24-19-angle',angle);const s=await state();assert.ok(s.op>0&&s.op<500);assert.ok(s.total>=optimum.total-1e-8);near(Math.hypot(s.P[0]-1,s.P[1])*500,s.pa);}
await select(21);await page.locator('#xh24-21-part').selectOption('2');await snap('q21-min');await page.locator('#xh24-21-part').selectOption('3');await page.locator('#xh24-21-zero').click();near((await state()).drift,0);await snap('q21-periodic');await page.close();}assert.deepEqual(errors,[]);console.log('Xuhui 2024: models, endpoints, controls and 1280/1920 browser checks passed.');}finally{await browser.close();}}
main().catch(reportFailure);
