const assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');
const {launchBrowser,reportFailure}=require('./browser-runtime.cjs');
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`),dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0);
(async()=>{const browser=await launchBrowser();try{const page=await browser.newPage({viewport:{width:1280,height:720}}),errors=[],external=[];page.on('pageerror',e=>errors.push(String(e)));page.on('request',r=>{if(/^https?:/.test(r.url()))external.push(r.url());});await page.context().setOffline(true);await page.goto(pathToFileURL(path.join(__dirname,'../papers/putuo-2024/index.html')).href);const select=id=>page.locator(`#questionNav [data-question="${id}"]`).click(),state=()=>page.evaluate(()=>Lesson.getState());
await select(7);for(const a of [-2,-1,0,1,3]){await page.locator(`[data-action="${a}"]`).click();assert.equal((await state()).a,a);const count=[-1,0,2].filter(x=>Math.abs(x-a)<1).length;assert.match(await page.locator('#pt24-7-read').innerText(),new RegExp('真子集有\\s*'+(2**count-1)));}
await select(10);await page.locator('[data-action="answer"]').click();near((await state()).ratio,2);const before=await state();await page.locator('#pt24-10-phi').focus();await page.locator('#pt24-10-phi').press('End');near((await state()).AB,before.AB);near((await state()).BC,before.BC);
await select(12);for(const face of ['0','1','2','3']){await page.locator('#pt24-12-face').selectOption(face);for(const key of ['Home','End']){await page.locator('#pt24-12-u').focus();await page.locator('#pt24-12-u').press(key);let s=await state();near(Math.hypot(...s.M),s.r);near(Math.hypot(...s.M.map((x,i)=>x-s.N[i])),2*s.r);near(s.dot,dot(s.M.map((x,i)=>x-s.P[i]),s.N.map((x,i)=>x-s.P[i])));assert.ok(s.dot<=1/3+1e-9);}}await page.locator('#pt24-12-max').click();near((await state()).dot,1/3);const d=(await state()).dot;await page.locator('#pt24-12-angle').focus();await page.locator('#pt24-12-angle').press('End');near((await state()).dot,d);
await select(16);for(const [m,n]of[[-1.5,1],[0,2],[3,2],[9,1],[12,2]]){await page.locator(`[data-action="${m}"]`).click();const s=await state();assert.equal(s.roots.length,n);for(const x of s.roots){assert.ok(x>=-1&&x<1);const f=x<0?x+1:(3*x-2)/(1-x);near(f-m*x+2*m/3,0);}}assert.deepEqual((await state()).roots,[2/3,3/4]);
await select(19);await page.locator('#drawButton').click();await page.locator('#constructionNext').click();assert.equal((await page.evaluate(()=>Lesson.getConstruction())).step,1);await page.locator('[data-action="left"]').click();assert.equal((await page.evaluate(()=>Lesson.getConstruction())).step,0);near((await state()).m,1/3);assert.equal((await state()).part,'2');await page.locator('#constructionFull').click();await page.locator('[data-action="right"]').click();near((await state()).m,5);
await select(21);await page.locator('#pt24-21-n').focus();await page.locator('#pt24-21-n').press('Home');assert.equal((await state()).difference,1);await page.locator('#pt24-21-n').press('ArrowRight');await page.locator('#pt24-21-n').press('ArrowRight');assert.equal((await state()).difference,2);await page.locator('#pt24-21-part').selectOption('2');assert.equal((await state()).tExact,-1);await page.locator('#pt24-21-part').selectOption('3');const text=await page.locator('#pt24-21-read').innerText();await page.locator('#pt24-21-t').focus();await page.locator('#pt24-21-t').press('End');assert.notEqual(await page.locator('#pt24-21-read').innerText(),text);assert.ok((await state()).values.every(x=>x>1));assert.ok((await state()).gap>0);
assert.deepEqual(errors,[]);assert.deepEqual(external,[]);console.log('PASS PT2024 exact endpoint presets, diameter/dot invariants, source-error counterexample, definition checks and construction reset.');}finally{await browser.close();}})().catch(reportFailure);
