const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs'),{pathToFileURL}=require('node:url');
const {launchBrowser,reportFailure}=require('./browser-runtime.cjs');const root=path.resolve(__dirname,'..'),shots=process.env.JA24_SHOTS;
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);
async function main(){const browser=await launchBrowser(),errors=[],network=[];try{for(const width of [1280,1920]){const page=await browser.newPage({viewport:{width,height:width===1280?720:1080}});page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url());});await page.goto(pathToFileURL(path.join(root,'papers/jingan-2024/index.html')).href);await page.waitForFunction(()=>window.Lesson);const select=async id=>{await page.evaluate(id=>Lesson.select(id),id);await page.waitForTimeout(100);},state=()=>page.evaluate(()=>Lesson.getState()),input=async(id,v)=>page.locator(id).evaluate((el,v)=>{el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}));},String(v)),snap=async label=>{if(shots){fs.mkdirSync(shots,{recursive:true});await page.screenshot({path:path.join(shots,`${width}-${label}.png`)});}};
for(const id of [9,12,16,19,21]){await select(id);assert.equal(await page.locator('.katex-error').count(),0,`q${id} TeX`);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);await snap('q'+id);}
await select(9);for(const t of [0,.4,1.5,2,4]){await input('#ja24-9-t',t);const s=await state();near(s.E[0],2);near(s.E[1],t);near(s.normal.reduce((r,v,i)=>r+v*(s.H[i]-s.P[i]),0),0);near(s.distance/Math.sqrt(8),s.sine);}await page.locator('#ja24-9-solve').click();near((await state()).sine,Math.sqrt(3)/6);await page.locator('#keyButton').click();await page.waitForTimeout(100);await snap('q9-solved');
await select(12);await page.locator('#ja24-12-boundary').click();assert.equal((await state()).exists,false);await page.locator('#ja24-12-inside').click();assert.equal((await state()).exists,true);await snap('q12-near-boundary');
await select(16);for(const d of [0,1,2,3]){await page.locator('#ja24-16-case').selectOption(String(d));for(const t of [-1,-.2,.6,1]){await input('#ja24-16-u',t);const s=await state();near(s.pointDistance,s.circleDistance);}await snap('q16-case'+d);}
await select(19);near((await state()).length,2*Math.sqrt(15));await page.locator('#ja24-19-part').selectOption('2');for(const y of [-3,-1,0,2,3]){await input('#ja24-19-y',y);const s=await state();near(s.P[0]**2/2-s.P[1]**2,1);near(-(s.P[0]**2)+(s.y-1)**2,s.k);}await page.locator('#ja24-19-zero').click();near((await state()).k,0);await snap('q19-dotzero');
await select(21);for(const total of [.1,.5,.98])for(const ratio of [.05,.5,.95]){await input('#ja24-21-s',total);await input('#ja24-21-t',ratio);const s=await state();assert.ok(s.x1>0&&s.x2>0&&s.x1+s.x2<1&&s.gap>0);}await page.locator('#ja24-21-part').selectOption('2');for(const b of [1,1.5,2]){await input('#ja24-21-b',b);assert.ok((await state()).gap>0);}await input('#ja24-21-b',.5);assert.equal((await state()).validL,false);await snap('q21-invalidb');await page.locator('#ja24-21-part').selectOption('3');for(const m of [.1,1,2,3.9]){await input('#ja24-21-m',m);const s=await state();assert.ok(s.x0>0&&s.x0<1);near(s.value,s.m);}await snap('q21-range');await page.close();}assert.deepEqual(errors,[]);assert.deepEqual(network,[]);console.log('Jingan 2024: models, endpoints, controls, offline and 1280/1920 browser checks passed.');}finally{await browser.close();}}
main().catch(reportFailure);
