const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const {launchBrowser,reportFailure}=require('./browser-runtime.cjs');
(async()=>{
  const output=path.join(__dirname,'screenshots');fs.mkdirSync(output,{recursive:true});
  const browser=await launchBrowser();
  const context=await browser.newContext({viewport:{width:1366,height:768},deviceScaleFactor:1});
  await context.setOffline(true);
  const page=await context.newPage();
  const errors=[],network=[];page.on('pageerror',e=>errors.push(String(e)));page.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url());});
  await page.goto(pathToFileURL(path.resolve(__dirname,'../archive/第20题_首轮样章.html')).href);
  await page.waitForFunction(()=>window.MathLab&&document.querySelector('#ellipseSvg circle'));
  const screenshot=async name=>page.screenshot({path:path.join(output,name+'.png'),fullPage:true});
  const input=async(id,value)=>page.locator('#'+id).evaluate((el,v)=>{el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}));},String(value));
  const state=()=>page.evaluate(()=>window.MathLab.getState());
  const geom=()=>page.evaluate(()=>window.MathLab.getGeometry());
  const noOverflow=async()=>assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1&&document.documentElement.scrollHeight<=innerHeight+1),'Viewport overflow');
  await noOverflow();await screenshot('01-free-1366');
  await input('position',.56);assert.ok(Math.abs((await geom()).rho-.56)<1e-6);
  // Real direct manipulation rather than only slider updates.
  const handle=await page.locator('[data-drag="move"]').boundingBox();
  await page.mouse.move(handle.x+handle.width/2,handle.y+handle.height/2);await page.mouse.down();await page.mouse.move(handle.x+handle.width/2,handle.y-30,{steps:5});await page.mouse.up();
  assert.ok(Math.abs((await geom()).rho-.56)>.05);
  const rotation=await page.locator('[data-drag="rotate"]').boundingBox();
  const angleBefore=(await state()).theta;
  await page.mouse.move(rotation.x+rotation.width/2,rotation.y+rotation.height/2);await page.mouse.down();await page.mouse.move(rotation.x+rotation.width/2+25,rotation.y+rotation.height/2-25,{steps:6});await page.mouse.up();
  assert.ok(Math.abs((await state()).theta-angleBefore)>1);
  await page.locator('[data-action="capture"]').click();assert.equal((await state()).samples.length,1);
  await page.locator('[data-stage="1"]').click();await page.locator('#lockBtn').click();assert.equal((await geom()).satisfies,true);
  assert.equal(await page.locator('#position').isDisabled(),true);
  await input('angle',64);assert.ok(Math.abs((await geom()).area-Math.sqrt(5))<1e-9);
  await page.locator('[data-action="locus"]').click();assert.equal((await state()).locus,true);
  await page.locator('[data-action="sweep"]').click();await page.waitForTimeout(120);assert.ok((await state()).theta>64);await page.locator('[data-action="sweep"]').click();assert.equal((await state()).sweep,false);
  await page.locator('[data-action="capture"]').click();await screenshot('02-locked-1366');
  await page.locator('summary').click();await page.locator('[data-special="horizontal"]').click();assert.equal((await geom()).valid,false);assert.match(await page.locator('#product1').innerText(),/未定义/);
  await page.locator('summary').click();await page.locator('[data-special="radius"]').click();assert.equal((await geom()).valid,false);
  await screenshot('02-special-1366');
  await page.locator('summary').click();await page.locator('[data-special="regular"]').click();assert.equal((await geom()).valid,true);
  await page.locator('[data-stage="2"]').click();
  await page.locator('[data-action="structure"]').click();await page.locator('[data-action="structure"]').click();
  await noOverflow();await screenshot('03-circle-1366');
  await input('morph',.53);const tr=await page.evaluate(()=>window.MathLab.inspect().transform);assert.ok(tr.factor>1&&tr.factor<2*Math.sqrt(5));
  await screenshot('03-morph-1366');
  await page.locator('#morphPlay').click();await page.waitForTimeout(200);await page.locator('#morphPlay').click();assert.equal((await state()).morphing,false);
  await input('morph',1);await page.locator('[data-action="structure"]').click();await screenshot('03-complete-1366');
  await page.locator('[data-stage="3"]').click();for(let i=0;i<4;i++)await page.locator('[data-action="proof-next"]').click();
  assert.match(await page.locator('#sideContent').innerText(),/参数消失/);await screenshot('04-analytic-1366');
  await page.locator('[data-path="transform"]').click();for(let i=0;i<3;i++)await page.locator('[data-action="proof-next"]').click();await screenshot('04-transform-1366');
  await page.locator('[data-stage="4"]').click();assert.equal(await page.locator('#angle').isDisabled(),true);
  await page.locator('[data-action="migration"]').click();assert.equal(await page.locator('#position').isDisabled(),false);await input('position',.2);const low=(await geom()).area;await input('position',.8);assert.ok((await geom()).area>low);await screenshot('05-migration-1366');
  await page.locator('#sourceBtn').click();assert.equal(await page.locator('#sourceModal').isVisible(),true);await screenshot('source');await page.keyboard.press('Escape');assert.equal(await page.locator('#sourceModal').isVisible(),false);
  await page.locator('#resetBtn').click();assert.equal((await state()).migration,false);
  // Keyboard on inputs must not navigate stages.
  await page.locator('[data-stage="0"]').click();await page.locator('#angle').focus();await page.keyboard.press('ArrowRight');assert.equal((await state()).stage,0);
  await page.locator('[data-stage="0"]').focus();await page.keyboard.press('ArrowRight');assert.equal((await state()).stage,1);
  await page.locator('#teacherBtn').click();await screenshot('teacher');await page.keyboard.press('Escape');
  await page.setViewportSize({width:1920,height:1080});await page.locator('[data-stage="2"]').click();await page.locator('[data-action="structure"]').click();await page.locator('[data-action="structure"]').click();await noOverflow();await screenshot('03-circle-1920');
  await page.setViewportSize({width:768,height:1024});await screenshot('tablet-768');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  assert.deepEqual(errors,[]);assert.deepEqual(network,[]);
  console.log('PASS: Chromium offline interaction, direct drag, constraints, exceptions, morph, both proofs, migration, modals, keyboard, 1366/1920/tablet layouts.');
  await browser.close();
})().catch(reportFailure);
