Problems[17]={
title:'两平面垂直与点面距离',
statement:`在四棱锥 ${M.inline('P-ABCD')} 中，${M.inline(String.raw`PA\perp\text{平面 }ABCD`)}，底面 ${M.inline('ABCD')} 是正方形。（1）求证：平面 ${M.inline('PBD')} 垂直于平面 ${M.inline('PAC')}；（2）设 ${M.inline('AB=2')}，四棱锥的体积为 ${M.inline(String.raw`\frac83`)}，求点 ${M.inline('A')} 到平面 ${M.inline('PBD')} 的距离。`,
model(h=2){const A=[0,0,0],B=[2,0,0],C=[2,2,0],D=[0,2,0],P=[0,0,h],E=[1,1,0],den=2+4/(h*h),H=[2/den,2/den,4/(h*den)];return{A,B,C,D,P,E,H,h,d:2/Math.sqrt(den),volume:4*h/3};},
mount(host){const C=Lab.C;let mode='planes',h=2,stage=null,key='';
host.innerHTML=`<div class="controls"><label>观察目标 <select id="yp24-17-mode"><option value="planes">（1）两平面垂直</option><option value="distance">（2）点到平面距离</option></select></label><label>高度 PA <input id="yp24-17-height" type="range" min=".6" max="3.2" step=".02" value="2"></label><button id="yp24-17-numeric">取第二问条件</button><button id="yp24-17-view">恢复视角</button></div><div class="figures"><svg id="yp24-17-svg" class="main-figure" role="img" aria-label="正方形底面的四棱锥，两垂直平面及从A到平面PBD的垂线"></svg></div><div class="readout" id="yp24-17-read"></div><div class="explain"><section class="proof-step"><h3>（1）找一条垂直于整个平面的直线</h3><p>正方形的两条对角线互相垂直，所以 ${M.inline(String.raw`BD\perp AC`)}。又因 ${M.inline(String.raw`PA\perp\text{平面 }ABCD`)}，有 ${M.inline(String.raw`BD\perp PA`)}。${M.inline('PA,AC')} 是平面 ${M.inline('PAC')} 内相交的两条直线，故</p>${M.block(String.raw`BD\perp\text{平面 }PAC.`)}<p>而 ${M.inline(String.raw`BD\subset\text{平面 }PBD`)}，所以</p>${M.block(String.raw`\text{平面 }PBD\perp\text{平面 }PAC.`)}</section><section class="proof-step"><h3>（2）先由体积确定真实高度</h3>${M.block(String.raw`\frac13\cdot2^2\cdot PA=\frac83\quad\Longrightarrow\quad PA=2.`)}<p>设 ${M.inline(String.raw`E=AC\cap BD`)}，则 ${M.inline(String.raw`AE=\sqrt2`)}。直角三角形 ${M.inline('PAE')} 中，${M.inline(String.raw`PE=\sqrt6`)}。</p></section><section class="proof-step"><h3>在平面 PAC 内作垂线，得到点面距离</h3><p>在平面 ${M.inline('PAC')} 内，过 ${M.inline('A')} 作 ${M.inline(String.raw`AH\perp PE`)}，垂足为 ${M.inline('H')}。由（1），${M.inline('BD')} 垂直于平面 ${M.inline('PAC')}，因而 ${M.inline(String.raw`AH\perp BD`)}。${M.inline('PE,BD')} 是平面 ${M.inline('PBD')} 内相交的两条直线，于是 ${M.inline(String.raw`AH\perp\text{平面 }PBD`)}。</p>${M.block(String.raw`AH=\frac{PA\cdot AE}{PE}=\frac{2\sqrt2}{\sqrt6}=\frac{2\sqrt3}{3}.`)}<p class="proof-note">第一问允许改变高度，但始终保持正方形底面与 PA 垂直于底面。切到第二问会固定 PA=2；相机旋转不改变任何几何条件。</p></section></div>`;
const svg=host.querySelector('#yp24-17-svg'),viewport=Space.create(svg,{center:[1,1,.9],get span(){return Math.max(3.3,1.3*h+.2);},view:{yaw:.22,pitch:.35,zoom:1}});
function render(){const m=Problems[17].model(h),k=stage===null?9:stage,newKey=[mode,h,stage].join('|');if(key!==newKey){key=newKey;const points=['A','B','C','D','P'].map(id=>({id,at:m[id],label:id,color:C.ink})),edges=[],faces=[{id:'base',vertices:[m.A,m.B,m.C,m.D],color:C.ink,opacity:.035},...[[m.P,m.A,m.B],[m.P,m.B,m.C],[m.P,m.C,m.D],[m.P,m.D,m.A]].map((vertices,i)=>({id:'side'+i,vertices,color:C.ink,opacity:.022}))];for(const [a,b]of[['A','B'],['B','C'],['C','D'],['D','A'],['P','A'],['P','B'],['P','C'],['P','D']])edges.push({id:a+b,a:m[a],b:m[b],color:a==='P'&&b==='A'?C.blue:C.ink,width:2});if(k>=1){faces.push({id:'PAC',vertices:[m.P,m.A,m.C],color:C.blue,opacity:.1,occluder:false},{id:'PBD',vertices:[m.P,m.B,m.D],color:C.gold,opacity:.12,occluder:false});edges.push({id:'AC',a:m.A,b:m.C,color:C.blue,width:2.2,occlude:false},{id:'BD',a:m.B,b:m.D,color:C.green,width:3,occlude:false});points.push({id:'E',at:m.E,label:'E',color:C.green,occlude:false});}if(k>=2){edges.push({id:'PE',a:m.P,b:m.E,color:C.gold,width:2.5,occlude:false});if(mode==='distance'){points.push({id:'H',at:m.H,label:'H',color:C.target,occlude:false});edges.push({id:'AH',a:m.A,b:m.H,color:C.target,width:3.3,occlude:false});}}viewport.setScene({points,edges,faces,annotations:[]});}else viewport.render();host.querySelector('#yp24-17-height').disabled=mode==='distance';host.querySelector('#yp24-17-read').innerHTML=mode==='planes'?`当前 ${M.inline('PA='+Lab.fmt(h,2))}。绿色 ${M.inline('BD')} 同时垂直于蓝色平面内的 ${M.inline('PA,AC')}；改变高度，垂直关系不变。${M.answer(M.inline(String.raw`\text{平面 }PBD\perp\text{平面 }PAC`))}`:`第二问固定 ${M.inline(String.raw`PA=2,\ V=\frac83`)}。红色 ${M.inline('AH')} 是所求垂距，${M.inline('H')} 位于 ${M.inline('PE')} 上。${M.answer(M.inline(String.raw`d=\frac{2\sqrt3}{3}\approx${Lab.fmt(m.d,4)}`))}`;}
function setMode(value){mode=value;if(mode==='distance'){h=2;host.querySelector('#yp24-17-height').value=2;}host.querySelector('#yp24-17-mode').value=mode;if(stage!==null)stage=0;render();host.dispatchEvent(new Event('constructionchange'));}
host.querySelector('#yp24-17-mode').onchange=e=>setMode(e.target.value);host.querySelector('#yp24-17-height').oninput=e=>{h=+e.target.value;render();};host.querySelector('#yp24-17-numeric').onclick=()=>setMode('distance');host.querySelector('#yp24-17-view').onclick=()=>viewport.resetView();render();
return{render,getState:()=>({mode,...Problems[17].model(h),space:viewport.getState()}),reset(){mode='planes';h=2;stage=null;host.querySelector('#yp24-17-mode').value=mode;host.querySelector('#yp24-17-height').value=h;viewport.resetView();render();},getConstructionSteps:()=>[{title:'保持题设，建立四棱锥',body:'正方形底面与竖直棱 PA 构成空间图。'},{title:'画两个平面与底面对角线',body:'BD 同时垂直于 PA、AC，成为平面 PAC 的法线方向。'},{title:mode==='distance'?'作点到平面的垂线':'画两平面的交线',body:mode==='distance'?'从 A 向交线 PE 作垂线 AH，它也垂直于 BD，因而垂直于平面 PBD。':'交线是 PE；两平面垂直由线面垂直严格保证。'}],getConstructionStep:()=>stage,setConstructionStep:n=>{stage=n===null?null:Math.max(0,Math.min(2,n));render();},destroy:()=>viewport.destroy()};}
};
