Problems[19]={
title:'雨棚形状、板材面积与遮挡高度',
statement:`挡雨棚抽象为柱体，底面 ${M.inline('ABC')} 与 ${M.inline('A_1B_1C_1')} 全等且平行，支架 ${M.inline(String.raw`AA_1,BB_1,CC_1\perp\text{平面 }ABC`)}。雨滴下落方向与外墙成 ${M.inline(String.raw`\frac\pi6`)} 角，即 ${M.inline(String.raw`\angle AOB=\frac\pi6`)}；有效遮挡区域为矩形 ${M.inline('AA_1O_1O')}，${M.inline('O,O_1')} 分别在 ${M.inline('CA,C_1A_1')} 的延长线上。（1）挡雨板面积视为曲线 ${M.inline('BC')} 长与 ${M.inline('BB_1')} 长的乘积。已知 ${M.inline('OA=1.5')} 米、${M.inline('AC=0.3')} 米、${M.inline('AA_1=2')} 米。分别求两种假设下的板面积，精确到 ${M.inline('0.1')} 平方米：① ${M.inline('BC')} 为直线段且 ${M.inline(String.raw`\angle ACB=\frac\pi3`)}；② ${M.inline('BC')} 为以 ${M.inline('O')} 为圆心的圆弧。（2）另制直角支架，${M.inline('AC=0.6')} 米、${M.inline(String.raw`\angle ABC=\frac\pi2`)}、${M.inline(String.raw`\angle CAB=\theta,\ \frac\pi6<\theta<\frac\pi2`)}，求有效遮挡区域高 ${M.inline('OA')} 的最大值。`,
model(mode='optimize',theta=60){if(mode==='optimize'){const t=theta*Math.PI/180,AB=.6*Math.cos(t),B=[AB*Math.sin(t),AB*Math.cos(t)],height=Math.sqrt(3)*B[0]-B[1];return{A:[0,0],C:[0,.6],B,O:[0,-height],height,theta,AB,BC:.6*Math.sin(t),length:0,area:0};}const radius=1.8,B=mode==='arc'?[.9,.9*Math.sqrt(3)]:[.45*Math.sqrt(3),1.35],length=mode==='arc'?.3*Math.PI:.9;return{A:[0,1.5],C:[0,1.8],B,O:[0,0],height:1.5,radius,length,area:2*length};},
mount(host){const C=Lab.C;let mode='straight',theta=60,stage=null;
host.innerHTML=`<div class="controls"><label>分问与形状 <select id="yp24-19-mode"><option value="straight">（1）① 直线挡雨板</option><option value="arc">（1）② 圆弧挡雨板</option><option value="optimize">（2）优化遮挡高度</option></select></label><label>角 θ（度）<input id="yp24-19-theta" type="range" min="30.1" max="89.9" step=".1" value="60"></label><button id="yp24-19-best">取最大遮挡高度</button></div><div class="figures"><svg id="yp24-19-geometry" class="figure" role="img" aria-label="挡雨棚侧截面、雨线与墙上有效遮挡高度"></svg><svg id="yp24-19-graph" class="figure" role="img" aria-label="挡雨板展开面积或遮挡高度函数"></svg></div><div class="readout" id="yp24-19-read"></div><div class="explain"><section class="proof-step"><h3>（1）① 先在侧截面求直板长度</h3><p>${M.inline('O,A,C')} 共线，且 ${M.inline('OC=OA+AC=1.8')} 米。在三角形 ${M.inline('OCB')} 中，${M.inline(String.raw`\angle COB=\frac\pi6`)}、${M.inline(String.raw`\angle OCB=\frac\pi3`)}，所以 ${M.inline(String.raw`\angle OBC=\frac\pi2`)}。</p>${M.block(String.raw`BC=OC\sin\frac\pi6=0.9\ \mathrm m.`)}<p>侧棱等长，${M.inline('BB_1=AA_1=2')} 米，故</p>${M.block(String.raw`S_1=BC\cdot BB_1=1.8\ \mathrm{m}^2.`)}</section><section class="proof-step"><h3>（1）② 用圆心角计算弧长，再展开</h3><p>圆弧的半径为 ${M.inline('OC=1.8')} 米，圆心角是 ${M.inline(String.raw`\angle COB=\frac\pi6`)}。</p>${M.block(String.raw`\begin{aligned}l_{BC}&=1.8\cdot\frac\pi6=0.3\pi,\\S_2&=2l_{BC}=0.6\pi\approx1.9\ \mathrm{m}^2.\end{aligned}`)}<p>两种形状具有相同的墙上遮挡高度，但弧板的板材面积更大。</p></section><section class="proof-step"><h3>（2）先用 θ 表示支架 AB</h3><p>这一问重新给定 ${M.inline('AC=0.6')} 米，且 ${M.inline(String.raw`\angle ABC=\frac\pi2`)}，所以</p>${M.block(String.raw`AB=0.6\cos\theta.`)}<p>三角形 ${M.inline('OAB')} 中，${M.inline(String.raw`\angle AOB=\frac\pi6`)}，${M.inline(String.raw`\angle OAB=\pi-\theta`)}，从而 ${M.inline(String.raw`\angle OBA=\theta-\frac\pi6`)}。</p></section><section class="proof-step"><h3>用雨线把支架长度转成遮挡高度</h3><p>由正弦定理，</p>${M.block(String.raw`\begin{aligned}OA&=\frac{AB\sin(\theta-\pi/6)}{\sin(\pi/6)}\\&=1.2\cos\theta\sin\left(\theta-\frac\pi6\right)\\&=0.6\sin\left(2\theta-\frac\pi6\right)-0.3.\end{aligned}`)}</section><section class="proof-step"><h3>在原角度范围内验证最大值能取到</h3><p>因为 ${M.inline(String.raw`\frac\pi6<\theta<\frac\pi2`)}，所以 ${M.inline(String.raw`\frac\pi6<2\theta-\frac\pi6<\frac{5\pi}6`)}。当且仅当 ${M.inline(String.raw`2\theta-\frac\pi6=\frac\pi2`)}，即 ${M.inline(String.raw`\theta=\frac\pi3`)} 时，正弦取最大值 ${M.inline('1')}。</p>${M.block(String.raw`OA_{\max}=0.6-0.3=0.3\ \mathrm m.`)}<p class="proof-note">角度端点不属于题设；接近 30° 或 90° 时遮挡高度趋于零。曲线上的空心点只表示极限，不是合法支架。图中所有长度单位为米。</p></section></div>`;
function path(p,pts,style){p.add(`<path d="${pts.map((pt,i)=>(i?'L':'M')+p.to(pt).join(',')).join(' ')}" fill="none" stroke="${style.stroke}" stroke-width="${style.width||2}" stroke-linejoin="round" stroke-linecap="round"/>`);}
function arcPoints(origin,r,a,b,n=36){return Array.from({length:n+1},(_,i)=>[origin[0]+r*Math.cos(a+(b-a)*i/n),origin[1]+r*Math.sin(a+(b-a)*i/n)]);}
function render(){const m=Problems[19].model(mode,theta),opt=mode==='optimize',k=stage===null?9:stage,p=Lab.plot(host.querySelector('#yp24-19-geometry'),opt?{xmin:-.2,xmax:.58,ymin:-.39,ymax:.75,pad:43}:{xmin:-.28,xmax:1.15,ymin:-.2,ymax:2.15,pad:43});host.querySelector('#yp24-19-theta').disabled=!opt;p.screenText(18,27,'侧截面 · 长度单位：米',{color:C.gray,size:17});p.line([0,opt?-.36:-.1],[0,opt?.68:1.94],{stroke:C.gray,width:3});p.line(m.A,m.C,{stroke:C.blue,width:3});p.dot(m.A,'A',C.ink,-19,14);p.dot(m.C,'C',C.ink,-18,-12);
if(k>=1){p.poly([m.A,m.B,m.C],{fill:C.blue,opacity:.045,stroke:'none'});p.line(m.A,m.B,{stroke:C.ink,width:2});if(mode==='arc')path(p,arcPoints(m.O,1.8,Math.PI/3,Math.PI/2),{stroke:C.target,width:3.4});else p.line(m.B,m.C,{stroke:opt?C.ink:C.target,width:3.4});p.dot(m.B,'B',C.ink,11,5);if(opt){const e1=m.A.map((x,i)=>(x-m.B[i])/m.A.map((v,j)=>v-m.B[j]).reduce((a,b)=>a+b*b,0)**.5),e2=m.C.map((x,i)=>(x-m.B[i])/m.C.map((v,j)=>v-m.B[j]).reduce((a,b)=>a+b*b,0)**.5),s=Math.min(.025,m.AB*.22,m.BC*.22),q1=m.B.map((x,i)=>x+s*e1[i]),q2=m.B.map((x,i)=>x+s*(e1[i]+e2[i])),q3=m.B.map((x,i)=>x+s*e2[i]);path(p,[q1,q2,q3],{stroke:C.green,width:1.5});path(p,arcPoints(m.A,.105,Math.PI/2-theta*Math.PI/180,Math.PI/2),{stroke:C.gold,width:1.4});p.math([.062,.115],String.raw`\theta`,{color:C.gold,size:22});}}
if(k>=2){p.line(m.B,m.O,{stroke:C.blue,width:2,dash:'5 5'});p.line(m.A,m.O,{stroke:opt?C.target:C.blue,width:4});p.dot(m.O,'O',C.ink,-18,18);const rainMid=m.B.map((x,i)=>(x+m.O[i])/2);p.text(rainMid,'雨线',{color:C.blue,dx:24,dy:15,size:17});p.math([0,(m.A[1]+m.O[1])/2],opt?'OA':'1.5',{color:opt?C.target:C.blue,dx:-30,anchor:'end',size:22});if(!opt)p.math([0,1.65],'0.3',{color:C.blue,dx:-25,anchor:'end',size:20});else p.math([0,.3],'0.6',{color:C.blue,dx:-26,anchor:'end',size:22});}p.finish();
const g=Lab.plot(host.querySelector('#yp24-19-graph'),opt?{xmin:27,xmax:93,ymin:-.035,ymax:.355,equal:false,pad:48}:{xmin:-.28,xmax:2.3,ymin:-.35,ymax:1.55,pad:44});if(opt){g.screenMath(17,26,String.raw`OA\ (\mathrm m)`,{color:C.target,size:21});g.axes({x:'θ（°）',y:'',stepX:15,stepY:.1,tickSize:14});if(k>=1)g.curve(x=>Problems[19].model('optimize',x).height,30,90,{stroke:C.target,width:2.7});if(k>=2){g.line([theta,0],[theta,m.height],{stroke:C.gray,dash:'4 5',width:1});g.dot([theta,m.height],'当前',C.target,10,-15);for(const x of[30,90]){const q=g.to([x,0]);g.add(`<circle cx="${q[0]}" cy="${q[1]}" r="5" fill="var(--canvas)" stroke="${C.target}" stroke-width="1.6"/>`);}g.dot([60,.3],'最大值 0.3',C.target,-5,-19);}}else{g.screenText(17,28,mode==='arc'?'圆弧板展开为矩形':'直线板展开为矩形',{size:18,color:C.gray});if(k>=1){g.poly([[0,0],[2,0],[2,m.length],[0,m.length]],{fill:C.target,opacity:.1,stroke:'none'});g.poly([[0,0],[2,0],[2,m.length],[0,m.length]],{fill:'none',stroke:C.target,width:2.5});g.math([1,0],'BB_1=2',{dy:30,anchor:'middle',size:22,color:C.ink});g.math([1,m.length/2],mode==='arc'?String.raw`S=0.6\pi`:String.raw`S=1.8`,{anchor:'middle',size:27,color:C.target});g.math([0,m.length/2],mode==='arc'?String.raw`0.3\pi`:'0.9',{dx:-16,anchor:'end',size:22,color:C.target});}}g.finish();
host.querySelector('#yp24-19-read').innerHTML=opt?`当前 ${M.inline(String.raw`\theta=${Lab.fmt(theta,1)}^\circ`)}，红色有效高度 ${M.inline(String.raw`OA\approx${Lab.fmt(m.height,4)}\ \mathrm m`)}。${M.answer(M.inline(String.raw`\theta=\frac\pi3\text{ 时，}OA_{\max}=0.3\ \mathrm m`))}`:`同为 ${M.inline('OA=1.5')} 米的遮挡高度，当前 ${mode==='arc'?'圆弧':'直线'}板长度 ${M.inline(String.raw`l\approx${Lab.fmt(m.length,4)}\ \mathrm m`)}。${M.answer(M.inline(String.raw`S_1=1.8\ \mathrm{m}^2,\quad S_2=0.6\pi\approx1.9\ \mathrm{m}^2`))}`;
}
function modeChange(value){mode=value;host.querySelector('#yp24-19-mode').value=mode;if(stage!==null)stage=0;render();host.dispatchEvent(new Event('constructionchange'));}host.querySelector('#yp24-19-mode').onchange=e=>modeChange(e.target.value);host.querySelector('#yp24-19-theta').oninput=e=>{theta=+e.target.value;render();};host.querySelector('#yp24-19-best').onclick=()=>{theta=60;host.querySelector('#yp24-19-theta').value=theta;modeChange('optimize');};render();
return{render,getState:()=>({mode,theta,...Problems[19].model(mode,theta)}),reset(){mode='straight';theta=60;stage=null;host.querySelector('#yp24-19-mode').value=mode;host.querySelector('#yp24-19-theta').value=theta;render();},getConstructionSteps:()=>[{title:'固定外墙与支架 AC',body:'两分问的 AC 不同；每次切换均采用当前题设数值。'},{title:mode==='optimize'?'按角度建立直角支架':'建立挡雨板并展开',body:mode==='optimize'?'改变 θ 时始终保持 AC=0.6 和 ∠ABC=90°。':'板的展开宽度等于 BC 的线段长或弧长。'},{title:'加入雨线与墙上有效高度',body:'雨线与外墙成 30°；沿雨线回到外墙确定 O，而不是独立拖动遮挡高度。'}],getConstructionStep:()=>stage,setConstructionStep:n=>{stage=n===null?null:Math.max(0,Math.min(2,n));render();}};}
};
