Problems[16]={title:'四面体中的三个等价条件',
 statement:`四面体 ${M.inline('ABCD')} 满足 ${M.inline('AB=BC,AD=CD')}。条件① ${M.inline(String.raw`AD\perp BC`)}；② ${M.inline('AC=BD')}；③ ${M.inline('AB^2+CD^2=AC^2+BD^2')} 中，有几个是 ${M.inline(String.raw`AB\perp CD`)} 的充要条件？A. 0　B. 1　C. 2　D. 3。`,
 mount(host){let theta=60,b=2,d=2;const C=Lab.C,$=s=>host.querySelector('#jd24-16-'+s);
 host.innerHTML=`<div class="controls"><label>夹角参数 <input id="jd24-16-theta" aria-label="夹角参数" type="range" min="15" max="165" step="1" value="60"></label><button id="jd24-16-right">使 AB ⟂ CD</button><button id="jd24-16-counter">AC = BD 的反例</button><button id="jd24-16-view">恢复视角</button><span class="hint">拖动旋转</span></div><div class="figures"><svg id="jd24-16-svg" class="main-figure" role="img" aria-label="保持两组边长相等的四面体，检验垂直与等长条件"></svg></div><div class="readout" id="jd24-16-readout"></div><div class="explain"><section class="proof-step"><h3>① 将两个等腰条件放进同一个坐标系</h3><p>设 ${M.inline('A=(-a,0,0),C=(a,0,0)')}。由 ${M.inline('AB=BC,AD=CD')}，${M.inline('B,D')} 都在 ${M.inline('AC')} 的垂直平分面上，可设</p>${M.block(String.raw`B=(0,b,0),\quad D=(0,u,v).`)}${M.block(String.raw`a,b>0,\quad v\ne0.`)}<p>这种表示覆盖任意非退化题设；图中只固定部分长度来作对照。</p></section><section class="proof-step"><h3>② 两个垂直条件恰好是同一等式</h3>${M.block(String.raw`\overrightarrow{AB}\cdot\overrightarrow{CD}=-a^2+bu,`)}${M.block(String.raw`\overrightarrow{AD}\cdot\overrightarrow{BC}=a^2-bu.`)}<p>两个内积互为相反数，故①与所求垂直条件充要。</p></section><section class="proof-step"><h3>③ 距离平方关系也化成同一等式</h3>${M.block(String.raw`AB^2+CD^2=2a^2+b^2+u^2+v^2,`)}${M.block(String.raw`AC^2+BD^2=4a^2+b^2+u^2+v^2-2bu.`)}<p>③等价于 ${M.inline('bu=a^2')}，因此也充要。</p></section><section class="proof-step"><h3>④ 等长条件不能决定方向</h3><p>取 ${M.inline('a=1,b=2,u=1,v=')} ${M.inline(String.raw`\sqrt3`)}，即图中的“反例”构型，则</p>${M.block(String.raw`AC=BD=2,\qquad \overrightarrow{AB}\cdot\overrightarrow{CD}=1\ne0.`)}<p>所以②不是充分条件。只有①、③符合。</p>${M.answer('C：共有 2 个。')}</section></div>`;
 const viewport=Space.create($('svg'),{center:[0,.7,.7],span:4.1,view:{yaw:.55,pitch:.4}});
 function model(){const a=theta*Math.PI/180,A=[-1,0,0],B=[0,b,0],Cc=[1,0,0],D=[0,d*Math.cos(a),d*Math.sin(a)],dot=-1+b*d*Math.cos(a);return{theta,A,B,C:Cc,D,dot,oppositeDot:-dot,ac:2,bd:Math.hypot(b-D[1],D[2]),squareDifference:2*dot};}
 function render(){const s=model(),edges=[],faces=[];for(const [a,z] of [['A','B'],['B','C'],['C','D'],['D','A'],['A','C'],['B','D']])edges.push({id:a+z,a:s[a],b:s[z],color:['AB','CD'].includes(a+z)?C.target:['AC','BD'].includes(a+z)?C.gold:C.blue,width:2.4});for(const ids of [['A','B','C'],['A','B','D'],['A','C','D'],['B','C','D']])faces.push({id:ids.join(''),vertices:ids.map(id=>s[id]),color:C.ink,opacity:.035});viewport.setScene({edges,faces,points:['A','B','C','D'].map(id=>({id,at:s[id],label:id,color:C.ink})),annotations:[]});$('theta').value=theta;$('readout').innerHTML=`红色边方向内积 ${M.inline(s.dot.toFixed(4))}；另一组内积 ${M.inline(s.oppositeDot.toFixed(4))}。${M.inline(String.raw`AC=2,\ BD\approx${s.bd.toFixed(4)}`)}。${M.answer('①、③与红色两边垂直等价；答案 C。')}`;}
 $('theta').oninput=e=>{theta=+e.target.value;render();};$('right').onclick=()=>{theta=Math.acos(1/4)*180/Math.PI;render();};$('counter').onclick=()=>{theta=60;render();};$('view').onclick=()=>viewport.resetView();render();return{render,reset(){theta=60;viewport.resetView();render();},getState:()=>({...model(),space:viewport.getState()}),destroy:()=>viewport.destroy()};
 }};
