(() => {
 const model=s=>{const t=2*Math.sqrt(s),P=[s,t],Q=[s+4+4/s,-2*Math.sqrt(s)-4/Math.sqrt(s)];return{s,t,P,Q,length:4*(s+1)**1.5/s,area:Math.abs(P[0]*Q[1]-P[1]*Q[0])/2,slope:1/Math.sqrt(s),normalSlope:-Math.sqrt(s)};};
 Problems[20]={title:'抛物线法线弦的最短长度',model,
 statement:`抛物线 ${M.inline('y^2=4x')} 上动点 ${M.inline('P(s,t),t>0')}。过 ${M.inline('P')} 作切线 ${M.inline('l')}，再作 ${M.inline(String.raw`m\perp l`)}，${M.inline('m')} 与抛物线另一交点为 ${M.inline('Q')}。<br>（1）${M.inline('s=1')} 时求 ${M.inline('l')}。<br>（2）${M.inline('l')} 与准线的交点在 ${M.inline('x')} 轴上，求 ${M.inline(String.raw`S_{\triangle OPQ}`)}。<br>（3）求 ${M.inline('|PQ|')} 关于 ${M.inline('s')} 的表达式及最小值。`,
 mount(host){let s=1,part='1';const C=Lab.C,$=x=>host.querySelector('#jd24-20-'+x);
 host.innerHTML=`<div class="controls"><label>小问 <select id="jd24-20-part"><option value="1">（1）切线</option><option value="2">（2）准线交点与面积</option><option value="3">（3）法线弦最短</option></select></label><label>横坐标 s <input id="jd24-20-s" aria-label="点 P 横坐标 s" type="range" min="0.35" max="5" step="0.01" value="1"></label><button id="jd24-20-one">s = 1</button><button id="jd24-20-best">最短弦 s = 2</button></div><div class="figures"><svg id="jd24-20-svg" class="main-figure" role="img" aria-label="抛物线上的切线、法线弦与准线"></svg></div><div class="readout" id="jd24-20-readout"></div><div class="explain"><section class="proof-step"><h3>① 切点的纵坐标为正，切线斜率唯一</h3><p>由 ${M.inline('t>0')} 得 ${M.inline(String.raw`s>0,t=2\sqrt{s}`)}。对 ${M.inline('y^2=4x')} 求导得 ${M.inline(String.raw`y\,y'=2`)}，所以切线为</p>${M.block(String.raw`l:\quad y-2\sqrt s=\frac{x-s}{\sqrt s}.`)}<div class="target">${M.block(String.raw`s=1\Rightarrow l:y=x+1.`)}</div></section><section class="proof-step"><h3>② 准线交点在横轴，迫使 s = 1</h3><p>准线是 ${M.inline('x=-1')}。切线通过 ${M.inline('(-1,0)')}，代入得 ${M.inline('s=1')}。法线为 ${M.inline('y=-x+3')}，与抛物线联立：</p>${M.block(String.raw`y^2+4y-12=0\Rightarrow y=2\ \text{或}\ -6.`)}<p>因此 ${M.inline('P=(1,2),Q=(9,-6)')}。</p><div class="target">${M.block(String.raw`S_{\triangle OPQ}=\tfrac12|1\cdot(-6)-2\cdot9|=12.`)}</div></section><section class="proof-step"><h3>③ 由法线的第二交点得到长度公式</h3>${M.block(String.raw`m:y=-\sqrt s\,x+\sqrt s(s+2).`)}<p>用 ${M.inline('x=y^2/4')} 代入，得到纵坐标两根之和为 ${M.inline(String.raw`-4/\sqrt s`)}，从而</p>${M.block(String.raw`Q=\left(s+4+\frac4s,-2\sqrt s-\frac4{\sqrt s}\right).`)}${M.block(String.raw`|PQ|=\sqrt{(4+4/s)^2+(4\sqrt s+4/\sqrt s)^2}`)}<div class="target">${M.block(String.raw`=\frac{4(s+1)^{3/2}}s,\quad s>0.`)}</div></section><section class="proof-step"><h3>④ 对全部正参数证明最小值</h3><p>令 ${M.inline('L(s)=4(s+1)^{3/2}/s')}。因 ${M.inline('L(s)>0')}，可用对数求导判断符号：</p>${M.block(String.raw`\frac{L'(s)}{L(s)}=\frac3{2(s+1)}-\frac1s=\frac{s-2}{2s(s+1)}.`)}<p>在 ${M.inline('(0,2)')} 上递减，在 ${M.inline(String.raw`(2,+\infty)`)} 上递增。</p><div class="target">${M.block(String.raw`L_{\min}=L(2)=6\sqrt3.`)}</div><p class="proof-note">滑杆仅展示 ${M.inline(String.raw`0.35\le s\le5`)}；证明处理整个 ${M.inline('s>0')}，没有把有限窗口当作定义域。</p></section></div>`;
 function render(){const g=model(s),ymax=7,ymin=Math.min(-8.5,g.Q[1]-1),xmax=Math.max(12,g.Q[0]+1),p=Lab.plot($('svg'),{xmin:-2,xmax,ymin,ymax,pad:45});p.axes({stepX:2,stepY:2});p.curve(x=>2*Math.sqrt(x),0,xmax,{stroke:C.blue,width:2.2});p.curve(x=>-2*Math.sqrt(x),0,xmax,{stroke:C.blue,width:2.2});p.line([-1,ymin],[-1,ymax],{stroke:C.gold,dash:'5 4',width:1.4});p.text([-1,ymax-1],'准线',{color:C.gold,dx:12,size:16});p.line([-2,(-2+s)/Math.sqrt(s)],[Math.min(xmax,7*Math.sqrt(s)-s),Math.min(7,(xmax+s)/Math.sqrt(s))],{stroke:C.green,width:2});p.line(g.P,g.Q,{stroke:C.target,width:3});if(part==='2')p.poly([[0,0],g.P,g.Q],{fill:C.target,opacity:.1,stroke:'none'});p.dot([0,0],'O',C.ink);p.dot(g.P,'P',C.target);p.dot(g.Q,'Q',C.target);p.dot([-1,(s-1)/Math.sqrt(s)],'准线交点',C.gold,-15,-18);p.screenMath(20,28,String.raw`|PQ|\approx${g.length.toFixed(3)}`,{color:C.target,size:18});p.finish();$('s').value=s;$('part').value=part;$('readout').innerHTML=`${M.inline(String.raw`s=${s.toFixed(3)},\quad |PQ|\approx${g.length.toFixed(4)}`)}。${part!=='3'&&Math.abs(s-1)>1e-9?'当前为条件外对照：点击 s = 1 回到本小问题设。':''}${M.answer(part==='1'?M.inline('y=x+1'):part==='2'?M.inline(String.raw`S_{\triangle OPQ}=12`):M.inline(String.raw`|PQ|_{\min}=6\sqrt3\quad(s=2)`))}`;}
 $('part').onchange=e=>{part=e.target.value;s=part==='3'?2:1;render();};$('s').oninput=e=>{s=+e.target.value;render();};$('one').onclick=()=>{s=1;render();};$('best').onclick=()=>{s=2;part='3';render();};render();return{render,reset(){s=1;part='1';render();},getState:()=>({...model(s),part})};
 }};
})();
