(() => {
 const f=x=>x*Math.exp(-x),g=x=>Math.log(x)/x;
 function bisect(fn,lo,hi){for(let i=0;i<70;i++){const mid=(lo+hi)/2;if(fn(lo)*fn(mid)<=0)hi=mid;else lo=mid;}return(lo+hi)/2;}
 const c=bisect(x=>f(x)-g(x),1,Math.E),special=f(c);
 function model(a){const u=bisect(x=>f(x)-a,0,1);let hi=2;while(f(hi)>a)hi*=2;const v=bisect(x=>f(x)-a,1,hi),four=[u,v,Math.exp(u),Math.exp(v)].sort((x,y)=>x-y),roots=four.filter((x,i)=>!i||Math.abs(x-four[i-1])>1e-7);return{a,u,v,c,special,roots,geometricError:Math.abs(roots.length===3?roots[1]**2-roots[0]*roots[2]:NaN)};}
 Problems[21]={title:'两条曲线、一个公共点和等比三交点',model,
 statement:`已知 ${M.inline(String.raw`f(x)=x/e^x,\quad g(x)=\ln x/x`)}。<br>（1）求两函数的单调区间和极值。<br>（2）严格证明两曲线有唯一交点。<br>（3）常数 ${M.inline(String.raw`a\in(0,1/e)`)}，直线 ${M.inline('y=a')} 与两曲线共有三个不同交点 ${M.inline('(x_1,a),(x_2,a),(x_3,a)')}，其中 ${M.inline('x_1<x_2<x_3')}，证明 ${M.inline('x_1,x_2,x_3')} 成等比数列。`,
 mount(host){let a=.28,part='1';const C=Lab.C,$=s=>host.querySelector('#jd24-21-'+s);
 host.innerHTML=`<div class="controls"><label>小问 <select id="jd24-21-part"><option value="1">（1）单调性与极值</option><option value="2">（2）唯一公共点</option><option value="3">（3）水平线的三交点</option></select></label><label>水平线 a <input id="jd24-21-a" aria-label="水平线高度 a" type="range" min="0.1" max="0.36" step="0.001" value="0.28"></label><button id="jd24-21-special">恰好三个不同交点</button></div><div class="figures"><svg id="jd24-21-svg" class="main-figure" role="img" aria-label="指数函数与对数函数的图像和水平线交点"></svg></div><div class="readout" id="jd24-21-readout"></div><div class="explain"><section class="proof-step"><h3>① 导数分别确定峰值</h3>${M.block(String.raw`f'(x)=e^{-x}(1-x).`)}<p>${M.inline('f')} 在 ${M.inline(String.raw`(-\infty,1)`)} 严格递增，在 ${M.inline(String.raw`(1,+\infty)`)} 严格递减；极大值 ${M.inline('f(1)=1/e')}，无极小值。</p>${M.block(String.raw`g'(x)=\frac{1-\ln x}{x^2},\quad x>0.`)}<p>${M.inline('g')} 在 ${M.inline('(0,e)')} 严格递增，在 ${M.inline(String.raw`(e,+\infty)`)} 严格递减；极大值 ${M.inline('g(e)=1/e')}，无极小值。</p></section><section class="proof-step"><h3>② 在一个区间内证明有且只有一个公共点</h3><p>公共定义域为 ${M.inline(String.raw`(0,+\infty)`)}。当 ${M.inline(String.raw`0<x\le1`)}，${M.inline(String.raw`f(x)>0\ge g(x)`)}，无交点。在 ${M.inline('(1,e)')} 上，${M.inline('f')} 严格递减、${M.inline('g')} 严格递增，且两端的大小关系相反，故由连续性恰有一个交点，横坐标记作 ${M.inline('c')}。</p><p>还需排除 ${M.inline(String.raw`x\ge e`)}：此时 ${M.inline(String.raw`g(x)\ge1/x`)}。函数 ${M.inline(String.raw`x-2\ln x`)} 在 2 处最小，且 ${M.inline(String.raw`2-2\ln2>0`)}，所以 ${M.inline('e^x>x^2')}，从而 ${M.inline(String.raw`f(x)<1/x\le g(x)`)}。唯一性在整个定义域成立。</p></section><section class="proof-step"><h3>③ 同一高度的根，由指数变换相互对应</h3><p>对 ${M.inline('0<a<1/e')}，${M.inline('f(x)=a')} 恰有两根 ${M.inline('0<u<1<v')}。注意恒等式</p>${M.block(String.raw`g(e^x)=\frac{x}{e^x}=f(x).`)}<p>所以 ${M.inline('g(x)=a')} 的两根恰为 ${M.inline('e^u,e^v')}。因为 ${M.inline('e^u>1>u')} 且 ${M.inline('e^v>v')}，这四个候选横坐标只能通过 ${M.inline('v=e^u')} 发生重合。</p></section><section class="proof-step"><h3>④ 三个不同交点，迫使中项平方等于两端之积</h3><p>题设“恰有三个不同交点”给出 ${M.inline('v=e^u')}。故</p>${M.block(String.raw`x_1=u,\quad x_2=v=e^u,\quad x_3=e^v.`)}<p>又 ${M.inline('f(u)=f(v)')}，所以</p>${M.block(String.raw`\frac{u}{e^u}=\frac{v}{e^v}\Rightarrow u e^v=v e^u=v^2.`)}<div class="target">${M.block(String.raw`x_1x_3=x_2^2.`)}</div><p>三数均正，因此成等比数列。动态数值只说明在哪个高度重合，上面的恒等式给出精确证明。</p></section></div>`;
 function render(){const s=model(a),xmax=Math.min(45,Math.max(7,s.roots.at(-1)*1.12)),p=Lab.plot($('svg'),{xmin:-.4,xmax,ymin:-.12,ymax:.44,equal:false,pad:49});p.axes({stepX:xmax>15?5:1,stepY:.1});p.curve(f,-.3,xmax,{stroke:C.blue,width:2.5});p.curve(g,.5,xmax,{stroke:C.green,width:2.5});if(part==='1'){p.dot([1,1/Math.E],'f 极大值',C.blue,-20,-20);p.dot([Math.E,1/Math.E],'g 极大值',C.green,15,30);}if(part==='2')p.dot([c,special],'唯一公共点',C.target,8,-20);if(part==='3'){p.line([0,a],[xmax,a],{stroke:C.target,width:2,dash:'5 4'});s.roots.forEach((x,i)=>{p.dot([x,a],'x'+(i+1),C.target,8,i%2?28:-15);p.line([x,0],[x,a],{stroke:C.gray,width:1,dash:'3 5'});});}p.screenMath(20,27,'f(x)=xe^{-x}',{color:C.blue,size:18});p.screenMath(230,27,String.raw`g(x)=\frac{\ln x}{x}`,{color:C.green,size:18});p.finish();$('part').value=part;$('a').value=a;$('readout').innerHTML=`${part==='3'?`当前 ${M.inline(String.raw`a\approx${a.toFixed(5)}`)}，共有 ${s.roots.length} 个不同交点；横坐标约 ${s.roots.map(x=>M.inline(x.toFixed(4))).join('，')}。`:`公共点横坐标 ${M.inline(String.raw`c\approx${c.toFixed(5)}`)}。`}${M.answer(part==='1'?`两函数的极大值均为 ${M.inline('1/e')}，峰值横坐标分别是 ${M.inline('1,e')}。`:part==='2'?`唯一交点满足 ${M.inline('1<c<e')}。`:M.inline('x_1x_3=x_2^2'))}<small>图中仅显示有限正横轴窗口；完整定义域、单调区间与唯一性见推导。</small>`;}
 $('part').onchange=e=>{part=e.target.value;render();};$('a').oninput=e=>{a=+e.target.value;part='3';render();};$('special').onclick=()=>{a=special;part='3';render();};render();return{render,reset(){a=.28;part='1';render();},getState:()=>({...model(a),part})};
 }};
})();
