Problems[11] = {
  title: '圆柱中的异面直线夹角',
  statement: `点 ${M.inline('P')} 在圆柱 ${M.inline('O_1O')} 的底面圆周上，${M.inline('AB')} 为底面圆的直径，${M.inline(String.raw`\angle AOP=120^\circ`)}，${M.inline('OA=3')}，${M.inline('A_1B')} 与底面所成角为 ${M.inline(String.raw`30^\circ`)}。求异面直线 ${M.inline('A_1B')} 与 ${M.inline('AP')} 所成角的<span class="target">余弦值</span>。`,
  mount(host) {
    const initial={yaw:-.65,pitch:.42};let state={...initial},constructionStep=null,sceneKey='';
    const steps=[
      {title:'底面直径与圆周点',body:`画半径为 ${M.inline('3')} 的底面圆，取直径 ${M.inline('AB')}，再按 ${M.inline(String.raw`\angle AOP=120^\circ`)} 确定 ${M.inline('P')}。`},
      {title:'用线面角确定圆柱高',body:`${M.inline('A_1B')} 的底面投影为 ${M.inline('AB')}，所以 ${M.inline(String.raw`\angle A_1BA=30^\circ`)}，${M.inline(String.raw`AA_1=AB\tan30^\circ=2\sqrt3`)}。画出圆柱和蓝色 ${M.inline('A_1B')}。`},
      {title:'把 AP 平移到 B 点',body:`取 ${M.inline('P')} 的对径点 ${M.inline('Q')}。${M.inline('AB')} 与 ${M.inline('PQ')} 互相平分，故 ${M.inline('APBQ')} 为平行四边形，${M.inline(String.raw`BQ\parallel AP`)}。`},
      {title:'将异面角化为同一顶点的角',body:`现在 ${M.inline('BA_1')} 与 ${M.inline('BQ')} 相交于 ${M.inline('B')}。标出的锐角 ${M.inline(String.raw`\varphi=\angle A_1BQ`)} 就是所求异面直线夹角。`},
    ];
    host.innerHTML=`<div class="controls"><button id="b11-translate" aria-pressed="false">显示平移辅助线</button><button id="b11-view">恢复视角</button><button id="b11-top">俯视底面</button><span class="hint">拖动旋转 · 滚轮缩放；题设尺寸固定</span></div><div class="figures"><svg id="b11-svg" class="main-figure" role="img" aria-label="圆柱中异面直线夹角，通过对径点将直线平移到同一顶点"></svg></div><div class="readout" id="b11-readout"></div><div class="explain"><section class="proof-step"><h3>线面角先确定高</h3><p>圆柱母线 ${M.inline('AA_1')} 垂直于底面，因此 ${M.inline('AB')} 是 ${M.inline('A_1B')} 的正射影。</p>${M.block(String.raw`AB=6,\qquad AA_1=6\tan30^\circ=2\sqrt3`)}${M.block(String.raw`A_1B=\frac6{\cos30^\circ}=4\sqrt3`)}</section><section class="proof-step"><h3>取对径点，把异面角平移出来</h3><p>取 ${M.inline('P')} 的对径点 ${M.inline('Q')}，则四边形 ${M.inline('APBQ')} 的两条对角线互相平分，故 ${M.inline(String.raw`BQ\parallel AP`)}。所求锐角是 ${M.inline(String.raw`\varphi=\angle A_1BQ`)}。</p><p>${M.inline(String.raw`\angle AOQ=60^\circ`)}，利用弦长公式：</p>${M.block(String.raw`AQ=2\cdot3\sin30^\circ=3`)}${M.block(String.raw`BQ=AP=2\cdot3\sin60^\circ=3\sqrt3`)}</section><section class="proof-step"><h3>余弦定理给出精确值</h3><p>${M.inline(String.raw`AA_1\perp AQ`)}，所以</p>${M.block(String.raw`A_1Q^2=AA_1^2+AQ^2=12+9=21`)}<p>在 ${M.inline(String.raw`\triangle A_1BQ`)} 中：</p><div class="target">${M.block(String.raw`\begin{aligned}\cos\varphi&=\frac{A_1B^2+BQ^2-A_1Q^2}{2A_1B\cdot BQ}\\&=\frac{48+27-21}{2\cdot4\sqrt3\cdot3\sqrt3}=\frac34.\end{aligned}`)}</div><p>余弦为正，确为两直线所成的锐角。</p></section></div>`;
    let translated=false;
    const C=Lab.C,h=2*Math.sqrt(3),O=[0,0,0],A=[-3,0,0],B=[3,0,0],P=[1.5,-3*Math.sqrt(3)/2,0],Q=P.map(x=>-x),A1=[-3,0,h],B1=[3,0,h],O1=[0,0,h];
    const mid=(a,b)=>a.map((v,i)=>(v+b[i])/2),sub=(a,b)=>a.map((v,i)=>v-b[i]);
    const viewport=Space.create(host.querySelector('#b11-svg'),{center:[0,0,h/2],span:7.6,view:initial,onViewChange:v=>Object.assign(state,{yaw:v.yaw,pitch:v.pitch})});
    function scene(){
      const points=[],edges=[],faces=[],annotations=[],stage=constructionStep===null?3:constructionStep,aux=constructionStep!==null?stage>=2:translated||document.body.classList.contains('show-key');
      const edge=(id,a,b,color=C.ink,width=2,more={})=>edges.push({id,a,b,color,width,...more});
      const point=(id,at,label=id,color=C.ink)=>points.push({id,at,label,color,priority:90});
      const rings=[0,h].map(z=>Array.from({length:48},(_,i)=>[3*Math.cos(i*Math.PI/24),3*Math.sin(i*Math.PI/24),z]));
      rings.forEach((ring,j)=>{if(j&&stage<1)return;for(let i=0;i<ring.length;i++)edge('ring-'+j+'-'+i,ring[i],ring[(i+1)%ring.length],C.gray,1.35);faces.push({id:'disc-'+j,vertices:ring,color:C.blue,opacity:.055});});
      if(stage>=1){for(let i=0;i<24;i++){let j=i*2,k=(j+2)%48;faces.push({id:'cylinder-'+i,vertices:[rings[0][j],rings[0][k],rings[1][k],rings[1][j]],color:C.ink,opacity:.018});}edge('AA1',A,A1);edge('BB1',B,B1);edge('A1B',A1,B,C.blue,3.5);point('A1',A1,'A₁');point('B1',B1,'B₁');point('O1',O1,'O₁');edge('A1B1',A1,B1,C.gray,1.2,{dash:'4 4'});annotations.push({id:'height',at:mid(A,A1),tex:String.raw`2\sqrt3`,color:C.gold,size:20,priority:80});}
      edge('AB',A,B,C.gray,1.5,{dash:'4 4'});edge('OP',O,P,C.gray,1.4,{dash:'4 4'});edge('AP',A,P,C.target,3.6,{occlude:false});point('O',O);point('A',A);point('B',B);point('P',P,'P',C.target);
      const baseArc=Array.from({length:25},(_,i)=>{const angle=Math.PI+i*Math.PI/36;return [.65*Math.cos(angle),.65*Math.sin(angle),0];});for(let i=1;i<baseArc.length;i++)edge('given-center-angle-'+i,baseArc[i-1],baseArc[i],C.gold,1.5,{occlude:false});annotations.push({id:'given-120',at:[-.55,-.95,0],tex:String.raw`120^\circ`,color:C.gold,size:18,priority:80});
      if(stage>=1){const slopeArc=Array.from({length:17},(_,i)=>{const angle=i*Math.PI/96;return [B[0]-.9*Math.cos(angle),0,.9*Math.sin(angle)];});for(let i=1;i<slopeArc.length;i++)edge('given-slope-angle-'+i,slopeArc[i-1],slopeArc[i],C.gold,1.5,{occlude:false});annotations.push({id:'given-30',at:[1.65,0,.42],tex:String.raw`30^\circ`,color:C.gold,size:18,priority:82});}
      if(aux){point('Q',Q,'Q',C.green);edge('PQ',P,Q,C.gray,1.3,{dash:'4 4',occlude:false});edge('BQ',B,Q,C.green,3.4,{occlude:false});edge('AQ',A,Q,C.gold,2,{dash:'5 4',occlude:false});edge('A1Q',A1,Q,C.gray,1.6,{dash:'5 4',occlude:false});annotations.push({id:'parallel',at:mid(B,Q),tex:String.raw`BQ\parallel AP`,color:C.green,size:19,priority:70});}
      if(aux&&stage>=3){const u=sub(A1,B).map(v=>v/(4*Math.sqrt(3))),v=sub(Q,B).map(x=>x/(3*Math.sqrt(3))),phi=Math.acos(.75),w=v.map((x,i)=>(x-.75*u[i])/Math.sin(phi)),arc=Array.from({length:20},(_,i)=>B.map((x,k)=>x+.8*(u[k]*Math.cos(phi*i/19)+w[k]*Math.sin(phi*i/19))));for(let i=1;i<arc.length;i++)edge('angle-'+i,arc[i-1],arc[i],C.target,2.4,{occlude:false});annotations.push({id:'phi',at:arc[10],tex:String.raw`\varphi`,color:C.target,size:23,priority:99,dx:-20,dy:-24});}
      return {points,edges,faces,annotations};
    }
    function render(){const key=[translated,constructionStep,document.body.classList.contains('show-key')].join('|');host.querySelector('#b11-translate').setAttribute('aria-pressed',String(translated));host.querySelector('#b11-translate').textContent=translated?'收起平移辅助线':'显示平移辅助线';if(key!==sceneKey){sceneKey=key;viewport.setScene(scene());}else viewport.render();}
    host.querySelector('#b11-readout').innerHTML=`<span>${M.inline(String.raw`OA=3,\quad\angle AOP=120^\circ`)}</span><span style="color:${C.blue}">${M.inline(String.raw`\angle A_1BA=30^\circ`)}</span>${M.answer(M.inline(String.raw`\cos\varphi=\frac34`))}<small>点击“显示平移辅助线”，观察绿色 ${M.inline('BQ')} 如何把红色 ${M.inline('AP')} 的方向移到 ${M.inline('B')} 点。夹角约 ${M.inline(String.raw`41.41^\circ`)}，精确答案是 ${M.inline(String.raw`\frac34`)}。</small>`;
    host.querySelector('#b11-translate').onclick=()=>{translated=!translated;render();};host.querySelector('#b11-view').onclick=()=>viewport.resetView();host.querySelector('#b11-top').onclick=()=>viewport.setView({yaw:0,pitch:1.42,zoom:1});
    render();return {render,reset(){state={...initial};translated=false;if(constructionStep!==null)constructionStep=0;viewport.resetView();render();host.dispatchEvent(new Event('constructionchange'));},getState:()=>({...state,translated,A,B,P,Q,A1,height:h,cosine:.75,angle:Math.acos(.75),space:viewport.getState()}),getConstructionSteps:()=>steps,getConstructionStep:()=>constructionStep,setConstructionStep(i){constructionStep=i===null?null:Math.max(0,Math.min(steps.length-1,Math.trunc(Number(i)||0)));render();},destroy:()=>viewport.destroy()};
  }
};
