Problems[12] = {
  title: '向量约束变成平面与球面',
  statement: `空间向量 ${M.inline(String.raw`\vec a,\vec b,\vec c`)} 满足 ${M.inline(String.raw`|\vec a|=2|\vec b|=3|\vec c|=6`)}，两两夹角均为 ${M.inline(String.raw`60^\circ`)}。若 ${M.inline(String.raw`\vec c\cdot\vec e_1=12`)}，${M.inline(String.raw`(\vec e_2-\vec a)\cdot(\vec e_2-\vec b)=0`)}，求<span class="target">${M.inline(String.raw`|\vec e_1-\vec e_2|`)} 的最小值</span>。`,
  mount(host) {
    const initial={latitude:25,longitude:20,offset:0,yaw:-.55,pitch:.18};let state={...initial},constructionStep=null,geometryKey='',readoutKey='';
    const C=Lab.C,A=[3*Math.sqrt(3),0,3],B=[Math.sqrt(3)/2,Math.sqrt(6),1.5],K=A.map((x,i)=>(x+B[i])/2),r=3*Math.sqrt(3)/2,planeZ=6,minimum=15/4-r;
    const steps=[
      {title:'向量终点改记为空间点',body:`以 ${M.inline('O')} 为起点，把 ${M.inline(String.raw`\vec a,\vec b,\vec c`)} 的终点记为 ${M.inline('A,B,C')}，长度分别是 ${M.inline('6,3,2')}。点 ${M.inline('E_1,E_2')} 分别表示 ${M.inline(String.raw`\vec e_1,\vec e_2`)} 的终点。`},
      {title:'一个点积条件变成平面',body:`${M.inline(String.raw`\vec c\cdot\overrightarrow{OE_1}=12`)} 表示 ${M.inline('E_1')} 在法向量为 ${M.inline(String.raw`\vec c`)} 的平面 ${M.inline(String.raw`\Pi`)} 上；${M.inline(String.raw`|\vec c|=2`)}，所以该平面到 ${M.inline('O')} 的距离为 ${M.inline('6')}。`},
      {title:'另一个点积条件变成球面',body:`${M.inline(String.raw`\overrightarrow{AE_2}\cdot\overrightarrow{BE_2}=0`)} 等价于 ${M.inline('E_2')} 位于以 ${M.inline('AB')} 为直径的球面上（含 ${M.inline('A,B')}）。球心 ${M.inline('K')} 是 ${M.inline('AB')} 中点，半径为 ${M.inline(String.raw`r=\frac{3\sqrt3}{2}`)}。`},
      {title:'先让平面上的点取最近位置',body:`固定球面点 ${M.inline('E_2')}，它到平面的最近点是垂足 ${M.inline('H')}。当“平面内偏移”为 ${M.inline('0')} 时 ${M.inline('E_1=H')}；否则距离更长。`},
      {title:'再把球面点移向平面',body:`把球面点纬度移到 ${M.inline(String.raw`90^\circ`)}，并把平面内偏移设为 ${M.inline('0')}。这时球面点沿法线最靠近平面，最短距离为 ${M.inline(String.raw`d(K,\Pi)-r=\frac{15}{4}-\frac{3\sqrt3}{2}`)}。`},
    ];
    host.innerHTML=`<div class="controls"><label>球面点纬度 <input id="b12-latitude" type="range" min="-90" max="90" step="1" value="25"><output id="b12-latitude-value"></output></label><label>经度 <input id="b12-longitude" type="range" min="-180" max="180" step="1" value="20"></label><label>平面内偏移 <input id="b12-offset" type="range" min="-2" max="2" step="0.05" value="0"></label><button id="b12-nearest">移到最短构型</button><button id="b12-view">恢复视角</button><span class="hint">拖动旋转 · 滚轮缩放</span></div><div class="figures"><svg id="b12-svg" class="main-figure" role="img" aria-label="向量条件对应球面与平面，移动球面点观察最短距离"></svg></div><div class="readout" id="b12-readout"></div><div class="explain"><section class="proof-step"><h3>识别两个向量终点的轨迹</h3><p>令 ${M.inline(String.raw`\overrightarrow{OA}=\vec a,\ \overrightarrow{OB}=\vec b`)}。${M.inline(String.raw`\vec c\cdot\vec e_1=12`)} 表示点 ${M.inline('E_1')} 位于法向量为 ${M.inline(String.raw`\vec c`)} 的平面 ${M.inline(String.raw`\Pi`)}。另一条件展开为</p>${M.block(String.raw`\left|\vec e_2-\frac{\vec a+\vec b}{2}\right|^2=\frac{|\vec a-\vec b|^2}{4}`)}<p>故 ${M.inline('E_2')} 在以 ${M.inline('AB')} 为直径的球面上，球心 ${M.inline(String.raw`\overrightarrow{OK}=\frac{\vec a+\vec b}{2}`)}。当 ${M.inline('E_2=A')} 或 ${M.inline('B')} 时点积也为零，因此球面没有漏掉这两个点。</p></section><section class="proof-step"><h3>先求球半径</h3><p>由题设 ${M.inline(String.raw`|\vec a|=6,\ |\vec b|=3,\ |\vec c|=2`)}，且 ${M.inline(String.raw`\vec a\cdot\vec b=6\cdot3\cos60^\circ=9`)}。</p>${M.block(String.raw`AB^2=|\vec a-\vec b|^2=36+9-18=27`)}${M.block(String.raw`r=\frac{AB}{2}=\frac{3\sqrt3}{2}`)}</section><section class="proof-step"><h3>沿法向量求球心到平面的距离</h3>${M.block(String.raw`\vec c\cdot\vec a=6,\qquad\vec c\cdot\vec b=3`)}${M.block(String.raw`\vec c\cdot\overrightarrow{OK}=\frac{6+3}{2}=\frac92`)}${M.block(String.raw`d(K,\Pi)=\frac{|12-\frac92|}{|\vec c|}=\frac{15}{4}`)}<p>注意分母还要除以法向量长度 ${M.inline('2')}。这里 ${M.inline(String.raw`\frac{15}{4}>\frac{3\sqrt3}{2}`)}，球面与平面不相交。</p></section><section class="proof-step"><h3>下界与取等构型都要证明</h3><p>对任意球面点 ${M.inline('E_2')} 与平面点 ${M.inline('E_1')}，先用垂线段最短，再用沿法向的投影不超过半径：</p>${M.block(String.raw`E_1E_2\ge d(E_2,\Pi)\ge d(K,\Pi)-r`)}<p>取 ${M.inline(String.raw`\overrightarrow{KE_2}=r\frac{\vec c}{|\vec c|}`)}，并令 ${M.inline('E_1')} 为 ${M.inline('E_2')} 在平面上的垂足，两次不等式同时取等。</p><div class="target">${M.block(String.raw`\min |\vec e_1-\vec e_2|=\frac{15}{4}-\frac{3\sqrt3}{2}`)}</div><p>图中的纬度、经度遍历整个球面；平面内偏移只展示一个方向的对照，完整最小值由以上一般证明确定。</p></section></div>`;
    const viewport=Space.create(host.querySelector('#b12-svg'),{center:[K[0],K[1],3.2],span:8.5,view:initial,onViewChange:v=>Object.assign(state,{yaw:v.yaw,pitch:v.pitch})});
    const mid=(a,b)=>a.map((x,i)=>(x+b[i])/2);
    function model(){const lat=state.latitude*Math.PI/180,lon=state.longitude*Math.PI/180,E2=[K[0]+r*Math.cos(lat)*Math.cos(lon),K[1]+r*Math.cos(lat)*Math.sin(lon),K[2]+r*Math.sin(lat)],H=[E2[0],E2[1],planeZ],E1=[H[0]+state.offset,H[1],planeZ];return {A,B,K,r,E1,E2,H,minimum,centerDistance:15/4,distance:Math.hypot(state.offset,planeZ-E2[2]),planeDistance:planeZ-E2[2],dotCondition:E2.map((x,i)=>(x-A[i])*(x-B[i])).reduce((a,b)=>a+b,0)};}
    function scene(m){
      const points=[],edges=[],faces=[],annotations=[],stage=constructionStep===null?4:constructionStep,showOriginal=constructionStep!==null?stage===0:document.body.classList.contains('show-key');
      const edge=(id,a,b,color=C.ink,width=2,more={})=>edges.push({id,a,b,color,width,occlude:false,...more}),point=(id,at,label=id,color=C.ink)=>points.push({id,at,label,color,priority:id==='E1'||id==='E2'?100:75,occlude:false});
      point('A',A);point('B',B);edge('AB',A,B,C.green,2.2);
      if(showOriginal){const O=[0,0,0],Cv=[0,0,2];point('O',O);point('C',Cv,'C',C.gold);edge('OA',O,A,C.gray,1.5);edge('OB',O,B,C.gray,1.5);edge('OC',O,Cv,C.gold,2);annotations.push({id:'c',at:mid(O,Cv),tex:String.raw`\vec c`,color:C.gold,size:19,priority:65});}
      if(stage>=1){const corners=[[K[0]-3.45,K[1]-3.05,6],[K[0]+3.45,K[1]-3.05,6],[K[0]+3.45,K[1]+3.05,6],[K[0]-3.45,K[1]+3.05,6]];faces.push({id:'plane',vertices:corners,color:C.blue,opacity:.13,occluder:false});corners.forEach((a,i)=>edge('plane-'+i,a,corners[(i+1)%4],C.blue,1.1));annotations.push({id:'plane-label',at:corners[3].map((x,i)=>i===0?x+.45:i===1?x-.4:x),tex:String.raw`\Pi:\ \vec c\cdot\vec x=12`,color:C.blue,size:20,priority:88});}
      if(stage>=2){point('K',K,'K',C.green);const sp=(lat,lon)=>[K[0]+r*Math.cos(lat)*Math.cos(lon),K[1]+r*Math.cos(lat)*Math.sin(lon),K[2]+r*Math.sin(lat)];for(let j=0;j<8;j++)for(let i=0;i<16;i++){const la=-Math.PI/2+j*Math.PI/8,lb=la+Math.PI/8,lo=i*Math.PI/8,lp=lo+Math.PI/8;faces.push({id:'sphere-'+j+'-'+i,vertices:[sp(la,lo),sp(la,lp),sp(lb,lp),sp(lb,lo)],color:C.green,opacity:.055,occluder:false});}for(let j=1;j<6;j++){const lat=-Math.PI/2+j*Math.PI/6;for(let i=0;i<40;i++)edge('latitude-'+j+'-'+i,sp(lat,i*Math.PI/20),sp(lat,(i+1)*Math.PI/20),C.green,.65,{opacity:.45});}for(let j=0;j<4;j++)for(let i=0;i<48;i++){const a=i*Math.PI/24,b=(i+1)*Math.PI/24,lo=j*Math.PI/4;edge('meridian-'+j+'-'+i,sp(a,lo),sp(b,lo),C.green,.65,{opacity:.45});}}
      if(stage>=3){point('E2',m.E2,'E₂',C.target);point('E1',m.E1,Math.abs(state.offset)<1e-8?'E₁ = H':'E₁',C.target);edge('distance',m.E1,m.E2,C.target,3.7);edge('radius',K,m.E2,C.green,2,{dash:'5 4'});if(Math.abs(state.offset)>1e-8){point('H',m.H,'H',C.gold);edge('projection',m.E2,m.H,C.gold,2,{dash:'5 4'});edge('offset',m.H,m.E1,C.blue,2);}annotations.push({id:'distance-label',at:mid(m.E1,m.E2),tex:'d',color:C.target,size:24,priority:95});const kProjection=[K[0],K[1],planeZ];edge('center-normal',K,kProjection,C.gray,1.3,{dash:'5 4'});}
      return {points,edges,faces,annotations};
    }
    function render(){const m=model(),key=[state.latitude,state.longitude,state.offset].join('|'),skey=key+'|'+constructionStep+'|'+document.body.classList.contains('show-key');host.querySelector('#b12-latitude').value=state.latitude;host.querySelector('#b12-longitude').value=state.longitude;host.querySelector('#b12-offset').value=state.offset;host.querySelector('#b12-latitude-value').textContent=state.latitude+'°';if(skey!==geometryKey){geometryKey=skey;viewport.setScene(scene(m));}else viewport.render();if(readoutKey===key)return;readoutKey=key;host.querySelector('#b12-readout').innerHTML=`<span style="color:${C.green}">${M.inline(String.raw`r=\frac{3\sqrt3}{2}`)}</span><span>${M.inline(String.raw`d(K,\Pi)=\frac{15}{4}`)}</span><span class="target">当前 ${M.inline(String.raw`E_1E_2\approx${Lab.fmt(m.distance,3)}`)}</span>${M.answer(M.inline(String.raw`d_{\min}=\frac{15}{4}-\frac{3\sqrt3}{2}\approx${Lab.fmt(minimum,3)}`))}<small>${Math.abs(state.offset)<1e-8?'当前 E₁ 就是垂足 H；再把球面点移到最靠近平面的位置。':'当前 E₁ 偏离垂足 H，红线长于金色垂线段；将平面内偏移调为 0 可缩短。'}</small>`;}
    ['latitude','longitude','offset'].forEach(name=>host.querySelector('#b12-'+name).oninput=e=>{state[name]=+e.target.value;render();});host.querySelector('#b12-nearest').onclick=()=>{state.latitude=90;state.offset=0;render();};host.querySelector('#b12-view').onclick=()=>viewport.resetView();
    render();return {render,reset(){state={...initial};if(constructionStep!==null)constructionStep=0;viewport.resetView();render();host.dispatchEvent(new Event('constructionchange'));},getState:()=>({...state,...model(),space:viewport.getState()}),getConstructionSteps:()=>steps,getConstructionStep:()=>constructionStep,setConstructionStep(i){constructionStep=i===null?null:Math.max(0,Math.min(steps.length-1,Math.trunc(Number(i)||0)));render();},destroy:()=>viewport.destroy()};
  }
};
