Problems[17] = {
  title: '四棱锥中的平行与距离不变量',
  statement: `四棱锥 ${M.inline('P-ABCD')} 中，${M.inline(String.raw`PD\perp\text{底面}\,ABCD`)}，底面 ${M.inline('ABCD')} 为正方形，${M.inline('E,F,G')} 分别为 ${M.inline('BC,AD,PA')} 中点。<span class="statement-part">（1）证明 <span class="target">${M.inline(String.raw`PE\parallel\text{平面}\,BFG`)}</span>。</span><span class="statement-part">（2）若 ${M.inline('AB=2')}，求 <span class="target">点 ${M.inline('E')} 到平面 ${M.inline('BFG')} 的距离</span>。</span>`,
  mount(host) {
    const initial={part:1,height:2.5,yaw:.58,pitch:.38};let state={...initial},constructionStep=null,geometryKey='',readoutKey='',proofPart=0;
    const commonSteps=[{title:'正方形底面与垂直高',body:`画正方形 ${M.inline('ABCD')}，从 ${M.inline('D')} 竖起 ${M.inline(String.raw`PD\perp\text{底面}`)}，连接 ${M.inline('P')} 与底面顶点。滑杆只改变高，保留正方形与垂直关系。`},{title:'按题设标出三个中点',body:`分别标出 ${M.inline('BC,AD,PA')} 的中点 ${M.inline('E,F,G')}。在 ${M.inline(String.raw`\triangle APD`)} 中，中位线 ${M.inline(String.raw`FG\parallel PD`)}，所以 ${M.inline('FG')} 也垂直于底面。`},{title:'看清目标平面的方向',body:`用蓝色标出平面 ${M.inline('BFG')}。它包含垂直于底面的 ${M.inline('FG')}，因而是经过底面直线 ${M.inline('BF')} 的竖直平面。`}];
    const steps={1:[...commonSteps,{title:'延长中位线，得到辅助点 T',body:`延长 ${M.inline('FG')} 到 ${M.inline('T')}，使 ${M.inline('GT=FG')}。于是 ${M.inline('FT=PD')} 且两线平行，${M.inline('DFTP')} 为平行四边形，所以 ${M.inline(String.raw`PT\parallel DF`)} 且 ${M.inline('PT=DF=BE')}。`},{title:'在平面内找到与 PE 平行的线',body:`${M.inline(String.raw`PT\parallel BE`)} 且 ${M.inline('PT=BE')}，因此 ${M.inline('PTBE')} 为平行四边形，${M.inline(String.raw`PE\parallel TB`)}。绿色 ${M.inline('TB')} 在平面 ${M.inline('BFG')} 内，而 ${M.inline('E')} 不在该平面内，得到所求线面平行。`}],2:[...commonSteps,{title:'把空间垂距落到底面里',body:`在底面内从 ${M.inline('E')} 向 ${M.inline('BF')} 作垂线，垂足为 ${M.inline('H')}。${M.inline(String.raw`EH\perp BF`)} 且 ${M.inline(String.raw`EH\perp FG`)}，故 ${M.inline('EH')} 垂直于平面 ${M.inline('BFG')}。`},{title:'用三角形面积求垂距',body:`${M.inline('AB=2')} 时，${M.inline(String.raw`BF=\sqrt5`)}，${M.inline(String.raw`S_{\triangle BEF}=\frac12\cdot2\cdot1=1`)}。所以 ${M.inline(String.raw`EH=\frac{2S_{\triangle BEF}}{BF}=\frac2{\sqrt5}`)}，不含高 ${M.inline('PD')}。`} ]};
    host.innerHTML=`<div class="controls"><label>小问 <select id="b17-part"><option value="1">（1）寻找平面内的平行线</option><option value="2">（2）把空间距离降到平面</option></select></label><label>高 ${M.inline('PD')} <input id="b17-height" type="range" min="0.6" max="4" step="0.02" value="2.5"><output id="b17-height-value"></output></label><button id="b17-view">恢复视角</button><button id="b17-top">俯视底面</button><span class="hint">拖动旋转 · 滚轮缩放</span></div><div class="figures"><svg id="b17-svg" class="main-figure" role="img" aria-label="改变四棱锥高，观察线面平行及点到竖直平面的距离不变"></svg></div><div class="readout" id="b17-readout"></div><div class="explain" id="b17-explain"></div>`;
    const C=Lab.C,mid=(a,b)=>a.map((x,i)=>(x+b[i])/2);
    function model(){const A=[0,0,0],B=[2,0,0],C=[2,2,0],D=[0,2,0],P=[0,2,state.height],E=mid(B,C),F=mid(A,D),G=mid(P,A),T=[0,1,state.height],H=[1.6,.2,0];return {A,B,C,D,P,E,F,G,T,H,distance:2/Math.sqrt(5),normal:[1,2,0],parallelDot:0,bf:Math.sqrt(5),baseArea:4};}
    const viewport=Space.create(host.querySelector('#b17-svg'),{center:[1,1,1.55],span:5.3,view:initial,onViewChange:v=>Object.assign(state,{yaw:v.yaw,pitch:v.pitch})});
    function scene(m){const points=[],edges=[],faces=[],annotations=[],stage=constructionStep===null?4:constructionStep,reveal=document.body.classList.contains('show-key'),aux=constructionStep!==null?stage>=3:reveal;
      const edge=(id,a,b,color=C.ink,width=2,more={})=>edges.push({id,a,b,color,width,...more}),point=(id,at,color=C.ink)=>points.push({id,at,label:id,color,priority:['E','G','H'].includes(id)?98:85});
      faces.push({id:'base',vertices:[m.A,m.B,m.C,m.D],color:C.ink,opacity:.055});[['A','B'],['B','C'],['C','D'],['D','A']].forEach(([a,b],i)=>{edge(a+b,m[a],m[b]);faces.push({id:'side-'+i,vertices:[m.P,m[a],m[b]],color:C.ink,opacity:.035});});['A','B','C','D'].forEach(id=>{edge('P'+id,m.P,m[id],id==='D'?C.gold:C.ink,id==='D'?2.8:1.8);point(id,m[id]);});point('P',m.P);
      if(stage>=1){['E','F','G'].forEach(id=>point(id,m[id],id==='E'?C.target:C.green));edge('FG',m.F,m.G,C.green,3,{occlude:false});}
      if(stage>=2){const J=[2,0,state.height];faces.push({id:'target-plane',vertices:[m.B,m.F,m.T,J],color:C.blue,opacity:.17,occluder:false});edge('BF',m.B,m.F,C.blue,2.8,{occlude:false});edge('BG',m.B,m.G,C.blue,1.7,{dash:'5 4',occlude:false});annotations.push({id:'plane-label',at:[1,.5,state.height*.75],tex:String.raw`\text{平面 }BFG`,color:C.blue,size:19,priority:72});}
      if(state.part===1&&stage>=2){edge('PE',m.P,m.E,C.target,3.7,{occlude:false});if(aux){point('T',m.T,C.green);edge('GT',m.G,m.T,C.green,2.4,{dash:'5 4',occlude:false});edge('PT',m.P,m.T,C.gold,2.6,{occlude:false});edge('BE',m.B,m.E,C.gold,2.6,{occlude:false});if(stage>=4){edge('TB',m.T,m.B,C.green,3.2,{occlude:false});annotations.push({id:'parallel',at:mid(m.T,m.B),tex:String.raw`TB\parallel PE`,color:C.green,size:19,priority:85});}}}
      if(state.part===2&&stage>=3){point('H',m.H,C.target);edge('EH',m.E,m.H,C.target,4,{occlude:false});edge('EF',m.E,m.F,C.gold,2,{occlude:false});faces.push({id:'distance-triangle',vertices:[m.E,m.B,m.F],color:C.gold,opacity:.07,occluder:false});const u=[-.12,.06,0],v=[.06,.12,0],add=(a,b)=>a.map((x,i)=>x+b[i]);edge('right-a',add(m.H,u),add(add(m.H,u),v),C.target,1.4,{occlude:false});edge('right-b',add(add(m.H,u),v),add(m.H,v),C.target,1.4,{occlude:false});annotations.push({id:'distance-label',at:mid(m.E,m.H),tex:stage>=4?String.raw`\frac2{\sqrt5}`:'EH',color:C.target,size:23,priority:105});}
      return {points,edges,faces,annotations};}
    function render(){const m=model(),key=state.part+'|'+state.height,skey=key+'|'+constructionStep+'|'+document.body.classList.contains('show-key');host.querySelector('#b17-part').value=state.part;host.querySelector('#b17-height').value=state.height;host.querySelector('#b17-height-value').textContent=Lab.fmt(state.height,2);if(skey!==geometryKey){geometryKey=skey;viewport.setScene(scene(m));}else viewport.render();if(key!==readoutKey){readoutKey=key;host.querySelector('#b17-readout').innerHTML=state.part===1?`<span>${M.inline(String.raw`PD\approx${Lab.fmt(state.height,2)}`)}</span><span style="color:${C.green}">${M.inline(String.raw`FG=\frac12PD`)}</span>${M.answer(M.inline(String.raw`PE\parallel\text{平面}\,BFG`))}<small>第一问用边长 2 的正方形作等比例代表，证明适用于任意边长。显示关键关系，或按条件画图，看绿色辅助线 ${M.inline('TB')}。</small>`:`<span>${M.inline(String.raw`PD\approx${Lab.fmt(state.height,2)}`)}</span><span>${M.inline(String.raw`AB=2,\quad BF=\sqrt5`)}</span>${M.answer(M.inline(String.raw`d(E,\text{平面}\,BFG)=\frac2{\sqrt5}=\frac{2\sqrt5}{5}`))}<small>改变高，蓝色平面始终竖直；红色垂距约 ${M.inline(Lab.fmt(m.distance,3))}，不随高改变。俯视底面可直接看清垂足 ${M.inline('H')}。</small>`;}
      if(proofPart!==state.part){proofPart=state.part;host.querySelector('#b17-explain').innerHTML=state.part===1?`<section class="proof-step"><h3>中位线确定目标平面的竖直方向</h3><p>在 ${M.inline(String.raw`\triangle APD`)} 中，${M.inline('F,G')} 是两边中点，所以</p>${M.block(String.raw`FG\parallel PD,\qquad FG=\frac12PD`)}<p>延长 ${M.inline('FG')} 到 ${M.inline('T')}，使 ${M.inline('GT=FG')}，则 ${M.inline(String.raw`FT\parallel PD`)} 且 ${M.inline('FT=PD')}。</p></section><section class="proof-step"><h3>构造平行四边形</h3><p>因此 ${M.inline('DFTP')} 为平行四边形，${M.inline(String.raw`PT\parallel DF`)}，${M.inline('PT=DF')}。正方形中 ${M.inline('DF=BE')} 且 ${M.inline(String.raw`DF\parallel BE`)}，故 ${M.inline(String.raw`PT\parallel BE`)} 且 ${M.inline('PT=BE')}，四边形 ${M.inline('PTBE')} 是平行四边形。</p>${M.block(String.raw`PE\parallel TB`)}</section><section class="proof-step"><h3>从线线平行得到线面平行</h3><p>${M.inline('T')} 在 ${M.inline('FG')} 的延长线上，故 ${M.inline('TB')} 在平面 ${M.inline('BFG')} 内。又 ${M.inline('E')} 不在底面交线 ${M.inline('BF')} 上，所以 ${M.inline('E')} 不在该平面内。</p><div class="target">${M.block(String.raw`PE\parallel\text{平面}\,BFG`)}</div><p>辅助点 ${M.inline('T')} 可以在原四棱锥之外；它只用于在目标平面内构造平行线。</p></section>`:`<section class="proof-step"><h3>空间垂距为什么可以在底面内作出</h3><p>由中位线 ${M.inline(String.raw`FG\parallel PD`)}，得 ${M.inline(String.raw`FG\perp\text{底面}\,ABCD`)}。在底面内作 ${M.inline(String.raw`EH\perp BF`)}，${M.inline('H')} 在 ${M.inline('BF')} 上。</p><p>${M.inline('EH')} 也垂直于 ${M.inline('FG')} 的方向，而 ${M.inline('BF,FG')} 为目标平面内两条相交直线，所以 ${M.inline(String.raw`EH\perp\text{平面}\,BFG`)}，所求距离就是 ${M.inline('EH')}。</p></section><section class="proof-step"><h3>用同一个三角形的两种面积式</h3><p>${M.inline('AB=2')}，所以 ${M.inline('AF=BE=1')}，${M.inline('EF=2')}。</p>${M.block(String.raw`BF=\sqrt{AB^2+AF^2}=\sqrt5`)}${M.block(String.raw`S_{\triangle BEF}=\frac12\,BE\cdot EF=1`)}<div class="target">${M.block(String.raw`EH=\frac{2S_{\triangle BEF}}{BF}=\frac2{\sqrt5}=\frac{2\sqrt5}{5}`)}</div></section><section class="proof-step"><h3>为什么高度没有进入答案</h3><p>改变 ${M.inline('PD')} 只移动 ${M.inline('P,G')} 的高度。平面 ${M.inline('BFG')} 始终是经过固定直线 ${M.inline('BF')} 的竖直平面，而 ${M.inline('E')} 也固定在底面内，因此垂距不变。这里要求 ${M.inline('PD>0')}，不能把锥体压成退化图形。</p></section>`;}}
    host.querySelector('#b17-part').onchange=e=>{state.part=+e.target.value;if(constructionStep!==null)constructionStep=0;render();host.dispatchEvent(new Event('constructionchange'));};host.querySelector('#b17-height').oninput=e=>{state.height=+e.target.value;render();};host.querySelector('#b17-view').onclick=()=>viewport.resetView();host.querySelector('#b17-top').onclick=()=>viewport.setView({yaw:0,pitch:1.42,zoom:1});
    render();return {render,reset(){state={...initial};if(constructionStep!==null)constructionStep=0;viewport.resetView();render();host.dispatchEvent(new Event('constructionchange'));},getState:()=>({...state,...model(),space:viewport.getState()}),getConstructionSteps:()=>steps[state.part],getConstructionStep:()=>constructionStep,setConstructionStep(i){constructionStep=i===null?null:Math.max(0,Math.min(steps[state.part].length-1,Math.trunc(Number(i)||0)));render();},destroy:()=>viewport.destroy()};
  }
};
