Problems[10]={title:'复数模：圆盘到直线的距离',statement:`${M.inline(String.raw`|z_1-1+\mathrm i|\le\sqrt2`)}，${M.inline(String.raw`|z_2|=|z_2+1-\mathrm i|`)}。求 <span class="target">${M.inline(String.raw`|z_1-z_2|`)} 的最小值</span>。`,mount(host){
  const H=HuangpuMath,C=Lab.C;let state={angle:150,radius:.75,t:.7},plot,drag=null;
  const steps=[
    {title:'把复数放进平面',body:`横轴表示实部，纵轴表示虚部。${M.inline('z_1')} 对应点 ${M.inline('P')}，${M.inline('z_2')} 对应点 ${M.inline('Q')}；复数差的模就是两点距离。`},
    {title:'第一条条件给出整个圆盘',body:`${M.inline(String.raw`|z_1-(1-\mathrm i)|\le\sqrt2`)} 表示到 ${M.inline('C(1,-1)')} 的距离不超过 ${M.inline(String.raw`\sqrt2`)}。画圆并涂出内部，${M.inline('P')} 可以在整个闭圆盘内移动。`},
    {title:'等距条件给出垂直平分线',body:`${M.inline(String.raw`|z_2|=|z_2-(-1+\mathrm i)|`)} 表示 ${M.inline('Q')} 到 ${M.inline('O(0,0)')} 与 ${M.inline('N(-1,1)')} 等距。连 ${M.inline('ON')}，画它的垂直平分线 ${M.inline('x-y+1=0')}，${M.inline('Q')} 必须在这条直线上。`},
    {title:'先固定 P，让 Q 走到垂足',body:`所求 ${M.inline(String.raw`|z_1-z_2|=PQ`)} 是红线长度。从 ${M.inline('P')} 向直线作垂线；固定 ${M.inline('P')} 时，垂足给出最短的 ${M.inline('PQ')}。`},
    {title:'再从圆盘里挑最近的 P',body:`连圆心到直线的垂线，圆心距离为 ${M.inline(String.raw`\frac3{\sqrt2}`)}。沿它走到圆周就减少一个半径，所以全局最短距离为 ${M.inline(String.raw`\frac3{\sqrt2}-\sqrt2=\frac{\sqrt2}{2}`)}。点击“取全局最短”验证取等位置。`}
  ];
  const construction=H.construction(host,steps,render);
  host.innerHTML=`<div class="controls"><label>圆盘内方向 <input id="q10-angle" type="range" min="0" max="360" step="1" value="150"></label><label>半径比例 <input id="q10-radius" type="range" min="0" max="1" step=".01" value=".75"></label><label>Q 的实部 <input id="q10-t" type="range" min="-2.5" max="2.5" step=".01" value=".7"></label><button id="q10-foot">Q 移到当前垂足</button><button id="q10-minimum">取全局最短</button><span class="hint">可拖动 P、Q</span></div><div class="figures"><svg id="q10-svg" class="main-figure" role="img" aria-label="复平面内的圆盘、等距直线与所求距离"></svg></div><div id="q10-readout" class="readout"></div><div class="explain"><section class="proof-step"><h3>先把两条条件转成几何对象</h3>${M.block(String.raw`(x_1-1)^2+(y_1+1)^2\le2`)}${M.block(String.raw`x_2^2+y_2^2=(x_2+1)^2+(y_2-1)^2\iff x_2-y_2+1=0`)}</section><section class="proof-step"><h3>下界对整个圆盘都成立</h3><p>圆心 ${M.inline('C(1,-1)')} 到直线的距离为 ${M.inline(String.raw`d=\frac3{\sqrt2}`)}。对任意合法点，由三角不等式</p>${M.block(String.raw`PQ\ge CQ-CP\ge d-\sqrt2=\frac{\sqrt2}{2}.`)}<p>取 ${M.inline('P=(0,0)')}，${M.inline(String.raw`Q=(-\frac12,\frac12)`)}，两点均满足原条件，且达到此下界。因此该值是最小值，而非仅一次测量。</p></section></div>`;
  const el=id=>host.querySelector('#q10-'+id),svg=el('svg');
  function render(){const m=H.complex(state.angle,state.radius,state.t);for(const k of ['angle','radius','t'])el(k).value=state[k];const bounds={xmin:Math.min(-2.1,m.Q[0]-.45),xmax:Math.max(2.7,m.Q[0]+.45),ymin:-2.7,ymax:Math.max(2.1,m.Q[1]+.45),pad:42},p=Lab.plot(svg,bounds);plot=p;p.axes({x:'实部',y:'虚部'});p.dot([0,0],construction.show(1)&&H.norm(m.P)<1e-10?'':'O',C.ink,-22,22);
    if(construction.show(1)){p.circle(m.center,Math.SQRT2,{stroke:'none',fill:C.blue,opacity:.12});p.circle(m.center,Math.SQRT2,{stroke:C.blue});p.dot(m.center,'C',C.blue,12,22);p.line(m.center,m.P,{stroke:C.blue,width:1.2,dash:'4 4'});p.dot(m.P,H.norm(m.P)<1e-10?'P = O':'P',C.blue,12,-12);}
    if(construction.show(2)){p.dot([-1,1],'N',C.gold,-20,-12);p.line([0,0],[-1,1],{stroke:C.gold,dash:'5 5',width:1.2});const left=Math.max(bounds.xmin,bounds.ymin-1),right=Math.min(bounds.xmax,bounds.ymax-1);p.line([left,left+1],[right,right+1],{stroke:C.ink,width:2.4});p.math([right-.25,right+.75],'x-y+1=0',{dx:10,dy:-18,size:19});p.dot(m.Q,construction.show(3)&&H.norm(H.sub(m.foot,m.Q))<1e-9?'':'Q',C.gold,-22,22);}
    if(construction.show(3)){p.line(m.P,m.Q,{stroke:C.target,width:3.5});p.line(m.P,m.foot,{stroke:C.green,dash:'4 4',width:1.8});p.dot(m.foot,H.norm(H.sub(m.foot,m.Q))<1e-9?'Q = H':'H',C.green,10,22);p.screenMath(18,30,String.raw`PQ\approx${M.number(m.distance,3)}`,{color:C.target,size:23});}
    if(construction.show(4)){p.line(m.center,[-.5,.5],{stroke:C.gold,width:2,dash:'6 4'});p.line(m.center,[0,0],{stroke:C.blue,width:2});p.math([.5,-.5],String.raw`\sqrt2`,{color:C.blue,dx:18,dy:9});p.screenMath(18,p.h-20,String.raw`\min PQ=\frac{\sqrt2}{2}`,{color:C.target,size:24});}
    p.finish();el('readout').innerHTML=`<span>当前 ${M.inline(String.raw`PQ\approx${M.number(m.distance,3)}`)}</span><span>当前 P 到直线 ${M.inline(String.raw`\approx${M.number(m.toLine,3)}`)}</span>${M.answer(M.inline(String.raw`\min|z_1-z_2|=\frac{\sqrt2}{2}`))}`;
  }
  for(const k of ['angle','radius','t'])el(k).oninput=e=>{state[k]=+e.target.value;render();};el('foot').onclick=()=>{state.t=H.complex(state.angle,state.radius,state.t).foot[0];render();};el('minimum').onclick=()=>{state={angle:135,radius:1,t:-.5};render();};
  svg.onpointerdown=e=>{const m=H.complex(state.angle,state.radius,state.t),xy=plot.fromEvent(e),dist=P=>H.norm(H.sub(xy,P))*plot.sx;if(construction.show(1)&&dist(m.P)<27)drag='P';else if(construction.show(2)&&dist(m.Q)<27)drag='Q';else return;svg.setPointerCapture(e.pointerId);};svg.onpointermove=e=>{if(!drag)return;const [x,y]=plot.fromEvent(e);if(drag==='P'){state.angle=(Math.atan2(y+1,x-1)*180/Math.PI+360)%360;state.radius=Math.min(1,Math.hypot(x-1,y+1)/Math.SQRT2);}else state.t=Math.max(-2.5,Math.min(2.5,(x+y-1)/2));render();};svg.onpointerup=svg.onpointercancel=()=>drag=null;
  return{render,...construction.api,getState:()=>({...state,...H.complex(state.angle,state.radius,state.t)}),reset(){state={angle:150,radius:.75,t:.7};construction.restart();render();},destroy(){drag=null;svg.onpointerdown=svg.onpointermove=svg.onpointerup=svg.onpointercancel=null;}};
}};
