Problems[14]={title:'正方体：两条直线的角',statement:`从正方体八个顶点中任取四个不同顶点，分别记为 ${M.inline('A,B,C,D')}。直线 ${M.inline('AB,CD')} 所成角不可能是 <span class="target">${M.inline(String.raw`30^\circ,45^\circ,60^\circ,90^\circ`)}</span> 中的哪一个？`,mount(host){
 const H=HuangpuMath,C=Lab.C,groups=[0,45,54.735610317245346,60,70.52877936550931,90];let state={family:45,index:0},key='';
 const steps=[
  {title:'先画正方体的八个候选顶点',body:`取棱长为 ${M.inline('1')} 的正方体；缩放不影响直线所成角。每个顶点的三个坐标都属于 ${M.inline(String.raw`\{0,1\}`)}。`},
  {title:'用两个顶点确定第一条直线',body:`从八个顶点中选出 ${M.inline('A,B')}，连接蓝色 ${M.inline('AB')}。它可能是棱、面对角线或体对角线，因此方向向量的模平方只能是 ${M.inline('1,2,3')}。`},
  {title:'再用两个不同顶点确定第二条直线',body:`从余下六个顶点选 ${M.inline('C,D')}，连接金色 ${M.inline('CD')}。四个顶点互不相同；两条线可能相交、异面或平行，均需比较方向。`},
  {title:'将方向移到同一个起点',body:`右图把两条直线的方向放在同一起点；必要时反向取射线，得到不超过 ${M.inline(String.raw`90^\circ`)} 的角。右图只比较方向，不拿投影画面中的角度充当空间角。`},
  {title:'用整数结构排除 30°',body:`方向向量分量都在 ${M.inline(String.raw`\{-1,0,1\}`)} 中。设点积为整数 ${M.inline('p')}、模平方为 ${M.inline(String.raw`r,s\in\{1,2,3\}`)}，则 ${M.inline(String.raw`\cos^2\theta=\frac{p^2}{rs}`)}。这不可能等于 ${M.inline(String.raw`\cos^2 30^\circ=\frac34`)}；其他三个选项可以直接构造。`}
 ];const construction=H.construction(host,steps,render);
 host.innerHTML=`<div class="controls"><label>观察的角 <select id="q14-family">${groups.map(a=>`<option value="${a}" ${a===45?'selected':''}>${Lab.fmt(a,3)}°</option>`).join('')}</select></label><button id="q14-next">换一个同角构型</button><button id="q14-view">恢复视角</button><span id="q14-count"></span><span class="hint">左图拖动旋转，空间角保持不变</span></div><div class="figures"><svg id="q14-cube" class="figure" role="img" aria-label="正方体内四个不同顶点确定的两条直线"></svg><svg id="q14-angle" class="figure" role="img" aria-label="两条空间直线方向所成的较小角"></svg></div><div class="readout" id="q14-readout"></div><div class="explain"><section class="proof-step"><h3>投影看起来像 30°，不代表空间角是 30°</h3><p>取单位立方体，任一顶点连线的方向分量均为 ${M.inline(String.raw`0,\pm1`)}，模平方 ${M.inline('r,s')} 只能是 ${M.inline('1,2,3')}。所以 ${M.inline('rs')} 只能取 ${M.inline('1,2,3,4,6,9')}，而点积 ${M.inline('p')} 为整数。</p>${M.block(String.raw`\cos^2\theta=\frac{p^2}{rs}=\frac34\Longrightarrow 4p^2=3rs.`)}<p>右端能被 ${M.inline('4')} 整除只可能 ${M.inline('rs=4')}，这又要求 ${M.inline('p^2=3')}，与 ${M.inline('p')} 为整数矛盾。</p></section><section class="proof-step"><h3>其余选项的存在性</h3><p>选择菜单中的 ${M.inline(String.raw`45^\circ,60^\circ,90^\circ`)}，每个构型都给出四个不同顶点的实例。完整枚举共 ${M.inline(String.raw`\binom84\cdot3=210`)} 组配对，仅用作核查；上面的整数论证已经排除了 ${M.inline(String.raw`30^\circ`)}。</p></section></div>`;
 const el=id=>host.querySelector('#q14-'+id),viewport=Space.create(el('cube'),{center:[.5,.5,.5],span:2.3,view:{yaw:-.75,pitch:.48}});
 const candidates=()=>H.cubePairs.filter(p=>Math.abs(p.angle-state.family)<1e-6);
 function render(){const all=candidates(),m=all[state.index%all.length];el('family').value=state.family;el('count').textContent=`本类 ${all.length} 个顶点配对 · 当前 ${state.index%all.length+1}`;el('angle').toggleAttribute('hidden',!construction.show(3));const cache=state.family+'|'+state.index+'|'+construction.get();
  if(key!==cache){key=cache;const scene=H.cubeScene(C);scene.points=[];scene.edges.forEach(edge=>{edge.width=1.2;edge.opacity=.45;});m.ids.forEach((v,i)=>scene.points.push({id:'chosen-'+i,at:H.vertices[v],label:'ABCD'[i],color:i<2?C.blue:C.gold,priority:95,occlude:false,layer:i<2?1:2}));scene.edges.push({id:'AB',a:H.vertices[m.ids[0]],b:H.vertices[m.ids[1]],color:C.blue,width:3.6,occlude:false,layer:1},{id:'CD',a:H.vertices[m.ids[2]],b:H.vertices[m.ids[3]],color:C.gold,width:3.6,occlude:false,layer:2});viewport.setScene(H.layers(scene,construction));}else viewport.render();
  if(construction.show(3)){const p=Lab.plot(el('angle'),{xmin:-.3,xmax:1.6,ymin:-.4,ymax:1.4,pad:50}),ang=m.angle*Math.PI/180;const end=[1.15*Math.cos(ang),1.15*Math.sin(ang)];p.line([0,0],[1.3,0],{stroke:C.blue,width:3});p.line([0,0],end,{stroke:C.gold,width:3});p.dot([0,0],'R',C.ink,-22,24);p.math([1.22,0],String.raw`AB\text{ 的方向}`,{color:C.blue,anchor:'end',dy:33,size:18});p.math(end,String.raw`CD\text{ 的方向}`,{color:C.gold,dx:10,dy:-18,size:18});for(let i=0;i<32;i++)p.line([.38*Math.cos(ang*i/32),.38*Math.sin(ang*i/32)],[.38*Math.cos(ang*(i+1)/32),.38*Math.sin(ang*(i+1)/32)],{stroke:C.target,width:2});p.screenMath(18,35,String.raw`\theta\approx${M.number(m.angle,3)}^\circ`,{color:C.target,size:25});if(construction.show(4))p.screenMath(18,p.h-22,String.raw`\cos^2\theta=\frac{${m.p*m.p}}{${m.r*m.s}}`,{color:C.target,size:22});p.finish();}else el('angle').replaceChildren();
  el('readout').innerHTML=`${M.inline(String.raw`\vec u=(${m.u.join(',')}),\quad\vec v=(${m.v.join(',')})`)}<span class="target">${M.inline(String.raw`\theta\approx${M.number(m.angle,3)}^\circ`)}</span>${M.answer('选 A：'+M.inline(String.raw`30^\circ`)+' 不可能。')}`;
 }
 el('family').onchange=e=>{state.family=+e.target.value;state.index=0;render();};el('next').onclick=()=>{state.index=(state.index+1)%candidates().length;render();};el('view').onclick=()=>viewport.resetView();
 return{render,...construction.api,getState:()=>({...state,pair:candidates()[state.index%candidates().length],space:viewport.getState()}),reset(){state={family:45,index:0};key='';construction.restart();viewport.resetView();render();},destroy(){viewport.destroy();}};
}};
