Problems[16]={title:'递减函数迭代：奇偶项为何反向？',statement:`${M.inline(String.raw`f'(x)<0`)} 在区间 ${M.inline('I')} 恒成立，且 ${M.inline(String.raw`f(I)\subseteq I`)}。数列满足 ${M.inline('a_{n+1}=f(a_n)')}，各项均不相同。判断 <span class="target">奇数项与偶数项子列的单调性</span>。`,mount(host){
 const H=HuangpuMath,C=Lab.C;let state={kind:'contract',a1:.4,n:8};
 const tex=()=>state.kind==='nonlinear'?String.raw`f(x)=e^{-x}`:state.kind==='expand'?String.raw`f(x)=2-\frac54x`:String.raw`f(x)=2-\frac12x`;
 const steps=[
  {title:'先画一个满足题设的递减函数',body:`本图所选 ${M.inline('f')} 在 ${M.inline(String.raw`I=\mathbf R`)} 上严格递减，并把 ${M.inline('I')} 映入自身。它是原题的一种合法实例；一般结论随后只用“递减”证明。`},
  {title:'画 y=x，把输出变成下一次输入',body:`补画 ${M.inline('y=x')}。曲线上点 ${M.inline('(a_n,a_{n+1})')} 的纵坐标，经水平移动到这条直线后，就成为下一次输入 ${M.inline('a_{n+1}')}。`},
  {title:'从首项画到第二项',body:`从横轴的 ${M.inline('a_1')} 竖直到函数曲线，得到 ${M.inline('a_2=f(a_1)')}；再水平到 ${M.inline('y=x')}，完成一次迭代。`},
  {title:'再走一次，比较 a₁ 与 a₃',body:`继续“竖直到曲线、水平到对角线”得到 ${M.inline('a_3')}。题设各项互异，所以 ${M.inline('a_1')} 与 ${M.inline('a_3')} 严格有序；递减函数每作用一次会反转顺序。`},
  {title:'将奇数项、偶数项分开连线',body:`右图红实线连接奇数项，红虚线连接偶数项。观察 ${M.inline('a_1')} 与 ${M.inline('a_3')} 的次序如何传递到 ${M.inline('a_2')} 与 ${M.inline('a_4')}；可单步增加项数，而非把整个数列误认成单调数列。`},
  {title:'连续两次反序，子列方向保持',body:`${M.inline(String.raw`f\circ f`)} 严格递增，所以奇数项的第一对次序会一直保持；偶数项的第一对方向恰好相反。因此一列严格增、另一列严格减，选 ${M.inline('C')}。收敛与发散都不改变这个结论。`}
 ];const construction=H.construction(host,steps,render);
 host.innerHTML=`<div class="controls"><label>递减函数 <select id="q16-kind"><option value="contract">线性收敛</option><option value="expand">线性发散</option><option value="nonlinear">指数型</option></select></label><label>首项 <input id="q16-first" type="number" min="-2" max="3" step=".1" value=".4"></label><label>显示项数 <input id="q16-count" type="range" min="4" max="18" step="1" value="8"><output id="q16-count-value"></output></label><button id="q16-next">再迭代一项</button><button id="q16-fixed">首项取不动点（反例边界）</button></div><div class="figures"><svg id="q16-web" class="figure" role="img" aria-label="递减函数的逐次迭代蛛网图"></svg><svg id="q16-terms" class="figure" role="img" aria-label="分别连接奇数项和偶数项的项值图"></svg></div><div class="readout" id="q16-readout"></div><div class="explain"><section class="proof-step"><h3>一次反序，两次保序</h3><p>由 ${M.inline(String.raw`f'(x)<0`)}，${M.inline('f')} 严格递减。故 ${M.inline(String.raw`g=f\circ f`)} 严格递增，且 ${M.inline('a_{n+2}=g(a_n)')}。</p><p>若 ${M.inline('a_1<a_3')}，对递增的 ${M.inline('g')} 反复应用，得</p>${M.block(String.raw`a_1<a_3<a_5<\cdots.`)}<p>再对每个不等式应用递减的 ${M.inline('f')}：</p>${M.block(String.raw`a_2>a_4>a_6>\cdots.`)}<p>若 ${M.inline('a_1>a_3')}，两列方向全部反过来。各项互异排除了 ${M.inline('a_1=a_3')} 的周期情形。</p></section><section class="proof-step"><h3>为什么不要求收敛？</h3><p>单调性来自反序与保序，无须有界性。菜单中的线性发散例子也满足原题。取不动点会得到常数列，${M.inline('f(x)=2-x')} 则可能产生二周期；这些都违反“各项均不相同”，不能充当原题反例。</p></section></div>`;
 const el=id=>host.querySelector('#q16-'+id);
 function render(){const m=H.recurrence(state.kind,state.a1,state.n),visibleN=construction.get()===null||construction.show(4)?state.n:construction.show(3)?3:construction.show(2)?2:0;el('kind').value=state.kind;el('first').value=state.a1;el('count').value=state.n;el('count-value').textContent=state.n;el('terms').toggleAttribute('hidden',!construction.show(4));
  const low=Math.min(-.3,...m.terms,m.fixed)-.5,high=Math.max(2.4,...m.terms,m.fixed)+.5;
  const p=Lab.plot(el('web'),{xmin:low,xmax:high,ymin:low,ymax:high,pad:48});p.axes();p.curve(m.fn,low,high,{stroke:C.blue,width:2.8});p.screenMath(17,31,tex(),{color:C.blue,size:21});if(construction.show(1)){p.line([low,low],[high,high],{stroke:C.gray,width:1.4,dash:'5 5'});p.math([high*.82,high*.82],'y=x',{color:C.gray,dx:14,dy:-10,size:17});}
  if(visibleN>=2){p.dot([state.a1,0],'a₁',C.gold,-16,28);let last=[state.a1,0];for(let i=1;i<visibleN;i++){const point=[m.terms[i-1],m.terms[i]],end=[m.terms[i],m.terms[i]];p.line(last,point,{stroke:i%2?C.gold:C.green,width:i===visibleN-1?2.5:1.6});p.line(point,end,{stroke:i%2?C.gold:C.green,width:1.6,dash:i%2?'':'4 3'});last=end;}if(!m.valid)p.text([m.fixed,m.fixed],'不动点：所有项重合',{color:C.target,dx:14,dy:-15,size:18});}
  p.finish();
  if(construction.show(4)){const q=Lab.plot(el('terms'),{xmin:.5,xmax:state.n+.7,ymin:low,ymax:high,equal:false,pad:50});q.axes({x:'项数 n',y:'aₙ',stepX:state.n>12?2:1});q.screenText(16,27,'红实线：奇数项　红虚线：偶数项',{size:16,color:C.target});const paritySegments=m.terms.slice(2).map((value,i)=>[[i+1,m.terms[i]],[i+3,value]]);for(let i=0;i<m.terms.length;i++){if(i>=2)q.line(paritySegments[i-2][0],paritySegments[i-2][1],{stroke:C.target,width:2.4,dash:i%2?'5 4':''});q.dot([i+1,m.terms[i]],'',i%2?C.gold:C.blue);if(i<4)q.math([i+1,m.terms[i]],`a_${i+1}`,{color:i%2?C.gold:C.blue,size:18,dx:i<2?-14:9,dy:i%2?24:-13,priority:4,avoidSegments:paritySegments});}if(construction.show(5))q.screenText(16,q.h-13,m.valid?(m.terms[2]>m.terms[0]?'奇数项严格增 · 偶数项严格减':'奇数项严格减 · 偶数项严格增'):'不满足各项互异，不能套用原题',{size:18,color:C.target});q.finish();}else el('terms').replaceChildren();
  el('readout').innerHTML=`${M.inline(tex())}<span>${M.inline(String.raw`a_1=${M.number(state.a1,4)}`)}</span>${!m.valid?'<span class="warning">当前为不动点示例，不满足各项互异。</span>':''}${M.answer('选 C：奇数项与偶数项子列，一列严格增，另一列严格减。')}`;
 }
 el('kind').onchange=e=>{state.kind=e.target.value;state.a1=.4;construction.restart();render();};el('first').onchange=e=>{const v=+e.target.value;if(Number.isFinite(v))state.a1=Math.max(-2,Math.min(3,v));render();};el('count').oninput=e=>{state.n=+e.target.value;render();};el('next').onclick=()=>{state.n=Math.min(18,state.n+1);render();};el('fixed').onclick=()=>{state.a1=H.recurrence(state.kind,state.a1,4).fixed;render();};
 return{render,...construction.api,getState:()=>({...state,terms:H.recurrence(state.kind,state.a1,state.n).terms}),reset(){state={kind:'contract',a1:.4,n:8};construction.restart();render();}};
}};
