Problems[17]={title:'正方体：线面垂直与线面角',statement:`在正方体 ${M.inline('ABCD-A_1B_1C_1D_1')} 中，${M.inline('E')} 是 ${M.inline('BC_1')} 的中点。（1）证明 <span class="target">${M.inline(String.raw`BC_1\perp\text{平面 }CDE`)}</span>；（2）求 <span class="target">直线 ${M.inline('DE')} 与底面所成角</span>。`,mount(host){
 const H=HuangpuMath,C=Lab.C,P=H.cubePoints,E=H.mid(P.B,P.C1),foot=[1,.5,0],angle=Math.atan(1/Math.sqrt(5));let state={part:1,section:false},key='';
 const steps=()=>state.part===1?[
  {title:'先建立正方体',body:`画单位正方体。所有棱长同时缩放不影响垂直关系，因此可取棱长 ${M.inline('1')}。右侧面 ${M.inline('BCC_1B_1')} 是正方形。`},
  {title:'按中点条件落下 E',body:`连接右侧面对角线 ${M.inline('BC_1')}，在它的中点标出 ${M.inline('E')}。${M.inline('E')} 在侧面的中心，不在竖直棱上。`},
  {title:'用三点建立目标平面',body:`连接 ${M.inline('CE,DE')}，与已有的 ${M.inline('CD')} 围成平面 ${M.inline('CDE')} 的可见部分。红线 ${M.inline('BC_1')} 是要证明与此面垂直的线。`},
  {title:'在面内找第一条垂线',body:`连接侧面的另一条对角线 ${M.inline('CB_1')}。正方形对角线互相垂直，且都过 ${M.inline('E')}，所以 ${M.inline(String.raw`BC_1\perp CE`)}。绿色 ${M.inline('CE')} 就是目标面内的第一条垂线。`},
  {title:'找到相交的第二条垂线',body:`${M.inline('CD')} 同时垂直于右侧面的两条相交棱，因此垂直于整个右侧面，特别有 ${M.inline(String.raw`CD\perp BC_1`)}。${M.inline('CD')} 与 ${M.inline('CE')} 在 ${M.inline('C')} 相交，这两条面内垂线给出线面垂直。`}
 ]:[
  {title:'先画正方体与底面',body:`画正方体，底面 ${M.inline('ABCD')} 用浅色表示。线面角是直线与其正投影所成的角，不是画面上看见的任意夹角。`},
  {title:'由中点确定 E，再画 DE',body:`在侧面对角线 ${M.inline('BC_1')} 的中点取 ${M.inline('E')}，连接所研究的直线 ${M.inline('DE')}。`},
  {title:'把 E 垂直投影到底面',body:`过 ${M.inline('E')} 作 ${M.inline('EH')} 垂直底面。由中点关系，${M.inline('H')} 是 ${M.inline('BC')} 的中点，且 ${M.inline(String.raw`EH=\frac12`)}。`},
  {title:'连接真正的底面投影 DH',body:`${M.inline('D')} 本来就在底面，故 ${M.inline('DE')} 的正投影是 ${M.inline('DH')}。在底面直角三角形 ${M.inline('DCH')} 中，${M.inline(String.raw`DH=\sqrt{1^2+(\frac12)^2}=\frac{\sqrt5}{2}`)}。`},
  {title:'在线面角的直角三角形中求角',body:`红色 ${M.inline(String.raw`\theta=\angle EDH`)} 就是所求角。由 ${M.inline(String.raw`\tan\theta=\frac{EH}{DH}=\frac1{\sqrt5}`)}，得到 ${M.inline(String.raw`\theta=\arctan\frac1{\sqrt5}=\arcsin\frac1{\sqrt6}`)}。`}
 ];const construction=H.construction(host,steps,render);
 host.innerHTML=`<div class="controls"><label>小问 <select id="q17-part"><option value="1">（1）证明线面垂直</option><option value="2">（2）求线面角</option></select></label><button id="q17-section">突出关键截面</button><button id="q17-view">恢复视角</button><span class="hint">拖动旋转 · 滚轮缩放</span></div><div class="figures"><svg id="q17-svg" class="main-figure" role="img" aria-label="正方体中的中点、垂直关系与线面角"></svg></div><div class="readout" id="q17-readout"></div><div class="explain" id="q17-explain"></div>`;
 const el=id=>host.querySelector('#q17-'+id),viewport=Space.create(el('svg'),{center:[.5,.5,.5],span:2.35,view:{yaw:-.75,pitch:.45}});
 function scene(){const s=H.cubeScene(C);if(state.section){s.faces=[];s.edges.forEach(e=>{e.opacity=.22;e.width=1;});}s.points.push({id:'E',at:E,label:'E',color:C.gold,priority:100,layer:1,occlude:false});s.edges.push({id:'given-BC1',a:P.B,b:P.C1,color:state.part===1?C.target:C.gold,width:3.4,layer:1,occlude:false});
  if(state.part===1){s.faces.push({id:'target-CDE',vertices:[P.C,P.D,E],color:C.blue,opacity:.18,occluder:false,layer:2});s.edges.push({id:'CE',a:P.C,b:E,color:C.green,width:3,layer:2,occlude:false},{id:'DE',a:P.D,b:E,color:C.blue,width:2.8,layer:2,occlude:false},{id:'CB1',a:E,b:P.B1,color:C.green,width:1.8,dash:'5 5',layer:3,occlude:false},{id:'target-CD',a:P.C,b:P.D,color:C.green,width:3,layer:4,occlude:false});
   const u=H.scale(H.sub(P.C,E),1/H.norm(H.sub(P.C,E))),v=H.scale(H.sub(P.C1,E),1/H.norm(H.sub(P.C1,E))),a=H.add(E,H.scale(u,.12)),b=H.add(a,H.scale(v,.12)),c=H.add(E,H.scale(v,.12));s.edges.push({id:'perp-a',a,b,color:C.green,width:1.4,layer:3,occlude:false},{id:'perp-b',a:b,b:c,color:C.green,width:1.4,layer:3,occlude:false});s.annotations.push({id:'perp-CE',at:H.mid(P.C,E),tex:String.raw`CE\perp BC_1`,color:C.green,size:18,layer:3,priority:90,dy:24},{id:'perp-CD',at:H.mid(P.C,P.D),tex:String.raw`CD\perp BC_1`,color:C.green,size:18,layer:4,priority:90,dy:-20});
  }else{s.edges.push({id:'DE',a:P.D,b:E,color:C.blue,width:3.5,layer:1,occlude:false},{id:'EH',a:E,b:foot,color:C.gold,width:3,layer:2,occlude:false},{id:'DH',a:P.D,b:foot,color:C.green,width:3,layer:3,occlude:false});s.points.push({id:'H',at:foot,label:'H',color:C.gold,priority:100,layer:2,occlude:false});s.faces.push({id:'angle-triangle',vertices:[P.D,E,foot],color:C.gold,opacity:.08,occluder:false,layer:3});const u=H.scale(H.sub(P.D,foot),1/H.norm(H.sub(P.D,foot))),v=[0,0,.1],a=H.add(foot,H.scale(u,.1)),b=H.add(a,v),c=H.add(foot,v);s.edges.push({id:'right-a',a,b,color:C.gold,width:1.4,layer:2,occlude:false},{id:'right-b',a:b,b:c,color:C.gold,width:1.4,layer:2,occlude:false});const direction=H.scale(H.sub(foot,P.D),1/H.norm(H.sub(foot,P.D)));for(let i=0;i<24;i++){const at=t=>H.add(P.D,H.add(H.scale(direction,.28*Math.cos(t)),[0,0,.28*Math.sin(t)]));s.edges.push({id:'angle-'+i,a:at(angle*i/24),b:at(angle*(i+1)/24),color:C.target,width:2.4,layer:4,occlude:false});}s.annotations.push({id:'EH-value',at:H.mid(E,foot),tex:String.raw`\frac12`,color:C.gold,size:21,priority:100,layer:2,dx:20},{id:'DH-value',at:H.mid(P.D,foot),tex:String.raw`\frac{\sqrt5}{2}`,color:C.green,size:21,priority:90,layer:3,dy:22},{id:'target-angle',at:H.add(P.D,H.scale(direction,.42)),tex:String.raw`\theta\approx24.095^\circ`,color:C.target,size:21,priority:110,layer:4,dy:-22});}
  return H.layers(s,construction);
 }
 function render(){el('part').value=state.part;el('section').setAttribute('aria-pressed',String(state.section));const cache=state.part+'|'+state.section+'|'+construction.get();if(key!==cache){key=cache;viewport.setScene(scene());}else viewport.render();el('readout').innerHTML=M.answer(`（1）${M.inline(String.raw`BC_1\perp\text{平面 }CDE`)}；（2）${M.inline(String.raw`\theta=\arctan\frac1{\sqrt5}\approx24.095^\circ`)}`);
  el('explain').innerHTML=state.part===1?`<section class="proof-step"><h3>正方形对角线给出第一条垂线</h3><p>${M.inline('E')} 是正方形 ${M.inline('BCC_1B_1')} 的中心，${M.inline('C,E,B_1')} 共线。因此 ${M.inline(String.raw`BC_1\perp CE`)}。</p></section><section class="proof-step"><h3>棱与侧面垂直给出第二条</h3><p>${M.inline('CD')} 垂直于侧面内相交的 ${M.inline('CB,CC_1')}，故 ${M.inline(String.raw`CD\perp\text{平面 }BCC_1B_1`)}，进而 ${M.inline(String.raw`CD\perp BC_1`)}。</p><p>${M.inline('CE,CD')} 是平面 ${M.inline('CDE')} 内交于 ${M.inline('C')} 的两条直线，故目标线垂直于整个平面。</p></section>`:`<section class="proof-step"><h3>确定正投影，避免错认角</h3><p>过 ${M.inline('E')} 作 ${M.inline('EH')} 垂直底面，${M.inline('H')} 为 ${M.inline('BC')} 中点。${M.inline(String.raw`\angle EDH`)} 是所求线面角。</p>${M.block(String.raw`EH=\frac12,\quad DH=\sqrt{DC^2+CH^2}=\frac{\sqrt5}{2}.`)}</section><section class="proof-step"><h3>两种三角比核对</h3>${M.block(String.raw`\tan\theta=\frac1{\sqrt5},\quad DE=\frac{\sqrt6}{2},\quad\sin\theta=\frac1{\sqrt6}.`)}<p>两种形式给出同一个 ${M.inline(String.raw`\theta\in(0,\frac\pi2)`)}。</p></section>`;
 }
 el('part').onchange=e=>{state.part=+e.target.value;construction.restart();render();};el('section').onclick=()=>{state.section=!state.section;render();};el('view').onclick=()=>viewport.resetView();return{render,...construction.api,getState:()=>({...state,E,foot,angle,space:viewport.getState()}),reset(){state={part:1,section:false};construction.restart();viewport.resetView();render();},destroy(){viewport.destroy();}};
}};
