Problems[20]={title:'双曲线：一条等长条件限制了什么？',statement:`双曲线 ${M.inline(String.raw`\frac{x^2}{a^2}-\frac{y^2}{b^2}=1`)} 的焦点为 ${M.inline('F_1(-c,0),F_2(c,0)')}。过 ${M.inline('F_1')} 的直线在右支上方交于 ${M.inline('A')}，在左支交于 ${M.inline('B')}。本图探究（3）：${M.inline('c=3')}，什么 ${M.inline('a')} 才存在直线使 <span class="target">${M.inline('AB=AF_2')}</span>？下方给出全题答案。`,mount(host){
 const H=HuangpuMath,C=Lab.C;let state={a:1.2,fraction:.7,attempt:false};
 const steps=[
  {title:'先按焦距画双曲线',body:`第三问给定 ${M.inline('c=3')}，所以 ${M.inline('F_1=(-3,0),F_2=(3,0)')}，且 ${M.inline(String.raw`b^2=9-a^2,\ 0<a<3`)}。本题只需上半平面，图中省略下半部分。改变 ${M.inline('a')} 时，形状改变而焦点不动。`},
  {title:'过左焦点作向右上方的射线',body:`设射线方向与正横轴夹角为 ${M.inline(String.raw`\theta`)}。要在右支上方有有限交点，严格要求 ${M.inline(String.raw`0<\theta<\arccos\frac a3`)}，即 ${M.inline(String.raw`\frac a3<\cos\theta<1`)}。`},
  {title:'沿射线依次找到 B 和 A',body:`合法方向上，点的次序是 ${M.inline('F_1,B,A')}。因此 ${M.inline('AB=AF_1-BF_1')}，而不是两个焦半径相加。红线先标出题设左边的 ${M.inline('AB')}。`},
  {title:'连接右焦点，比较两段长度',body:`连接 ${M.inline('AF_2')}。右支的双曲线定义给出 ${M.inline('AF_1-AF_2=2a')}；所以 ${M.inline('AB=AF_2')} 等价于 ${M.inline('BF_1=2a')}。原本很长的两段线，转化为左焦点附近的一段线。`},
  {title:'把等长条件画成左焦点附近的圆',body:`右图保留左焦点局部：以 ${M.inline('F_1')} 为圆心画半径 ${M.inline('2a')} 的上半圆。${M.inline('B')} 必须同时落在左支和这条红弧上；点在红弧上还不够，射线仍须能到达右支上方。`},
  {title:'检查候选方向是否真的合法',body:`由 ${M.inline(String.raw`BF_1=\frac{9-a^2}{3\cos\theta+a}=2a`)} 得到候选 ${M.inline(String.raw`\cos\theta=\frac{3-a^2}{2a}`)}。把它放回严格区间 ${M.inline(String.raw`\frac a3<\cos\theta<1`)}，恰得到 ${M.inline(String.raw`1<a<\frac3{\sqrt5}`)}；两个端点都不能取。`}
 ];const construction=H.construction(host,steps,render);
 host.innerHTML=`<div class="controls"><label>半实轴 a <input id="q20-a" type="range" min=".65" max="2.55" step=".01" value="1.2"><output id="q20-a-value"></output></label><label>方向（左端为渐近边界）<input id="q20-direction" type="range" min="0" max="1" step=".001" value=".7"></label><button id="q20-target">尝试让 BF₁ = 2a</button><button id="q20-left">a = 1</button><button id="q20-right">${M.inline(String.raw`a=\frac3{\sqrt5}`)}</button><button id="q20-example">a = 1.2</button></div><div class="figures"><svg id="q20-global" class="figure" role="img" aria-label="双曲线上两支交点和两个焦半径的关系"></svg><svg id="q20-local" class="figure" role="img" aria-label="左焦点附近的等长圆与左支交点"></svg></div><div class="readout" id="q20-readout"></div><div class="explain"><section class="proof-step"><h3>（1）代点求参数</h3>${M.block(String.raw`\frac95-\frac{16}{b^2}=1\Rightarrow b^2=20,\quad c=\sqrt{5+20}=5.`)}</section><section class="proof-step"><h3>（2）垂直条件与等比条件</h3><p>${M.inline('AF_2')} 竖直，所以 ${M.inline('x_A=c')}。代入双曲线，因 ${M.inline('A')} 在上方，得 ${M.inline(String.raw`y_A=\frac{b^2}{a}`)}。等比数列给出 ${M.inline('b^2=ac')}，因此</p>${M.block(String.raw`k_l=\frac{y_A}{2c}=\frac{b^2}{2ac}=\frac12.`)}</section><section class="proof-step"><h3>（3）先证明等价关系</h3><p>合法直线沿右上射线依次遇到 ${M.inline('B,A')}。右支定义为 ${M.inline('AF_1-AF_2=2a')}，于是</p>${M.block(String.raw`AB=AF_2\iff AF_1-BF_1=AF_1-2a\iff BF_1=2a.`)}<p>设 ${M.inline('r=BF_1')}。左支定义 ${M.inline('BF_2=r+2a')}，在三角形 ${M.inline('F_1BF_2')} 中用余弦定理：</p>${M.block(String.raw`(r+2a)^2=r^2+36-12r\cos\theta`)}${M.block(String.raw`r=\frac{9-a^2}{3\cos\theta+a}.`)}</section><section class="proof-step"><h3>严格方向区间给出充要条件</h3><p>右支上方交点存在等价于 ${M.inline(String.raw`\frac a3<\cos\theta<1`)}。代入候选方向：</p>${M.block(String.raw`\frac a3<\frac{3-a^2}{2a}<1\iff 1<a<\frac3{\sqrt5}.`)}<p>反过来，在此开区间内，候选余弦确实严格落在合法方向区间，所以存在唯一右上方向，满足等长条件。</p><p class="proof-note">${M.inline('a=1')} 时只能取水平轴，${M.inline('A')} 不在上方；${M.inline(String.raw`a=\frac3{\sqrt5}`)} 时直线平行于渐近线，右支没有有限交点。不能把屏幕外很远的点当成临界位置的交点。</p></section></div>`;
 const el=id=>host.querySelector('#q20-'+id);
 function branches(p,m,xmin,xmax,ymax){const branch=y=>m.a*Math.sqrt(1+y*y/(m.b*m.b));for(const sign of [-1,1]){let prev=null;for(let i=0;i<=200;i++){const y=ymax*i/200,point=[sign*branch(y),y];if(prev&&point[0]>=xmin-1&&point[0]<=xmax+1)p.line(prev,point,{stroke:C.ink,width:2});prev=point;}}}
 function render(){const m=H.hyperbola(state.a,state.fraction);el('a').value=state.a;el('a-value').textContent=Lab.fmt(state.a,4);el('direction').value=state.fraction;el('local').toggleAttribute('hidden',!construction.show(4));
  const far=m.A&&m.A[0]>40,finiteA=m.A&&Number.isFinite(m.A[0]),xmax=finiteA?Math.max(5,m.A[0]*1.08+.5):6,ymax=finiteA?Math.max(3.5,m.A[1]*1.14+.4):4;
  const p=Lab.plot(el('global'),{xmin:-4.1,xmax,ymin:-.7,ymax,pad:48});p.axes();branches(p,m,-4.1,xmax,ymax);p.dot(m.F1,'F₁',C.blue,-26,24);p.dot(m.F2,'F₂',C.green,12,24);p.screenMath(16,30,String.raw`\frac{x^2}{a^2}-\frac{y^2}{9-a^2}=1`,{size:19});
  if(construction.show(1)){const rayLength=Math.min((xmax+3)/m.u,m.s>0?ymax/m.s:Infinity),end=finiteA?m.A:[-3+rayLength*m.u,rayLength*m.s];p.line(m.F1,end,{stroke:C.gold,width:1.8,dash:'5 4'});p.screenMath(16,62,String.raw`\cos\theta\approx${M.number(m.u,4)}`,{color:C.gold,size:18});}
  if(construction.show(2)){p.dot(m.B,'B',C.gold,-19,-15);if(finiteA){p.line(m.B,m.A,{stroke:C.target,width:3.2});p.dot(m.A,state.fraction===1?'A（在横轴上）':'A',C.target,10,-12);}}
  if(construction.show(3)&&finiteA)p.line(m.A,m.F2,{stroke:C.green,width:2.6});
  if(construction.show(1))p.screenText(16,p.h-20,!m.valid?(state.fraction===0?'渐近边界：不存在右支有限交点 A':'水平边界：A 不在 x 轴上方'):far?'A 很远：左图自动缩小，右图保留焦点局部':'当前射线在右支上方有有限交点 A',{size:16,color:m.valid?C.gray:C.target});p.finish();
  if(construction.show(4)){const R=2*m.a,xmin=Math.min(-3-R,m.B[0])-.4,xmaxLocal=Math.max(-3+R,m.B[0])+.4,ymaxLocal=Math.max(R,m.B[1])+.65,q=Lab.plot(el('local'),{xmin,xmax:xmaxLocal,ymin:-.7,ymax:ymaxLocal,pad:44});q.line([xmin,0],[xmaxLocal,0],{stroke:C.gray,width:1});branches(q,m,xmin,xmaxLocal,ymaxLocal);q.curve(x=>Math.sqrt(Math.max(0,R*R-(x+3)*(x+3))),-3-R,-3+R,{stroke:C.target,width:2.7});q.line(m.F1,m.B,{stroke:C.blue,width:3.2});q.dot(m.F1,'F₁',C.blue,-24,24);q.dot(m.B,'B',C.gold,12,-14);q.screenText(16,26,'左焦点局部 · 半径 2a 的目标圆',{size:17,color:C.target});q.screenMath(16,q.h-50,String.raw`BF_1\approx${M.number(m.r,4)},\quad 2a=${M.number(2*m.a,4)}`,{size:20,color:C.target});if(construction.show(5))q.screenMath(16,q.h-18,String.raw`\frac a3<\cos\theta<1`,{size:19,color:C.gold});q.finish();}else el('local').replaceChildren();
  const warning=[state.attempt&&!m.possible?'此 a 不存在满足所有原条件的方向。':'',!m.valid?(state.fraction===0?'当前为渐近方向，A 不存在。':'当前为水平轴，违反 A 在上方。'):''].filter(Boolean).join(' ');
  el('readout').innerHTML=`${m.valid?`<span>${M.inline(String.raw`AB\approx${M.number(m.AB,3)}`)}</span><span>${M.inline(String.raw`AF_2\approx${M.number(m.AF2,3)}`)}</span><strong class="target">${M.inline(String.raw`AB-AF_2=2a-BF_1\approx${M.number(m.difference,4)}`)}</strong>`:''}${warning?`<span class="warning">${warning}</span>`:''}${M.answer(`（1）${M.inline('c=5')}；（2）${M.inline(String.raw`k_l=\frac12`)}；（3）${M.inline(String.raw`1<a<\frac3{\sqrt5}`)}。`)}`;
 }
 function attempt(){state.attempt=true;const m=H.hyperbola(state.a,state.fraction),f=(m.targetU-state.a/3)/(1-state.a/3);if(f>=-1e-12&&f<=1+1e-12)state.fraction=Math.abs(f)<1e-12?0:Math.abs(f-1)<1e-12?1:f;render();}
 el('a').oninput=e=>{state.a=+e.target.value;state.attempt=false;render();};el('direction').oninput=e=>{state.fraction=+e.target.value;state.attempt=false;render();};el('target').onclick=attempt;el('left').onclick=()=>{state.a=1;attempt();};el('right').onclick=()=>{state.a=3/Math.sqrt(5);attempt();};el('example').onclick=()=>{state.a=1.2;attempt();};return{render,...construction.api,getState:()=>({...state,...H.hyperbola(state.a,state.fraction)}),reset(){state={a:1.2,fraction:.7,attempt:false};construction.restart();render();}};
}};
