(() => {
 const poly=x=>16-((x+2)**2-5)**2;
 function model(c){const roots=[];for(const sign of [1,-1]){if(16-sign*c<0)continue;for(const z of [5-Math.sqrt(16-sign*c),5+Math.sqrt(16-sign*c)]){if(z<-1e-10)continue;for(const x of [-2-Math.sqrt(Math.max(0,z)),-2+Math.sqrt(Math.max(0,z))])if(!roots.some(y=>Math.abs(x-y)<1e-7))roots.push(x);}}return{c,roots:roots.sort((a,b)=>a-b)};}
 Problems[11]={title:'对称四次函数怎样出现七个零点',model,
 statement:`函数 ${M.inline(String.raw`y=|(1-x^2)(x^2+ax+b)|-c\quad(c\ne0)`)} 的图像关于 ${M.inline('x=-2')} 对称，且恰有 7 个零点，求 ${M.inline('a+b+c')}。`,
 mount(host){let c=9;const C=Lab.C,$=s=>host.querySelector('#js24-11-'+s);
 host.innerHTML=`<div class="controls"><label>水平线高度 c <input id="js24-11-c" aria-label="水平线高度 c" type="range" min="0.1" max="18" step="0.1" value="9"></label><button id="js24-11-seven">七个零点 c = 9</button><button id="js24-11-max">外峰 c = 16</button></div><div class="figures"><svg id="js24-11-svg" class="main-figure" role="img" aria-label="对称四次函数绝对值与水平线的交点"></svg></div><div class="readout" id="js24-11-readout"></div><div class="explain"><section class="proof-step"><h3>① 绝对值的对称性确定多项式</h3><p>记 ${M.inline('p(x)=(1-x^2)(x^2+ax+b)')}。由 ${M.inline('|p(x)|=|p(-4-x)|')} 得两个平方多项式恒等，即 ${M.inline(String.raw`[p(x)-p(-4-x)][p(x)+p(-4-x)]\equiv0`)}。多项式环无零因子，且两者首项均为 ${M.inline('-x^4')}，所以只能有 ${M.inline('p(x)=p(-4-x)')}。</p><p>${M.inline('p(1)=p(-1)=0')}，对称性还给出零点 ${M.inline('-5,-3')}。四个零点及首项确定</p>${M.block(String.raw`p(x)=-(x-1)(x+1)(x+3)(x+5).`)}<p>因此 ${M.inline('a=8,b=15')}。</p></section><section class="proof-step"><h3>② 平移到对称中心，看清三个峰</h3><p>令 ${M.inline('u=x+2')}，则</p>${M.block(String.raw`p(x)=16-(u^2-5)^2.`)}<p>${M.inline('|p|')} 有四个零点；中央峰值为 ${M.inline('|p(-2)|=9')}，两侧峰值均为16，外侧两段向正无穷增长。解原函数零点等价于将水平线 ${M.inline('y=c')} 与 ${M.inline('y=|p(x)|')} 相交；显然 ${M.inline('c>0')}。</p></section><section class="proof-step"><h3>③ 在临界高度数不同交点</h3><p>${M.inline('0<c<9')}：8点；${M.inline('c=9')}：中央两点合并，7点；${M.inline('9<c<16')}：6点；${M.inline('c=16')}：两侧分别合并，4点；${M.inline('c>16')}：只剩外侧2点。</p><p>也可从 ${M.inline(String.raw`p(x)=\pm c`)} 精确核对：</p>${M.block(String.raw`u^2=5\pm\sqrt{16\mp c}.`)}<p>在 ${M.inline('c=9')}，${M.inline('p=-9')} 给出 ${M.inline(String.raw`u=0,\pm\sqrt{10}`)} 三点，${M.inline('p=9')} 给出 ${M.inline(String.raw`u=\pm\sqrt{5\pm\sqrt7}`)} 四点。</p><div class="target">${M.block(String.raw`a+b+c=8+15+9=32.`)}</div></section></div>`;
 function render(){const s=model(c),p=Lab.plot($('svg'),{xmin:-5.65,xmax:1.65,ymin:-1,ymax:19,equal:false,pad:49});p.axes({stepX:1,stepY:4});p.curve(x=>Math.abs(poly(x)),-5.65,1.65,{stroke:C.blue,width:2.5,n:800});p.line([-2,-1],[-2,19],{stroke:C.gray,width:1,dash:'5 5'});p.line([-5.65,c],[1.65,c],{stroke:C.target,width:2});s.roots.forEach(x=>p.dot([x,c],'',C.target));p.text([-2,9],'中央峰 9',{color:C.gold,dx:15,dy:-18,size:16});p.text([-2+Math.sqrt(5),16],'侧峰 16',{color:C.gold,dx:-8,dy:-18,size:16});p.finish();$('c').value=c;$('readout').innerHTML=`当前 ${M.inline('c='+c.toFixed(2))}，不同交点 ${s.roots.length} 个；图中水平线交点与原函数零点一一对应。${M.answer(M.inline('a+b+c=32'))}`;}
 $('c').oninput=e=>{c=+e.target.value;render();};$('seven').onclick=()=>{c=9;render();};$('max').onclick=()=>{c=16;render();};render();return{render,reset(){c=9;render();},getState:()=>model(c)};
 }};
})();
