(() => {
 function corner(beta){const a=beta*Math.PI/180,s=Math.sin(a),c=Math.cos(a),L=(1.8*(s+c)-1.2)/(s*c),H=[-L*c,0],G=[0,L*s],E=[H[0]-1.2*s,1.2*c],F=[-1.2*s,G[1]+1.2*c];return{beta,L,H,G,E,F,O:[-1.8,1.8]};}
 Problems[19]={title:'冰箱过门与直角转弯的几何约束',model:corner,
 statement:`（1）冰箱纵截面为矩形 ${M.inline('ABCD')}，${M.inline(String.raw`AD=0.8\,\mathrm{m},AB=2.4\,\mathrm{m}`)}，门高 ${M.inline(String.raw`2.3\,\mathrm{m}`)}。底面与地面夹角不超过 ${M.inline(String.raw`\pi/4`)}，且底面至少两个顶点接地。以 ${M.inline(String.raw`\alpha=\pi/4`)} 倾斜进门，能否通过？<br>（2）另一旧冰箱水平推运，其水平截面为矩形 ${M.inline('EFGH')}，${M.inline(String.raw`EH=1.2\,\mathrm{m}`)}。直角过道两侧宽度均为 ${M.inline(String.raw`1.8\,\mathrm{m}`)}。恰卡住时，${M.inline('H,G')} 分别在外墙射线 ${M.inline('PR,PQ')} 上，内墙角点 ${M.inline('O')} 在线段 ${M.inline('EF')} 上，设 ${M.inline(String.raw`\angle PHG=\beta`)}。用 ${M.inline(String.raw`\beta`)} 表示 ${M.inline('EF')} 并求最小值，据此求可推运冰箱高度的最大值（精确到 ${M.inline(String.raw`0.1\,\mathrm{m}`)}）。`,
 mount(host){let part='door',angle=45;const C=Lab.C,$=s=>host.querySelector('#js24-19-'+s);
 host.innerHTML=`<div class="controls"><label>情境 <select id="js24-19-part"><option value="door">（1）倾斜通过门洞</option><option value="corner">（2）水平转过墙角</option></select></label><label>角度 <input id="js24-19-angle" aria-label="冰箱倾角" type="range" min="0" max="45" step="0.5" value="45"></label><button id="js24-19-critical">45° 临界构型</button></div><div class="figures"><svg id="js24-19-plan" class="figure" role="img" aria-label="冰箱截面与门或过道的真实几何关系"></svg><svg id="js24-19-curve" class="figure" role="img" aria-label="倾角与所需高度或可转弯长度"></svg></div><div class="readout" id="js24-19-readout"></div><div class="explain"><section class="proof-step"><h3>① 过门高度来自两条边的竖直分量</h3>${M.block(String.raw`h(\alpha)=2.4\cos\alpha+0.8\sin\alpha.`)}<p>当 ${M.inline(String.raw`\alpha=\pi/4`)} 时，</p><div class="target">${M.block(String.raw`h=\frac{3.2}{\sqrt2}=1.6\sqrt2\approx2.263<2.3.`)}</div><p>所以按该角度倾斜可通过门洞。图中以接地边的截面点 ${M.inline('A')} 为支点；另一个接地顶点沿冰箱厚度方向，不在此截面内。</p></section><section class="proof-step"><h3>② 卡住时，内墙角位于长边上</h3><p>令 ${M.inline('P=(0,0),O=(-1.8,1.8)')}，长边方向为 ${M.inline(String.raw`(\cos\beta,\sin\beta)`)}，短边长为1.2。把角点在短边法向上的投影相等：</p>${M.block(String.raw`L\sin\beta\cos\beta+1.2`)}${M.block(String.raw`=1.8(\sin\beta+\cos\beta).`)}<div class="target">${M.block(String.raw`L=EF=\frac{1.8(\sin\beta+\cos\beta)-1.2}{\sin\beta\cos\beta},`)}${M.block(String.raw`0<\beta<\frac\pi2.`)}</div><p>两条外墙给出 ${M.inline(String.raw`H=(-L\cos\beta,0),G=(0,L\sin\beta)`)}；两端到角点的沿边距离都为正，角点确在线段 ${M.inline('EF')} 内。</p></section><section class="proof-step"><h3>③ 最窄的构型决定能否转过整个墙角</h3><p>令 ${M.inline(String.raw`t=\sin\beta+\cos\beta\in(1,\sqrt2]`)}，则</p>${M.block(String.raw`L(t)=\frac{3.6t-2.4}{t^2-1},`)}${M.block(String.raw`L'(t)=\frac{-1.2(3t^2-4t+3)}{(t^2-1)^2}<0.`)}<p>故 ${M.inline(String.raw`t=\sqrt2`)}，即 ${M.inline(String.raw`\beta=\pi/4`)} 时取得最小值：</p><div class="target">${M.block(String.raw`L_{\min}=3.6\sqrt2-2.4\approx2.691\ \mathrm m.`)}</div><p>理论可通过的最大高度为上述阈值；按题目要求保留一位小数，答案 ${M.inline(String.raw`2.7\,\mathrm{m}`)}。</p></section></div>`;
 function render(){const a=angle*Math.PI/180,s=Math.sin(a),c=Math.cos(a),p=Lab.plot($('plan'),part==='door'?{xmin:-2.2,xmax:1.2,ymin:-.3,ymax:3.1,pad:35}:{xmin:-4.7,xmax:.5,ymin:-.5,ymax:4.7,pad:35});let value;
 if(part==='door'){const A=[0,0],D=[.8*c,.8*s],B=[-2.4*s,2.4*c],Cc=[B[0]+D[0],B[1]+D[1]];value=Cc[1];p.line([-2.1,0],[1.1,0],{stroke:C.ink,width:2.4});p.line([-2.1,2.3],[1.1,2.3],{stroke:C.gold,width:2.4});p.poly([A,D,Cc,B],{stroke:C.blue,fill:C.blue,opacity:.12,width:2.3});p.poly([A,D,Cc,B],{stroke:C.blue,width:2.3});for(const [name,P] of [['A',A],['B',B],['C',Cc],['D',D]])p.dot(P,name,C.blue);p.line([.95,0],[.95,value],{stroke:C.target,width:2.4});p.text([.95,value/2],value.toFixed(3)+' m',{color:C.target,anchor:'end',dx:-8,size:16});p.screenText(15,27,'门高 2.3 m',{color:C.gold,size:17});}
 else{const m=corner(angle);value=m.L;p.poly([[-4.7,1.8],[-1.8,1.8],[-1.8,4.7],[-4.7,4.7]],{fill:C.gray,opacity:.1,stroke:'none'});p.line([-4.7,0],[0,0],{stroke:C.ink,width:2.8});p.line([0,0],[0,4.7],{stroke:C.ink,width:2.8});p.line([-4.7,1.8],[-1.8,1.8],{stroke:C.gold,width:2.8});p.line([-1.8,1.8],[-1.8,4.7],{stroke:C.gold,width:2.8});p.poly([m.E,m.F,m.G,m.H],{stroke:C.blue,fill:C.blue,opacity:.13,width:2.2});p.poly([m.E,m.F,m.G,m.H],{stroke:C.blue,width:2.2});p.line(m.E,m.F,{stroke:C.target,width:3});for(const id of ['E','F','G','H'])p.dot(m[id],id,C.blue);p.dot(m.O,'O',C.gold,-20,-15);p.dot([0,0],'P',C.ink);p.screenText(15,27,'两侧过道均宽 1.8 m',{color:C.gold,size:17});}p.finish();
 const q=Lab.plot($('curve'),part==='door'?{xmin:0,xmax:45,ymin:2.15,ymax:2.58,equal:false,pad:49}:{xmin:15,xmax:75,ymin:2.5,ymax:4.6,equal:false,pad:49});q.axes({stepX:15,stepY:part==='door'?.1:.5,x:'角度 / °',y:'m'});const fn=t=>part==='door'?2.4*Math.cos(t*Math.PI/180)+.8*Math.sin(t*Math.PI/180):corner(t).L;q.curve(fn,part==='door'?0:15,part==='door'?45:75,{stroke:C.target,width:2.5});q.dot([angle,value],'当前',C.target,-45,-18);if(part==='door'){q.line([0,2.3],[45,2.3],{stroke:C.gold,width:1.7,dash:'5 4'});}else q.dot([45,3.6*Math.SQRT2-2.4],'最窄构型',C.green,-15,30);q.finish();$('part').value=part;$('angle').min=part==='door'?0:15;$('angle').max=part==='door'?45:75;$('angle').value=angle;$('readout').innerHTML=`当前角度 ${angle.toFixed(1)}°，${part==='door'?'所需竖直高度':'恰卡住的长边长度'}约 ${M.inline(value.toFixed(4))} 米。${M.answer(part==='door'?'45° 时高度约2.263米，可以通过2.3米门洞。':`最大高度 ${M.inline(String.raw`3.6\sqrt2-2.4\approx2.691`)} 米，按题意记作2.7米。`)}`;}
 $('part').onchange=e=>{part=e.target.value;angle=45;render();};$('angle').oninput=e=>{angle=+e.target.value;render();};$('critical').onclick=()=>{angle=45;render();};render();return{render,reset(){part='door';angle=45;render();},getState:()=>({part,angle,...(part==='door'?{height:2.4*Math.cos(angle*Math.PI/180)+.8*Math.sin(angle*Math.PI/180)}:corner(angle))})};
 }};
})();
