(() => {
 function chord(k,m){const d=16-8*k*m,y1=(4-Math.sqrt(d))/k,y2=(4+Math.sqrt(d))/k,A=[y1*y1/8,y1],B=[y2*y2/8,y2];return{k,m,A,B,length:Math.hypot(A[0]-B[0],A[1]-B[1]),dot:A[0]*B[0]+A[1]*B[1]};}
 function triples(t,r){const u=[r*r,r,1],chords=u.map(v=>{const m=-t-v,c=chord(1,m),distance=v/Math.SQRT2;return{...c,u:v,distance,area:.5*c.length*distance};});return{t,r,u,chords,distanceRatio:1/r,areaRatios:[chords[1].area/chords[0].area,chords[2].area/chords[1].area]};}
 Problems[20]={title:'平行抛物线弦与两组等比数列',model:{chord,triples},
 statement:`三条直线 ${M.inline(String.raw`l_i:y=kx+m_i\ (i=1,2,3)`)} 分别与抛物线 ${M.inline(String.raw`\Gamma:y^2=8x`)} 交于 ${M.inline('A_i,B_i')}。定点 ${M.inline('T(t,0)')} 满足 ${M.inline('m_1<m_2<m_3<-t')}；点 ${M.inline('T')} 到直线 ${M.inline('l_i')} 的距离为 ${M.inline('d_i')}，${M.inline(String.raw`\triangle TA_iB_i`)} 面积为 ${M.inline('S_i')}。<br>（1）${M.inline('l_3')} 倾角45°且过焦点，求 ${M.inline('l_3')}。<br>（2）${M.inline(String.raw`\overrightarrow{OA_1}\cdot\overrightarrow{OB_1}=0`)} 且 ${M.inline(String.raw`km_1\ne0`)}，证明 ${M.inline('l_1')} 过定点。<br>（3）当 ${M.inline('k=1')}，是否存在 ${M.inline('T')} 使 ${M.inline('S_1,S_2,S_3')} 与 ${M.inline('d_1,d_2,d_3')} 都成等比数列？求点 ${M.inline('T')} 或说明不存在。`,
 mount(host){let part='1',k=1,t=-2,r=2;const C=Lab.C,$=s=>host.querySelector('#js24-20-'+s);
 host.innerHTML=`<div class="controls"><label>小问 <select id="js24-20-part"><option value="1">（1）焦点弦</option><option value="2">（2）垂直弦的定点</option><option value="3">（3）两组等比数列</option></select></label><label id="js24-20-k-wrap">斜率 k <input id="js24-20-k" aria-label="斜率 k" type="range" min="0.8" max="2" step="0.02" value="1"></label><label id="js24-20-t-wrap">T 的横坐标 <input id="js24-20-t" aria-label="点 T 横坐标" type="range" min="-2.8" max="0" step="0.02" value="-2"></label><label id="js24-20-r-wrap">距离倒比 r <input id="js24-20-r" aria-label="距离倒比" type="range" min="1.2" max="3" step="0.05" value="2"></label><button id="js24-20-fixed">T = (−2, 0)</button></div><div class="figures"><svg id="js24-20-svg" class="main-figure" role="img" aria-label="抛物线上的平行弦、定点与三角形"></svg></div><div class="readout" id="js24-20-readout"></div><div class="explain"><section class="proof-step"><h3>① 焦点和倾角直接确定第一条直线</h3><p>${M.inline('y^2=8x')} 的焦点为 ${M.inline('F=(2,0)')}，倾角45°给出斜率1。</p><div class="target">${M.block(String.raw`l_3:y=x-2.`)}</div></section><section class="proof-step"><h3>② 垂直条件通过韦达定理转化</h3><p>令 ${M.inline('l_1:y=kx+m')}，其中 ${M.inline(String.raw`km\ne0`)}。联立抛物线得到</p>${M.block(String.raw`k^2x^2+(2km-8)x+m^2=0.`)}<p>所以</p>${M.block(String.raw`x_Ax_B=\frac{m^2}{k^2},\quad y_Ay_B=\frac{8m}{k}.`)}${M.block(String.raw`\overrightarrow{OA}\cdot\overrightarrow{OB}=\frac{m(m+8k)}{k^2}=0.`)}<p>排除 ${M.inline('m=0')} 后，${M.inline('m=-8k')}，即 ${M.inline('y=k(x-8)')}。</p><div class="target">${M.block(String.raw`\text{定点为 }(8,0).`)}</div><p>图中用正斜率作代表；代数结论涵盖任意非零斜率，不依赖图示范围。</p></section><section class="proof-step"><h3>③ 把距离与面积写成同一组正参数</h3><p>当 ${M.inline('k=1')}，令 ${M.inline('u_i=-t-m_i')}，则 ${M.inline('u_1>u_2>u_3>0')}。由弦端点方程可得</p>${M.block(String.raw`|A_iB_i|=8\sqrt{2-m_i},\qquad d_i=\frac{u_i}{\sqrt2},`)}${M.block(String.raw`S_i=2\sqrt2\,u_i\sqrt{u_i+t+2}.`)}<p>两交点不同保证根式内为正。距离成等比等价于 ${M.inline('u_2^2=u_1u_3')}。</p></section><section class="proof-step"><h3>④ 第二组等比条件迫使定点唯一</h3><p>由 ${M.inline('S_2^2=S_1S_3')} 及距离等比式，除去正因子并平方：</p>${M.block(String.raw`(u_2+t+2)^2=(u_1+t+2)(u_3+t+2).`)}${M.block(String.raw`(t+2)(2u_2-u_1-u_3)=0.`)}<p>三个正参数不同，且 ${M.inline('u_2^2=u_1u_3')}，由严格算术几何平均不等式得 ${M.inline('u_1+u_3>2u_2')}。故只能 ${M.inline('t=-2')}。</p><p>反过来，取任意 ${M.inline('u_1>u_2>u_3>0')} 成等比，令 ${M.inline('t=-2,m_i=2-u_i')}，所有题设成立，且 ${M.inline(String.raw`S_i=2\sqrt2\,u_i^{3/2}`)} 也成等比。</p><div class="target">${M.block(String.raw`\text{存在，且 }T=(-2,0).`)}</div></section></div>`;
 function render(){const triple=triples(t,r),items=part==='1'?[chord(1,-2)]:part==='2'?[chord(k,-8*k)]:triple.chords,all=items.flatMap(c=>[c.A,c.B]),xmax=Math.max(12,...all.map(P=>P[0]+1)),ymin=Math.min(-5,...all.map(P=>P[1]-1)),ymax=Math.max(9,...all.map(P=>P[1]+1)),p=Lab.plot($('svg'),{xmin:-3.5,xmax,ymin,ymax,pad:42});p.axes({stepX:5,stepY:5});p.curve(x=>Math.sqrt(8*x),0,xmax,{stroke:C.blue,width:2});p.curve(x=>-Math.sqrt(8*x),0,xmax,{stroke:C.blue,width:2});const colors=[C.target,C.green,C.gold];items.forEach((item,i)=>{const color=colors[i];p.line(item.A,item.B,{stroke:color,width:2.7});p.dot(item.A,'A'+(items.length>1?i+1:''),color);p.dot(item.B,'B'+(items.length>1?i+1:''),color);if(part==='2'){p.line([0,0],item.A,{stroke:C.gold,width:1.5,dash:'4 4'});p.line([0,0],item.B,{stroke:C.gold,width:1.5,dash:'4 4'});}if(part==='3'){p.poly([[t,0],item.A,item.B],{fill:color,opacity:.05,stroke:'none'});const foot=[t+triple.u[i]/2,-triple.u[i]/2];p.line([t,0],foot,{stroke:color,width:1.5,dash:'4 4'});}});if(part==='1')p.dot([2,0],'焦点 F',C.green);if(part==='2')p.dot([8,0],'定点 (8,0)',C.target,12,28);if(part==='3')p.dot([t,0],'T',C.target,-15,28);p.finish();$('part').value=part;$('k').value=k;$('t').value=t;$('r').value=r;$('k-wrap').hidden=part!=='2';$('t-wrap').hidden=part!=='3';$('r-wrap').hidden=part!=='3';$('fixed').hidden=part!=='3';$('readout').innerHTML=part==='1'?M.answer(M.inline('l_3:y=x-2')):part==='2'?`当前 ${M.inline('k='+k.toFixed(2))}，${M.inline('m=-8k')}；两向量内积约 ${M.inline(items[0].dot.toFixed(8))}。${M.answer('所有满足条件的直线都经过 (8,0)。')}`:`距离始终成等比，公比约 ${M.inline((1/r).toFixed(4))}。面积相邻比为 ${triple.areaRatios.map(x=>M.inline(x.toFixed(5))).join('，')}。${M.answer('两组同时等比 ⇔ T = (−2,0)。')}`;}
 $('part').onchange=e=>{part=e.target.value;render();};$('k').oninput=e=>{k=+e.target.value;render();};$('t').oninput=e=>{t=+e.target.value;render();};$('r').oninput=e=>{r=+e.target.value;render();};$('fixed').onclick=()=>{t=-2;render();};render();return{render,reset(){part='1';k=1;t=-2;r=2;render();},getState:()=>({part,k,t,r,...(part==='3'?triples(t,r):part==='2'?chord(k,-8*k):chord(1,-2))})};
 }};
})();
