(() => {
 const critical=6+2*Math.sqrt(3),f=x=>x*x/(2*(x*x-2*x+2));
 function roots(m){const d=m*m-12*m+24;if(d<-1e-9)return[];return [((m-Math.sqrt(Math.max(0,d)))/4),((m+Math.sqrt(Math.max(0,d)))/4)].filter((t,i,a)=>t>1+1e-10&&t<4-1e-10&&(!i||Math.abs(t-a[0])>1e-8)).map(t=>1+Math.log2(t));}
 const partition=n=>({n,interior:2**n,G:1/5,H:2**(n-1),product:2**(n-1)/5});
 Problems[21]={title:'“均值点”：割线斜率、函数值与对称求和',model:{roots,partition,f,critical},
 statement:`定义：若存在 ${M.inline(String.raw`x_0\in(a,b)`)}，使 ${M.inline(String.raw`f(x_0)=\frac{f(b)-f(a)}{b-a}`)}，称 ${M.inline('f')} 是 ${M.inline('[a,b]')} 上的“均值函数”，${M.inline('x_0')} 为“均值点”。<br>（1）判断 ${M.inline('y=x^2')} 是否为 ${M.inline('[1,2]')} 上的均值函数，并求均值点。<br>（2）${M.inline(String.raw`y=-2^{2x-1}+m2^{x-1}-12`)} 是 ${M.inline('[1,3]')} 上的均值函数，求 ${M.inline('m')} 的范围。<br>（3）${M.inline(String.raw`f(x)=\frac{x^2+a}{2(x^2-2x+2)}`)} 是 ${M.inline('[-2,2]')} 上的均值函数，且 ${M.inline('2/3')} 是均值点。任意分割 ${M.inline('[-2,0]')}，设 ${M.inline(String.raw`t_0=-2<t_1<\cdots<t_m<t_{m+1}=0`)}，${M.inline(String.raw`G=\sum_{i=0}^{m}|f(t_{i+1})-f(t_i)|`)}。将 ${M.inline('[0,2]')} 等分成 ${M.inline('2^n+1')} 份，内部点依次 ${M.inline(String.raw`x_1,\ldots,x_{2^n}`)}，${M.inline(String.raw`H=\sum_{i=1}^{2^n}f(x_i)`)}。求使 ${M.inline('HG>2023')} 的最小整数 ${M.inline('n')}。`,
 mount(host){let part='1',m=critical,n=4;const C=Lab.C,$=s=>host.querySelector('#js24-21-'+s);
 host.innerHTML=`<div class="controls"><label>小问 <select id="js24-21-part"><option value="1">（1）函数值等于割线斜率</option><option value="2">（2）参数与均值点</option><option value="3">（3）总变化与对称配对</option></select></label><label id="js24-21-m-wrap">参数 m <input id="js24-21-m" aria-label="参数 m" type="range" min="-5" max="18" step="0.05" value="9.464"></label><button id="js24-21-critical">临界 m = 6 + 2√3</button><button id="js24-21-excluded">被排除端点 m = 2</button><label id="js24-21-n-wrap">整数 n <input id="js24-21-n" aria-label="整数 n" type="range" min="0" max="16" step="1" value="4"></label><button id="js24-21-first">首次超过 2023</button></div><div class="figures"><svg id="js24-21-svg" class="main-figure" role="img" aria-label="均值点与分割求和的函数图形"></svg></div><div class="readout" id="js24-21-readout"></div><div class="explain"><section class="proof-step"><h3>① 定义比较的是函数值和割线斜率</h3><p>对 ${M.inline('f(x)=x^2')}，${M.inline('[1,2]')} 上割线斜率是 ${M.inline('(4-1)/(2-1)=3')}。均值点满足 ${M.inline('x_0^2=3')} 且在开区间内，因此</p><div class="target">${M.block(String.raw`x_0=\sqrt3\in(1,2).`)}</div><p>它是均值函数。定义中的左边是 ${M.inline('f(x_0)')}，不能误写成导数 ${M.inline("f'(x_0)")}。</p></section><section class="proof-step"><h3>② 把第二问化成参数函数的值域</h3><p>端点值为 ${M.inline('f(1)=m-14,f(3)=4m-44')}，割线斜率 ${M.inline('(3m-30)/2')}。令 ${M.inline(String.raw`t=2^{x_0-1}\in(1,4)`)}，均值条件化为</p>${M.block(String.raw`-2t^2+mt-12=\frac{3m-30}2,`)}${M.block(String.raw`m=2t+3+\frac3{2t-3},\qquad t\ne\frac32.`)}<p>在 ${M.inline('(1,3/2)')} 上，此式严格递减，值域 ${M.inline(String.raw`(-\infty,2)`)}。在 ${M.inline('(3/2,4)')} 上，导数为</p>${M.block(String.raw`2-\frac6{(2t-3)^2}.`)}<p>于 ${M.inline(String.raw`t=(3+\sqrt3)/2`)} 取得最小值 ${M.inline(String.raw`6+2\sqrt3`)}，靠近 ${M.inline('3/2')} 时趋于正无穷，故</p><div class="target">${M.block(String.raw`m\in(-\infty,2)\cup[6+2\sqrt3,+\infty).`)}</div><p>2 不取，因为对应 ${M.inline('x_0=1')} 是端点；另一个下界来自内部切点，可以取到。</p></section><section class="proof-step"><h3>③ 已知均值点先确定参数 a</h3>${M.block(String.raw`\frac{f(2)-f(-2)}4=\frac{4+a}{20},`)}${M.block(String.raw`f(2/3)=\frac{4+9a}{20}.`)}<p>二者相等，所以 ${M.inline('a=0')}。此时</p>${M.block(String.raw`f'(x)=\frac{x(2-x)}{(x^2-2x+2)^2}.`)}<p>在 ${M.inline('[-2,0]')} 上单调递减，任意分割中的绝对差都同向，故可首尾抵消：</p>${M.block(String.raw`G=f(-2)-f(0)=\frac15.`)}</section><section class="proof-step"><h3>④ 等分点关于 1 配对，每对函数值和为 1</h3>${M.block(String.raw`f(x)+f(2-x)=1.`)}<p>内部等分点满足 ${M.inline('x_i+x_{2^n+1-i}=2')}，所以 ${M.inline('H=2^{n-1}')}。${M.inline('n=0')} 时只有中点1，也有 ${M.inline('H=f(1)=1/2')}。</p>${M.block(String.raw`HG=\frac{2^{n-1}}5>2023\iff2^{n-1}>10115.`)}<p>因为 ${M.inline('2^{13}=8192<10115<16384=2^{14}')}，</p><div class="target">${M.block(String.raw`n_{\min}=15.`)}</div><p>图中点数很多时只抽取部分对称点显示，和式的结果始终使用精确配对公式。</p></section></div>`;
 function render(){let p;if(part==='1'){p=Lab.plot($('svg'),{xmin:.7,xmax:2.25,ymin:.5,ymax:4.7,equal:false,pad:49});p.axes({stepX:.5,stepY:1});p.curve(x=>x*x,.75,2.2,{stroke:C.blue,width:2.5});p.line([1,1],[2,4],{stroke:C.gold,width:2});p.line([.7,3],[2.25,3],{stroke:C.target,width:2,dash:'5 4'});p.dot([1,1],'(1,1)',C.blue);p.dot([2,4],'(2,4)',C.blue,-55,-15);p.dot([Math.sqrt(3),3],'均值点',C.target,10,28);p.screenText(18,27,'割线斜率 = 3；寻找函数值 = 3 的点',{size:17,color:C.target});}
 else if(part==='2'){const fn=x=>-2*(2**(x-1))**2+m*2**(x-1)-12,slope=(3*m-30)/2,values=Array.from({length:101},(_,i)=>fn(1+i/50)),lo=Math.min(slope,...values)-3,hi=Math.max(slope,...values)+3;p=Lab.plot($('svg'),{xmin:.9,xmax:3.1,ymin:lo,ymax:hi,equal:false,pad:49});p.axes({stepX:.5,x:'x',y:'y'});p.curve(fn,1,3,{stroke:C.blue,width:2.5});p.line([1,fn(1)],[3,fn(3)],{stroke:C.gold,width:1.4,dash:'5 4'});p.line([.9,slope],[3.1,slope],{stroke:C.target,width:2});for(const x of roots(m))p.dot([x,slope],'均值点',C.target,10,28);for(const x of [1,3]){p.dot([x,fn(x)],'',C.blue);p.circle([x,slope],.025,{stroke:C.target,fill:'var(--canvas)',width:1});}p.screenMath(18,27,String.raw`\text{割线斜率}=${slope.toFixed(3)}`,{color:C.target,size:17});}
 else{const N=2**n,pairs=Math.min(8,Math.floor(N/2));p=Lab.plot($('svg'),{xmin:-2.25,xmax:2.3,ymin:-.1,ymax:1.2,equal:false,pad:49});p.axes({stepX:1,stepY:.25});p.curve(f,-2,2,{stroke:C.blue,width:2.5});p.line([-2,.2],[-2,0],{stroke:C.target,width:3});p.dot([-2,.2],'f(−2)=1/5',C.target,10,-18);p.dot([0,0],'f(0)=0',C.target,8,28);p.line([1,-.1],[1,1.2],{stroke:C.gray,dash:'4 4',width:1});if(n===0)p.dot([1,.5],'唯一内点',C.green);else for(let j=0;j<pairs;j++){const i=1+Math.floor(j*(N/2-1)/Math.max(1,pairs-1)),x=2*i/(N+1),y=2-x;p.dot([x,f(x)],'',C.green);p.dot([y,f(y)],'',C.gold);p.line([x,f(x)],[y,f(y)],{stroke:C.gray,width:.7,dash:'3 5',opacity:.5});}p.screenMath(18,27,'f(x)+f(2-x)=1',{color:C.green,size:18});p.screenText(18,57,N>16?`共有 ${N} 个内点；图中抽取 ${pairs} 对`:`共有 ${N} 个内点，按中心对称配对`,{color:C.gray,size:15});}
 p.finish();$('part').value=part;$('m').value=m;$('n').value=n;for(const s of ['m-wrap','critical','excluded'])$(s).hidden=part!=='2';for(const s of ['n-wrap','first'])$(s).hidden=part!=='3';const sum=partition(n);$('readout').innerHTML=part==='1'?M.answer(M.inline(String.raw`x_0=\sqrt3`)):part==='2'?`当前 ${M.inline('m='+m.toFixed(5))}，开区间内有 ${roots(m).length} 个均值点。${M.answer(M.inline(String.raw`m<2\ \text{或}\ m\ge6+2\sqrt3`))}`:`${M.inline('n='+n)}，${M.inline('G=1/5')}，${M.inline('H='+sum.H)}，${M.inline('HG='+sum.product)}，${sum.product>2023?'已超过':'未超过'}2023。${M.answer(M.inline(String.raw`n_{\min}=15`))}`;}
 $('part').onchange=e=>{part=e.target.value;render();};$('m').oninput=e=>{m=+e.target.value;render();};$('n').oninput=e=>{n=+e.target.value;render();};$('critical').onclick=()=>{m=critical;render();};$('excluded').onclick=()=>{m=2;render();};$('first').onclick=()=>{n=15;render();};render();return{render,reset(){part='1';m=critical;n=4;render();},getState:()=>({part,m,roots:roots(m),...partition(n)})};
 }};
})();
